src/pages/docs/publishing-your-api/custom-doc-domains.md
src/pages/docs/publishing-your-api/documenting-your-api.md
src/pages/docs/publishing-your-api/publishing-your-docs.md
src/pages/docs/publishing-your-api/viewing-documentation.md

Doc: Document your API
new procedures and screenshots

Documentation Flow Updates

---

src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md

updated 404 link to API Network.

updated old API Network link

---

src/components/Footer/Footer.data.json

To keep in sync with WWW site, I added in the "API Testing" link in first col of footer.

added link to API Testing page in footer

---

src/pages/docs/collaborating-in-postman/roles-and-permissions.md

Add community mgr role to docs

---

src/pages/docs/collaborating-in-postman/roles-and-permissions.md

Add more permissions

---

src/pages/index.jsx

Added livestreams to the bottom of the homepage with a custom component to track outgoing links in GA. 
Did not include Office Hours for now as I thought It'd probably be too long, and we may want to add them somewhere else as they're a different type of content.

More tweaks to Homepage

---

src/pages/docs/getting-started/installation-and-updates.md

Based on [slack convo](https://postman.slack.com/archives/C013AHDG9DZ/p1608324466048500?thread_ts=1607968880.044900&cid=C013AHDG9DZ)

Add agent video link

---

src/pages/docs/integrations/intro-integrations.md
src/pages/docs/integrations/webhooks.md

- intro integrations page is fully updated.
- custom webhooks page needs a valid webhook to update steps and screenshots for backing up Postman Collections

Updated steps and screenshots for integrations.

---

src/pages/docs/collaborating-in-postman/commenting-on-collections.md
src/pages/docs/collaborating-in-postman/version-control-for-collections.md
src/pages/docs/getting-started/installation-and-updates.md
src/pages/docs/getting-started/navigating-postman.md
src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
src/pages/docs/sending-requests/authorization.md
src/pages/docs/sending-requests/examples.md
src/pages/docs/sending-requests/troubleshooting-api-requests.md
src/pages/docs/writing-scripts/script-references/variables-list.md

This resolves #2741 (for now at least til new videos are released). Links bring users to each video within the playlist to encourage them to check others out as well.
cc @loopDelicious

Add level up videos to sidebar

---

src/components/MarketingPages/Cards.scss

Fixed Card (with circle image) hover state to show orange when user hovers anywhere on card.

fixed card hover state

---

src/pages/docs/integrations/available-integrations/coralogix.md

Updated screenshots and wording for Postman steps.

Updated Coralogix screenshots and wording for Postman steps

---

src/pages/docs/administration/buying.md

Purchasing page v8 link fix

---

src/pages/docs/collaborating-in-postman/roles-and-permissions.md

Probably could've grouped this with something else 😅

Roles and permissions v8

---

src/pages/docs/getting-started/postman-account.md

Updated screenshots and some language

Account page v8

---

src/pages/docs/collaborating-in-postman/commenting-on-collections.md

Updated screenshot
Page restructure - dashboard/web section removed

Commenting on collections

---

src/pages/docs/getting-started/sending-the-first-request.md

Sending your first request

---

src/pages/docs/collaborating-in-postman/sharing.md

Updated screenshots and flow for **Sharing** page.

Sharing your work docs

---

src/pages/docs/getting-started/introduction.md

Just updating the template link from the intro page to use the new public workspace flow..

Explore update

---

src/pages/docs/sending-requests/requests.md

Requests doc updates for app V8

---

src/pages/docs/integrations/available-integrations/victorops.md

Updated VictorOps screenshots and steps

---

src/pages/docs/collaborating-in-postman/using-workspaces/conflicts.md
src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md

* Updated the flow and screenshots for `Managing workspaces` and `Resolving team conflicts` page

Managing workspaces docs

---

src/pages/docs/getting-started/creating-the-first-collection.md

Creating your first collection

---

src/pages/docs/sending-requests/generate-code-snippets.md

* Updated navigation text
* Replaced screenshots
* Updated supported languages

Generate code snippets for v8

---

src/pages/docs/running-collections/using-newman-cli/integration-with-travis.md

Updated collection link for Travis doc

---

DOCS_STYLE_GUIDE.md

Updated http link to be https.

http --> https in link

---

src/pages/docs/sending-requests/supported-api-frameworks/making-soap-requests.md

Updated broken link to SOAP template.

fixed 404 template link

---

src/pages/docs/integrations/available-integrations/bitbucket.md

bitbucket-update

---

src/pages/docs/getting-started/importing-and-exporting-data.md

Updated command to run ti correctly

updated command

---

src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md

Reverts postmanlabs/postman-docs#2854

Revert "Update view-and-analyze-api-reports.md"

---

CONTRIBUTING.md

Added development instructions for dynamic_blog feature flag in right sidebar.

Updated CONTRIBUTING file for dynamic blog feature

---

src/pages/docs/sending-requests/intro-to-collections.md
src/pages/docs/sending-requests/visualizer.md
src/pages/index.jsx

Added dynamic blog posts for two pages.

added dynamic blog posts to right sidebar

---

src/components/Footer/Footer.jsx
src/templates/doc.jsx

* wrapped left nav in <nav> landmark tag
* wrapped middle content area in <main> landmark tag
* wrapped right sidebar is <aside> landmark tag
* wrapped footer in <footer> landmark tag

refactored divs to use landmark tags for improved a11y

---

src/components/Shared/EditDoc.jsx
src/pages/docs/getting-started/creating-the-first-collection.md

* removed 404 link in sidebar
* added nofollow to GitHub edit button

Fix ext 4xx links

---

src/pages/docs/getting-started/introduction.md

@claireriley just adding links to the training workspaces 🙂

Adds training workspaces

---

src/pages/docs/sending-requests/generate-code-snippets.md

Add Level Up video as resource for generating code snippets

---

src/pages/docs/designing-and-developing-your-api/mocking-data/mocking-with-examples.md

Should link to the correct section

---

src/pages/docs/developer/intro-api.md

Updated the image for PR - https://github.com/postmanlabs/postman-docs/pull/2886

Postman API Updates

---

src/pages/docs/developer/intro-api.md

Fixes #2877 by @loopDelicious 
Updated the documentation as per the instructions given in the issue
I would like to add two images for more details regarding the forking for more clarity to the end user but the images in the repo are controlled via `https://assets.postman.com/postman-docs` so gave these images in the description of the PR.
NO need of testing .

Feat #2877: updated the docs of into-api.md

---

src/components/Footer/Footer.data.json

'Postman Enterprise' updated to 'Postman for Enterprises' in footer

updated copy for link in footer

---

CONTRIBUTING.md
DOCS_STYLE_GUIDE.md
README.md

Minor stuff from my first read-through

minor copy edits

---

src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md

To allow users to change the visibility of their default and personal workspaces.

Boostrap workspace

---

CONTRIBUTING.md
src/pages/docs/administration/upgrading-to-v8.md

* scanned LC with ScreamingFrog and fixed 302 for internal link
* augmented CONTRIBUTING doc to cover internal and external links best practices.

fixed 302 link; updated contributing doc about links

---

CONTRIBUTING.md

fixed extra space at end of line linting error.

fixed linting error

---

src/components/Footer/Footer.data.json

Updating "Contact Sales" link to point to form page, and match blog and (soon) WWW.

updated Contact Sales link

---

src/components/layout.scss
src/pages/docs/publishing-your-api/publishing-your-docs.md

* added the latest Level Up video (Public Profiles) embed to the /docs/publishing-your-api/publishing-your-docs/ page
* added a margin-bottom style to all responsive iframe video embeds to move them off the copy following them.

added Level Up video; added margin-bottom to all responsive video embeds

---

src/components/seo.jsx

* added prefetches for google, polyfil and bootstrap assets
* added missing crossOrigin to existing preconnect
* test in Chrome and Safari (output below)
*

Update preconnects and prefetches, added missing crossOrigin

---

src/components/CookieAlert.jsx
src/components/Shared/EditDoc.jsx

Fixed up a couple files that the linter found issues with.

linter fixes

---

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/setting-up-monitor.md

https://postman.slack.com/archives/CKYBLA9JB/p1616713601108300

Added space

---

src/pages/auto-flex-policy.jsx

URL: /auto-flex-policy/
New page so that it can referenced from any blog post, "Learn about auto-flex" sections of the product and also from the product docs/FAQ in the LC.
cc: @jkonrath-postman @tristandenyer

Auto-Flex Policy page hosted to LC

---

src/pages/docs/collaborating-in-postman/adding-private-network.md
src/pages/docs/collaborating-in-postman/versioning-an-api.md
src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md
src/pages/docs/getting-started/introduction.md
src/pages/docs/integrations/available-integrations/aws-api-gateway.md
src/pages/docs/integrations/available-integrations/bitbucket.md

updated old links that were redirecting issue: 2928

---

src/pages/docs/designing-and-developing-your-api/the-api-workflow.md

* Change images with Define tab on them to show navigation tree
* Add description of navigation tree
* Add expand/collapse
* Add jump to references (plus new screenshot)

PC-46 Doc ADM schema navigation

---

src/pages/docs/administration/upgrading-to-v8.md
src/pages/docs/getting-started/navigating-postman.md

* Adding Universal Search docs section to LC. Related issue - #2906 
* Level-up video for **Universal Search** added to the sidebar.
* Blog post added
* Redirection links for search

Universal Search Functionality

---

src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md

* Moved contents to top above getting started
* Added section on moving mock servers + image

PC-47 Doc moving mock servers

---

src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md

Reverts postmanlabs/postman-docs#2942
Hold off on this until I get an all-clear that it shipped

Revert "PC-47 Doc moving mock servers"

---

src/pages/docs/running-collections/working-with-data-files.md
src/pages/docs/sending-requests/requests.md

* Loop through a data file
* Upload a File via POST Request

Level-up videos

---

src/pages/auto-flex-policy.jsx

Updated title tag, H1, and 2 places in the body copy.

[PC-48] updated title

---

src/pages/auto-flex-policy.jsx

Removed duplicative site name from title tag

[PC-48] fixed title tag text

---

src/pages/auto-flex-policy.jsx
src/pages/docs/integrations/intro-integrations.md

Updating Auto-flex page title and copy.

Dev --> Prod

---

src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md

https-update

---

src/pages/docs/administration/billing.md

Screenshots from figma as needed, includes update of larger page

Add auto-flex docs

---

src/pages/docs/sending-requests/authorization.md

Added information regarding authorizing using the browser

Update Authorize using browser info

---

src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md

Updated the commands for the installation of certificates in for the Linux distributions

Updated certificate installation commands for Linux

---

src/pages/index.jsx

Convert functional component into React Class based component, added pixel on mount.

Add pixel to homepage

---

redirects.json
src/pages/docs/administration/managing-your-team/managing-your-team.md
src/pages/docs/administration/managing-your-team/user-groups.md
src/pages/docs/collaborating-in-postman/collaboration-intro.md
src/pages/docs/collaborating-in-postman/roles-and-permissions.md
src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md

Approved here: https://github.com/postmanlabs/postman-docs/pull/2934

Publish groups docs

---

src/components/Footer/Footer.data.json
src/components/Footer/__snapshots__/Footer.spec.jsx.snap

* in support of migrating the resellers page, this is updating the link in the footer

update footer Resellers link

---

src/pages/docs/getting-started/introduction.md

Update this URL to `/managing-your-team/managing-your-team/` as `/managing-your-team/` triggers a redirect.
This will test if the redirected link on /introduction/ is causing CloudFront to send a 403.

Update URL for /managing-your-team/managing-your-team/ link

---

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/monitoring-apis-websites.md

Add related blog post link for /monitoring-your-api

---

package-lock.json
package.json

* removed the react-router package since it was not being used
* regenerated package-lock.json file
* Acceptance Criteria: no changes to app; pages should paginated and route as they do today. This change should have no negative impact and no regressions.

[MARKENG-118] remove unused package; re-generated package-lock

---

src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md

* Updated the image in question
* Updated a few more images
* General edits

Issue 1809 - Jenkins command doesn't match image

---

src/pages/docs/collaborating-in-postman/collaboration-intro.md
src/pages/docs/designing-and-developing-your-api/monitoring-your-api/setting-up-monitor.md
src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md

* Added that you can opt in/out of notifications by clicking your avatar and selecting the notifications thing
* A minor typo

Issue 2060 notifications

---

src/pages/docs/sending-requests/managing-environments.md

Export environment

---

src/pages/docs/sending-requests/supported-api-frameworks/making-soap-requests.md

Update SOAP template and Public SOAP APIs links to point to public SOAP workspace
https://github.com/postmanlabs/postman-docs/issues/3021

3021 - Fix dead link and update existing on /making-soap-requests/

---

src/pages/docs/collaborating-in-postman/public-workspaces.md
src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
src/pages/docs/collaborating-in-postman/using-workspaces/conflicts.md
src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md

New page for public workspaces

Public workspaces

---

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors.md
src/pages/docs/getting-started/settings.md
src/pages/docs/running-collections/intro-to-collection-runs.md
src/pages/docs/sending-requests/variables.md

To remove "Automatically persist variable values" section

---

src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md
src/pages/docs/sending-requests/cookies.md

Syncing cookies for authentication
Run collections with Newman

V8 level up videos

---

src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
src/pages/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors.md

Postman plan upgrade - Multi region monitoring and changelog

---

src/pages/docs/collaborating-in-postman/public-workspaces.md

Adding so that it's easier for users to find how to make their public workspace and its elements discoverable on the network.

Add summary, category level up video on public workspace sidebar

---

src/pages/index.jsx

Modify anchor link from upcoming-postman-livestreams to upcoming-livestreams

---

src/pages/docs/administration/billing.md

Small fix for jira TW-44 (also confirming with Shreyas there).

TW-44 billing

---

src/pages/docs/collaborating-in-postman/public-workspaces.md

Add public workspace exploratory video to sidebar resources

---

src/pages/docs/getting-started/importing-and-exporting-data.md
src/pages/docs/sending-requests/capturing-request-data/proxy.md
src/pages/docs/sending-requests/certificates.md
src/pages/docs/sending-requests/responses.md

A continuation of #3096 - there were a few other places that the wrench icon was mentioned instead of the gear icon.

Change wrench to gear

---

src/pages/docs/api-security/api-schema.md

Made several updated to the titles.

Title changes api schema

---

src/pages/docs/api-security/api-schema.md

Changed to OAuth

---

src/pages/docs/administration/sso/saml-in-azure-ad.md

AD FS is different from Azure AD

One should select SAML 2.0 and not AD FS.

---

src/components/Footer/Footer.data.json
src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md
src/pages/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors.md
src/pages/docs/designing-and-developing-your-api/monitoring-your-api/monitoring-apis-websites.md
src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md
src/pages/docs/getting-started/importing-and-exporting-data.md
src/pages/docs/getting-started/syncing.md
src/pages/docs/publishing-your-api/authoring-your-documentation.md
src/pages/docs/publishing-your-api/custom-doc-domains.md
src/pages/docs/publishing-your-api/documenting-your-api.md
src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
src/pages/docs/publishing-your-api/viewing-documentation.md
src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md
src/pages/docs/running-collections/using-newman-cli/continuous-integration.md
src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md
src/pages/docs/running-collections/using-newman-cli/integration-with-travis.md
src/pages/docs/sending-requests/authorization.md
src/pages/docs/sending-requests/examples.md
src/pages/docs/sending-requests/generate-code-snippets.md
src/pages/docs/sending-requests/intro-to-collections.md
src/pages/docs/writing-scripts/intro-to-scripts.md
src/pages/docs/writing-scripts/pre-request-scripts.md
src/pages/docs/writing-scripts/test-scripts.md

* Customers is now Case Studies (/customers/ --> /case-studies/)
* Removed missing case studies
* Updated label and link in footer

[MARKENG-236] [c] updated /customers/ to /case-studies/; removed missing case studies

---

src/pages/docs/sending-requests/variables.md

Clarification to empty current value of variable

---

src/pages/docs/getting-started/troubleshooting-inapp.md

* New image
* Updated UI interaction as per MMoS
* New headings
* General edit

Update troubleshooting-inapp.md for v8

---

src/pages/docs/integrations/available-integrations/github.md

* Addresses Issue 3026 - include "Update collection" flow
* Restructured doc
* New screenshots
* More updates to latest version of integration

Issue 3026 GitHub integration updates

---

src/pages/docs/api-security/security-warnings.md

Updated the gif for possible fix redirect to LC

Security warnings - Possible fix GIF 

---

src/pages/docs/sending-requests/capturing-request-data/interceptor.md

This is based on PR #2416 
I couldn't cleanly merge the old PR because everything's moved, so I started a new one. I also streamlined this a bit and moved it into the troubleshooting section.

Use a flavor of chromium other than chrome with interceptor

---

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/setting-up-monitor.md

Update screenshot and wording

---

src/components/Footer/Footer.data.json
src/components/Footer/Footer.jsx

Minor updates to footer links:
* added label and link to Breaking Changes Show
* all Postman Marketing site links open in new tab (with tabnabbing protection in place)

Footer: Added Breaking Changes link; now opening links in new tab

---

src/pages/docs/administration/managing-your-team/configuring-scim.md

For upcoming Okta Postman app provisioning release!

SCIM Okta additions

---

src/pages/docs/administration/managing-your-team/configuring-scim.md

Blogpost for SCIM

---

src/pages/docs/getting-started/introduction.md
src/pages/docs/getting-started/postman-account.md

Introduction and account page reverts

---

src/pages/docs/api-security/security-warnings.md

Blogpost for security warnings

---

src/pages/index.jsx

- Modified the admin card and replaced the content with the 30 days of Postman challenge
- Updated the description for the Postman Network card

Update descriptions and links for cards on Learning center home

---

src/pages/docs/designing-and-developing-your-api/mocking-data/mocking-with-examples.md

Added SOAP clients in addition to REST APIs as reported by user. 
Please re-word if required.

SOAP Clients as well

---

src/pages/docs/sending-requests/troubleshooting-api-requests.md

* Replaced all but one image
* Minor edits

Edits to troubleshooting topic for V8

---

src/pages/docs/sending-requests/cookies.md

Information added in `Using cookies` doc

---

src/pages/docs/getting-started/postman-account.md
src/pages/docs/getting-started/syncing.md
src/pages/docs/getting-started/using-scratch-pad.md

* New page
* Modifications to the syncing and managing account pages

TW-76 Scratch Pad docs

---

src/pages/docs/administration/billing.md

Update screenshot to reflect resource usage UI/UX update 

---

src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md

Added hyperlink to public workspaces doc. Reordered visibility dropdown info according to Postman app UI.

Add public workspaces info

---

src/pages/docs/administration/team-settings.md
src/pages/docs/publishing-your-api/publishing-your-docs.md

For [ESCALATION-774](https://postmanlabs.atlassian.net/browse/ESCALATION-774)

Add image req information

---

src/components/Footer/Footer.jsx
src/components/Footer/__snapshots__/Footer.spec.jsx.snap
src/pages/index.jsx

https://www.youtube.com/postmanapidevelopment is now https://www.youtube.com/c/Postman
* old URL does NOT redirect!
* update across LC

[MARKENG-358] updated YouTube profile URL

---

src/pages/index.jsx

@loopDelicious can you review this change once?

Adjust cards to add Postman Space Camp on Learning Center Home page

---

.github/ISSUE_TEMPLATE/documentation-request.md

Changing auto-assign and label on doc requests.

Update issue templates

---

package.json
src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md

Reverts postmanlabs/postman-docs#3212

Revert "Dev -> Prod"

---

src/pages/docs/integrations/available-integrations/github.md

testing out new link checker plugin.
This PR is a smoke test to:
* test build process of plugin
* test output to Actions console for WARN and ERR
* to see if it stops build and or pipeline
One link is explicitly broken. local build shows:

smoke test for beta build to test out link checker plugin process / coverage

---

src/pages/docs/integrations/available-integrations/github.md

reverting change + adding blog post to right sidebar

Broken link smoke test

---

src/pages/docs/sending-requests/troubleshooting-api-requests.md

* There's not a keyboard shortcut to open the console from Postman web
* General edits

[Issue-3231] keyboard shortcuts

---

src/pages/docs/getting-started/settings.md

Added some search keywords for keyboard shortcuts and GPU hardware acceleration.

Adding keywords to settings page

---

src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md

Minor test edit

---

src/pages/docs/sending-requests/supported-api-frameworks/websocket.md

Should not have trailing slash

Fix link on websocket page

---

src/pages/docs/sending-requests/capturing-request-data/interceptor.md

* Clarification that requests are saved in the history, or you can select a collection
* Screenshot of above dialog
* Minor edits around that

[IS-1754] Interceptor documentation update

---

.github/workflows/deploy.yml
.github/workflows/prod-deploy.yml
gatsby-config.js

moved gatsby plugin to last plugin and added settings, added GA pagev…iew indexing to development deploy to keep reindexing the same, removed old email - action - never worked
npm i
npm run build:prod && npm run serve
localhost:9000

Algolia adjustments

---

src/pages/docs/api-security/security-warnings.md

Minor URL fixes for SAST scanner v2

SAST scanner v2 - URL fix

---

src/pages/docs/getting-started/navigating-postman.md

Request to include and reword action of saving responses w.r.t Collection Run.

History on Collection runs.

---

src/pages/docs/getting-started/settings.md

- Updated settings descriptions to align with v8.9.1 UI and current style guide
- Reorganized content in the Working Directory section to be easier to scan

[TW-111] Settings page updates

---

src/pages/docs/administration/team-settings.md

Added requirements for uploading favicons in team settings

[TW-148] Add favicon specifications

---

src/pages/docs/administration/managing-your-team/managing-your-team.md
src/pages/docs/collaborating-in-postman/collaboration-intro.md
src/pages/docs/collaborating-in-postman/public-workspaces.md
src/pages/docs/collaborating-in-postman/version-control-for-collections.md
src/pages/docs/collaborating-in-postman/versioning-an-api.md
src/pages/docs/designing-and-developing-your-api/testing-an-api.md
src/pages/docs/designing-and-developing-your-api/the-api-workflow.md
src/pages/docs/developer/intro-api.md
src/pages/docs/getting-started/importing-and-exporting-data.md
src/pages/docs/getting-started/introduction.md
src/pages/docs/integrations/available-integrations/datadog.md
src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
src/pages/docs/sending-requests/capturing-request-data/proxy.md
src/pages/docs/sending-requests/supported-api-frameworks/websocket.md

Closes:
#3237 
#3234  
#3260 
#3267 
#3268 
#3262 
#3278 
#3277 
#3287 
#3300 
#3372 
#3376
#3242

Add devrel resources to sidebar batch 1

---

src/pages/docs/getting-started/introduction.md
src/pages/docs/running-collections/building-workflows.md
src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md

Add devrel resources to sidebar pt2 - videos

---

src/pages/docs/collaborating-in-postman/adding-private-network.md

Removed the steps on navigating to a private API network from the top section

Bug fix for Private API Network

---

src/pages/index.jsx
src/pages/index.scss

New fonts are in other branch, not yet merged

added video frame and change text positioning

---

ga_connector.js
gatsby-config.js
src/components/layout.scss
src/pages/index.jsx
src/pages/index.scss

- to run comment out algolia plugin in `gatsby-config.js`
-```npm run build:prod && npm run serve```

Markeng 560 - added events section

---

src/components/MarketingPages/Cards.jsx
src/pages/index.jsx

Hey @ch264 :D we needed to enable tracking of outboud links in the LandingCard component so I duplicated the original one and created one specific for cards containing an outbound link. Let me know if this would work or if you'd rather handle it directly in the LandingCard component?

Duplicated LandingCard component

---

src/pages/docs/getting-started/navigating-postman.md

Included a line over on the same. Please reword if needed.

Find and replace isn't present on Postman Web.

---

src/components/ContextualLinks/ContextualLinks.scss
src/components/Shared/_variables.scss
src/components/layout.scss
src/templates/doc.scss
styles/config/typography.css

* updated right sidebar styles to match Sandbox
* updated inline code styles

updated sidebar and code styles

---

src/pages/index.jsx

- updated copy of header on homepage events section

changes header of events section on homepage

---

src/pages/docs/integrations/available-integrations/keen.md

* Fixed links
* Also turned a procedure into a numbered list.

TW-194 broken Keen links

---

src/pages/docs/integrations/available-integrations/datadog.md

TW-192 Datadog link fix

---

src/components/Header/Header.jsx

Contact Us link is now under Support in Nav

IA: Move Contact Us under Support in Nav

---

src/components/Header/Header.jsx

updated label of sign up button

---

src/templates/doc.scss

Reverts postmanlabs/postman-docs#3480

Revert "offsets headers so they clear sticky nav when deep linking to element…"

---

src/templates/doc.scss

Reverts "titles clear the sticky nav" PR

Dev => Prod

---

src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md

This fixes the file upload example and status code test example.

Replace echo.getpostman.com with postman-echo.com

---

src/components/Header/Header.jsx
src/components/Header/Header.scss

Icon was causing issues on Safari. I removed the flipped icon css and updated the HTML to reflect the changes.

Remove flipped home icon in global nav

---

src/components/LeftNav/LeftNav.scss

[MARKENG-742] Remove white text on hover for nested side nav link

---

src/pages/docs/getting-started/installation-and-updates.md

See https://github.com/postmanlabs/postman-docs/issues/3493

System requirements edit

---

src/components/Shared/_variables.scss
src/components/seo.jsx

Commented out Google fonts to reduce requests on load. Verified fonts are displaying Degular Semibold and Inter.

[MARKENG-704] Disabled Google Fonts; Repo using imported fonts

---

src/pages/docs/designing-and-developing-your-api/mocking-data/matching-algorithm.md

This is based on https://github.com/postmanlabs/postman-docs/pull/3497 because I can't make changes to that branch.

Update matching-algorithm.md (2)

---

src/components/Header/Header.jsx
src/components/Header/Header.scss
src/components/Search/_search.scss
src/components/Search/searchPreview.jsx

changed search result styling

---

src/components/Footer/Footer.data.json
src/components/Footer/Footer.jsx

Ticket: https://postmanlabs.atlassian.net/browse/MARKENG-750
- remove external-postman enum
- make sure footer open in the same tab except social media

[MARKENG-750] Remove target _blank from LC footer

---

src/components/LeftNav/LeftNav.scss

- removed cursor pointer from caret when hovering

changed cursor style for left nav

---

src/pages/docs/administration/sso/saml-onelogin.md

* change Onelogin to OneLogin
* minor edits

TW-205 change Onelogin to OneLogin

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/manual-rerun.yml
.github/workflows/prod-deploy.yml
.gitignore
bff.js
gatsby-ssr.js
package-lock.json
package.json
src/pages/404.jsx

Branched from `develop`, this adds the pm-tech SDK (v1.1.9) & sets up testing for it on the 404 page
This is the fourth app that we are adding the SDK to. Testing from the 404 page is an incremental step before formally implementing across the app.

[MARKENG-401] pm tech SDK (v1.1.9) test on 404 page

---

src/pages/docs/administration/managing-enterprise-deployment.md
src/pages/docs/collaborating-in-postman/adding-private-network.md
src/pages/docs/designing-and-developing-your-api/creating-an-api.md
src/pages/docs/designing-and-developing-your-api/defining-an-api.md
src/pages/docs/designing-and-developing-your-api/deploying-an-api.md
src/pages/docs/designing-and-developing-your-api/developing-an-api.md
src/pages/docs/designing-and-developing-your-api/generating-server-code.md
src/pages/docs/designing-and-developing-your-api/managing-apis.md
src/pages/docs/designing-and-developing-your-api/observing-an-api.md
src/pages/docs/designing-and-developing-your-api/testing-an-api.md
src/pages/docs/designing-and-developing-your-api/the-api-workflow.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
src/pages/docs/integrations/available-integrations/ci-integrations/circleci.md
src/pages/docs/integrations/available-integrations/ci-integrations/travis-ci.md
src/pages/docs/integrations/ci-integrations.md

Adding some `updated` tags for things I know were fully reviewed for 9.0.
For review, just check that it builds without errors on your machine.

Retroactively add update dates

---

src/components/Header/Header.jsx

Added "State of the API" to the top nav

---

bff.js
package.json
src/components/layout.jsx
src/pages/404.jsx

_Branched from `develop`_, this enables pm-tech on all pages & remove the test config from the 404 page.
ATM, we are only testing pm-tech on the /404 page. This will make the marketing web app the next biggest Postman web app to have pm-tech submitting events on all pages.
_*will confirm on BETA, once merged_

[MARKENG-958] global pm tech

---

src/pages/docs/developer/code-generators.md
src/pages/docs/developer/collection-conversion.md
src/pages/docs/developer/collection-sdk.md
src/pages/docs/developer/resources-intro.md
src/pages/docs/developer/runtime-library.md
src/pages/docs/integrations/available-integrations/gitlab.md
src/pages/docs/publishing-your-api/viewing-documentation.md
src/pages/docs/running-collections/using-newman-cli/integration-with-travis.md
src/pages/docs/sending-requests/generate-code-snippets.md

* Mostly minor text edits
* I fixed some hyphenation globally

TW-263 refresh developer/code-generators

---

src/components/Header/Header.jsx

This improves the initial load state of our Sign In and Launch Postman buttons.
The button will display the correct one depending if a user is signed in or logged out in the navbar
.

[MARKENG-996] Improves Navbar Sign In and Launch Postman on load

---

src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md

Correct order:
- Global
- Collection
- Environment
- Data
- Local

Corrected collection and environment scope order

---

src/pages/docs/writing-scripts/script-references/test-examples.md

* image changes
* other minor edits

TW-237  Test script examples refresh

---

src/pages/index.jsx

We have a new "intro to Postman" video series from Valentin, this PR updates the now outdated one we have on the homepage with the new version. 📺

Updated YT video on homepage

---

src/pages/docs/designing-and-developing-your-api/versioning-an-api.md

Small addition to close #3670 (last automated devrel gh issue as we switch to jira)

Add devrel link to sidebar

---

CONTRIBUTING.md

This PR:
- Adds information about Apple M1 workflow to CONTRIBUTING.md
- Reformats the Development Process section to include subheadings for **Prerequisites** and **Workflow**
cc @tristandenyer

Add information about Apple M1 workflow to CONTRIBUTING.md

---

src/pages/docs/collaborating-in-postman/adding-private-network.md
src/pages/docs/collaborating-in-postman/collaboration-intro.md
src/pages/docs/collaborating-in-postman/sharing.md
src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md
src/pages/docs/getting-started/syncing.md
src/pages/docs/running-collections/intro-to-collection-runs.md
src/pages/docs/sending-requests/authorization.md
src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
src/pages/docs/sending-requests/managing-environments.md
src/pages/docs/sending-requests/variables.md
src/pages/docs/writing-scripts/script-references/test-examples.md
src/pages/docs/writing-scripts/test-scripts.md

This PR updates the first 5 folders' sidebars in the docs, removing older videos and replacing with updated content.

Update videos in sidebar

---

src/pages/docs/getting-started/installation-and-updates.md

* Added a note to say to download the right installer
* Changed installation to a numbered procedure
* You don't have to unzip the Mac installer anymore
* Other minor edits

TW-217 Doc Apple Silicon support

---

bff.js
src/components/layout.jsx

This simplifies the configuration for consuming the pm-tech SDK
There are several web apps that are consuming & configuring the SDK. This aims to simplify the process & make as consistent as we can.
_*no visuals (regressive)_

[MARKENG-1052][c] simplify process to consume pm-tech SDK

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/manual-rerun.yml
.github/workflows/prod-deploy.yml
scripts/fetchPmTech.js

This updates the fetch script for pmTech to use the correct tag for the web app.
ATM, it’s inadvertently using “covid-19-apis”
*no visuals _(regressive)_

[MARKENG-1060][c] update fetch script for pmTech to use “postman-docs”

---

src/pages/docs/developer/echo-api.md

* New screenshot
* Minor edits

TW-120  Echo page refresh

---

src/pages/docs/getting-started/navigating-postman.md
src/pages/docs/getting-started/settings.md
src/pages/docs/publishing-your-api/authoring-your-documentation.md
src/pages/docs/sending-requests/certificates.md
src/pages/docs/sending-requests/requests.md
src/pages/docs/sending-requests/responses.md
src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
src/pages/docs/sending-requests/troubleshooting-api-requests.md
src/pages/docs/sending-requests/variables.md

- Verified all keyboard shortcuts (that I could find) and corrected as needed
- Noted when shortcuts are for Postman app only
- Corrected formatting per Microsoft Style Guide

[TW-125] Fix keyboard shortcuts

---

gatsby-config.js

* updated robots.txt file to point to /sitemap/sitemap-index.xml, where the sitemap file is stored.

updated sitemap url

---

src/pages/docs/sending-requests/supported-api-frameworks/making-soap-requests.md

- Updated screenshots to reflect new UI
- Added numeric steps for users to follow
- General copyedits

TW-117 SOAP request page refresh

---

src/pages/docs/designing-and-developing-your-api/developing-an-api.md
src/pages/docs/designing-and-developing-your-api/testing-an-api.md
src/pages/docs/designing-and-developing-your-api/the-api-workflow.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api.md
src/pages/docs/getting-started/importing-and-exporting-data.md
src/pages/docs/getting-started/sending-the-first-request.md
src/pages/docs/publishing-your-api/authoring-your-documentation.md
src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
src/pages/docs/sending-requests/variables.md

Weeks 11/25/2021 and 12/5/2021

Add devrel content to sidebar

---

src/pages/docs/getting-started/sending-the-first-request.md

- Rewrote and edited "Sending your first request" page
- Added additional context
- Updated screenshot

[TW-292] Refresh "Sending your first request"

---

src/pages/docs/getting-started/importing-and-exporting-data.md

Note: first image is changing in the near future, so ignore that.

TW-259 Importing and Exporting refresh

---

src/pages/docs/sending-requests/supported-api-frameworks/graphql.md

- Refreshes content to clarify built-in support vs other methods
- Removes video from main content (already linked in sidebar)
- Updates screenshots
- Emphasizes that `POST` method must be used

TW-116 GraphQL page refresh

---

src/components/LeftNav/LeftNav.jsx

Related to failed merged - https://github.com/postmanlabs/postman-docs/actions/runs/1589800914

Update typeof document error in LeftNav.jsx

---

src/pages/docs/running-collections/building-workflows.md

- Rewrote and edited "Building request workflows" page
- Restructured content to be easier to scan

[TW-118] Refresh "Building request workflows"

---

src/pages/docs/designing-and-developing-your-api/observing-an-api.md
src/pages/docs/integrations/available-integrations/new-relic.md

- Clarify that there are two different New Relic integrations (for monitors and APM metrics)
- Clarify that the two integration types use different New Relic API keys
- Add descriptions of health status to "Observing an API" page
- Edit text and update some screenshots on "New Relic" page

[LAND-525] New Relic keys

---

src/pages/docs/getting-started/troubleshooting-inapp.md
src/pages/docs/sending-requests/troubleshooting-api-requests.md

- Refreshes and reorganizes content
- Reformats list of possible issues into table
- Links to other troubleshooting guides
- Removes content unrelated to troubleshooting _requests_

TW-291 Troubleshooting requests refresh

---

src/templates/doc.scss

Removed the orange hover for tables to reflect newest design system

[MARKENG-1089] Update table hover styles to reflect Postman Design System

---

gatsby-browser.js
src/templates/doc.jsx

This fixes the issue when anchor links are clicked and displays above the navbar which hides the title

Update display position of sections when <a> is clicked on through deeplinking

---

src/pages/docs/collaborating-in-postman/public-workspaces.md
src/pages/docs/getting-started/exploring-public-api-network.md
src/pages/docs/getting-started/navigating-postman.md

- Updates content and screenshots related to categories in the Public API Network
- General copyedits

TW-272 Categories in the Public API Network

---

src/components/Header/Header.jsx

public Algolia API key was updated for the front-end

Roll over Algolia key

---

src/pages/docs/administration/managing-your-team/managing-your-team.md
src/pages/docs/administration/managing-your-team/user-groups.md
src/pages/docs/collaborating-in-postman/roles-and-permissions.md

One additional screenshot to edit once UI is updated here: /docs/administration/team-settings/#understanding-roles-and-permissions, may be in a follow up PR if necessary.

Add docs for Super Admin feature

---

gatsby-node.js
src/templates/doc.jsx

This feature returns the latest git commit by the most recent author
- Added new field called lastModifiedDate that can be queried and returned n doc.jsx
- Display "Last Modified: YY:MM:DD" on Doc pages
- The "Last Modified" date displays on all MD files via GraphQL query

[MARKENG-1078] Add "Last Modified" date to Doc files

---

src/pages/docs/administration/managing-enterprise-deployment.md

[TW-234] Doc enterprise app for macOS 

---

src/pages/docs/sending-requests/variables.md

* added links to the updated images that were hard to see the text so they open in full.

added links to new, hard-to-read images on Variables doc

---

src/pages/docs/getting-started/creating-your-first-workspace.md

- Adds `search_keyword` to frontmatter 
- Converts narrative into step-by-step instructions
- Checked screenshots - no updates needed

TW 258 Refresh /getting-started/creating-your-first-workspace/

---

src/pages/docs/administration/managing-your-team/managing-your-team.md
src/pages/docs/collaborating-in-postman/collaboration-intro.md

- Adds a new section to https://learning.postman.com/docs/administration/managing-your-team/managing-your-team/ about removing team members
- Adds a sentence to https://learning.postman.com/docs/collaborating-in-postman/collaboration-intro/#leaving-a-team about leaving a team as an individual user

TW-187 Document what happens to data when user is removed from team

---

src/templates/doc.jsx

* changed class to be className on Last modified component, console error in dev mode

fix class to be className

---

src/pages/docs/administration/managing-enterprise-deployment.md

[TW-309] Update enterprise app screenshot

---

src/pages/docs/administration/managing-your-team/user-groups.md
src/pages/docs/collaborating-in-postman/requesting-access-to-collections.md
src/pages/docs/collaborating-in-postman/version-control-for-collections.md
src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
src/pages/docs/developer/intro-api.md
src/pages/docs/getting-started/navigating-postman.md
src/pages/docs/monitoring-your-api/faqs-monitors.md
src/pages/docs/monitoring-your-api/setting-up-monitor.md
src/pages/docs/monitoring-your-api/using-static-IPs-to-monitor.md
src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
src/pages/docs/running-collections/scheduling-collection-runs.md
src/pages/docs/sending-requests/intro-to-collections.md
src/pages/docs/sending-requests/managing-environments.md
src/pages/docs/writing-scripts/pre-request-scripts.md

* Updates instances of `...` to use image of the three dot icon
* Small copyedits to surrounding sentences to accommodate using the icon rather than ellipses

Updates instances of `...` to use image of the three dot icon

---

src/components/modules/PreviousAndNextLinks.jsx

* added unique classNames for pmtech
* added dynamic a11y labels and title

Doc prev / next nav improvements

---

src/pages/docs/running-collections/using-newman-cli/integration-with-travis.md

- Edited and rewrote all text
- Updated tutorial example and verified all steps

[TW-318] Refresh "Integrating with Travis CI" page

---

src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md

* Removed antique screenshots
* Restructured this to use an existing collection
* Made procedural
* Removed unneeded steps of testing the collection locally
* General rewrites

TW-119 Jenkins integration page refresh

---

src/pages/docs/getting-started/introduction.md
src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
src/pages/docs/sending-requests/capturing-request-data/capturing-https-traffic.md
src/pages/docs/sending-requests/capturing-request-data/interceptor.md

- Updates `Capture Requests` to `Capture requests and cookies`

CLNTINT-450 Capture requests and cookies

---

src/components/Header/Header.jsx
src/components/Header/Header.scss

- Adds chevron icon w/ transition when user clicks on mobile navigation menu
- Inline with Blog and WWW updates
- Removed commented out code / general clean up 
- Updated code in header.jsx and header.scss to match figma Ticket - [MARKENG-1170] 
[MARKENG-1170]: https://postmanlabs.atlassian.net/browse/MARKENG-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MARKENG-1174] Stacked mobile navigation updates

---

README.md
src/pages/docs/administration/onboarding-checklist.md
src/pages/docs/getting-started/installation-and-updates.md

* added link to Postman Agent on README
* updated existing links to point to new page instead of /downloads/ page

updated and added links to the new Postman Agent page

---

src/pages/docs/integrations/available-integrations/datadog.md

- Updates Datadog API key location
- Removes old name from the metrics table
- General copyedits & removal of unnecessary screenshots

TW 324 update Datadog integration page

---

src/pages/docs/administration/managing-your-team/configuring-domain-capture.md

Domain capture page additions based on support checklist doc. Formatting is based on existing styling in other docs with some adjustments for lists.

[TW-325] Domain capture updates

---

package-lock.json
package.json
src/components/Header/Dropdown.jsx
src/components/Header/Header.jsx

broke out dropdown from header into Dropdown component and implemented clickout with hooks instead of third party package

markeng-202

---

src/pages/docs/sending-requests/capturing-request-data/interceptor.md

- Updates https://learning.postman.com/docs/sending-requests/capturing-request-data/interceptor/ to include new screenshots and workflows for syncing and capturing cookies

TW 326 Update interceptor page with cookie sync and cookie capture workflows

---

src/pages/docs/sending-requests/responses.md

- Rewrites and reorganizes content
- Updates screenshots
- Adds table of contents

TW 260 Refresh /sending-requests/responses/

---

src/pages/docs/collaborating-in-postman/roles-and-permissions.md

- Adds information about role-based permissions for monitors and mock servers
- General rewriting, rearranging, and editing

TW 42 Update /collaborating-in-postman/roles-and-permissions/

---

src/components/layout.jsx
src/components/modules/PreviousAndNextLinks.jsx
src/components/modules/handlePagination.jsx
src/templates/doc.jsx

This PR adds the ability to navigate between Docs using the <- and -> arrow keys on web and left or right swipe on mobile.
- Added handlePagination.jsx component that contains handleKeyboard() and handleSwipe() functions
- Updated PreviousAndNextLinks.jsx to use the handlePagination component
- Navigating between links are locked to section the user is in until we explore full pagination
- Linted code to keep files clean
- Broke out DisplayContextualLinks to functional component in Doc.jsx

[MARKENG-1172] Added Arrow key and Swipe functionality to Docs

---

src/pages/docs/getting-started/importing-and-exporting-data.md

- Adds information about the possible statuses for data dump requests
@VaishnaviChallaPostman can you please take a quick look to make sure I've interpreted your Slack message correctly?

TW 331 Add status information for data dumps

---

src/pages/docs/sending-requests/intro-to-collections.md

- Reorganized and rewrote content

TW 317 Refresh /sending-requests/intro-to-collections/

---

src/pages/docs/api-security/security-warnings/openapi2.md
src/pages/docs/api-security/security-warnings/openapi3.md
src/pages/docs/collaborating-in-postman/version-control-for-collections.md

- Reorganizes the OpenAPI 2.0 & 3.0 security warnings to conform to the new Category-Vulnerability-Rule (CVR) framework.

TW 307 Reorganize OpenAPI 2.0 & 3.0 security warnings

---

src/pages/docs/collaborating-in-postman/roles-and-permissions.md
src/pages/docs/sending-requests/managing-environments.md
src/pages/docs/sending-requests/variables.md

**Managing environments**
* fix screenshots
* add more info about secret variables
* minimum necessary edits in spots I was editing for secret vars, full rewrite needed (created TW-335)
**Using variables**
* fix screenshots
**Defining roles**
* add environment section (this isn't in the webdash so kept extremely simple, reaching out to see if it can be added)

[TW-305] Secret vars update

---

src/pages/docs/integrations/available-integrations/apimatic.md

* Updates screenshots
* Adds prerequisites 
* Formats instructions as a numbered list

TW 264 Refresh APIMatic page

---

redirects.json
src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/administration/onboarding-checklist.md
src/pages/docs/getting-started/installation-and-updates.md
src/pages/docs/getting-started/proxy.md
src/pages/docs/getting-started/settings.md
src/pages/docs/sending-requests/capturing-request-data/capture-overview.md

Also some light touchup while I was in there.

TW-306 Move custom proxy page

---

.gitignore
_vale.ini
scripts/pm-get-vale-styles

See TW-365 for details and scope

TW-365 Vale setup

---

src/pages/docs/administration/billing.md

Waiting on one other screenshot for auto-flex

[TW-379] Resource usage page updates

---

src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md

I can delete My WorkSpace and Team WorkSpace from my postman environment.
Using postman --version: 9.13.2

Deleting My WorkSpaces and Team Workspace is poddible.

---

src/pages/docs/getting-started/syncing.md

- Updates content to tighten the scope of the page
- Updates format to aid readability

TW 255 Refresh /getting-started/syncing/

---

src/pages/docs/collaborating-in-postman/requesting-access-to-collections.md

- Added details for requesting access to environments and mock servers
- Consolidated steps into a single common procedure rather than separate procedures for each element type

[TW-101] Refresh Requesting access page

---

src/pages/docs/writing-scripts/script-references/variables-list.md

https://www.infoworld.com/article/3647750/faker-npm-package-back-on-track-after-malicious-coding-incident.html
Editor at Large, InfoWorld \| Jan 19, 2022 11:47 am PST
In the wake of a recent incident that wreaked havoc on the NPM package registry, a new group of maintainers is reestablishing the Faker project, making it a community effort. The previous maintainer had sabotaged the Faker NPM package with malicious code, impacting more than 2,500 other NPM packages that depend on it.
The Faker JavaScript library generates mock data for testing and development. A group of engineers has created a [GitHub repo](https://github.com/faker-js/faker) for the new Faker package and released previous versions at `@faker-js/faker` on [NPM](https://www.npmjs.com/package/@faker-js/faker).
On January 4, …

Update link to faker

---

src/pages/docs/getting-started/navigating-postman.md

Adds Oxford commas, addresses consistency nits, and revised copy in the Getting Started docs.

Navigating Postman Edits

---

src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md
src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
src/pages/docs/publishing-your-api/run-in-postman/run-button-API.md

- TW-373
- TW-374
- TW-376
- Minor rewording in areas that were affected by above
- Resolves vale errors for folder
- Updates screenshot

RiP button updates

---

src/pages/docs/administration/audit-logs.md

Updated + alphabetized audit logs

[TW-383] Audit logs update

---

src/pages/docs/collaborating-in-postman/collaboration-intro.md
src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
src/pages/docs/getting-started/creating-the-first-collection.md
src/pages/docs/integrations/available-integrations/bigpanda.md
src/pages/docs/integrations/available-integrations/coralogix.md
src/pages/docs/integrations/available-integrations/opsgenie.md
src/pages/docs/integrations/available-integrations/pagerduty.md
src/pages/docs/integrations/available-integrations/slack.md
src/pages/docs/integrations/available-integrations/splunk.md
src/pages/docs/monitoring-your-api/uptime-monitors.md

[TW-384][TW-388][TW-396] Sidebar devrel content additions

---

src/pages/docs/getting-started/creating-the-first-collection.md
src/pages/docs/getting-started/creating-your-first-workspace.md
src/pages/docs/getting-started/exploring-public-api-network.md
src/pages/docs/getting-started/importing-and-exporting-data.md
src/pages/docs/getting-started/installation-and-updates.md
src/pages/docs/getting-started/introduction.md
src/pages/docs/getting-started/postman-account.md
src/pages/docs/getting-started/proxy.md
src/pages/docs/getting-started/sending-the-first-request.md
src/pages/docs/getting-started/settings.md
src/pages/docs/getting-started/syncing.md
src/pages/docs/getting-started/troubleshooting-inapp.md
src/pages/docs/getting-started/using-scratch-pad.md
src/pages/docs/sending-requests/variables.md
vale-styles/Vocab/LC/accept.txt

Working on files in the `/getting-started/` folder:
Before: `✖ 55 errors, 189 warnings and 370 suggestions in 14 files.`
After: `✖ 13 errors, 132 warnings and 307 suggestions in 14 files.`

Vale errors and suggestions

---

src/pages/docs/administration/sso/saml-in-azure-ad.md

Screenshot of the updated page: ![screencapture-localhost-8000-docs-administration-sso-saml-in-azure-ad-2022-03-14-09_44_13](https://user-images.githubusercontent.com/21180383/158220017-ca1ddf69-6cee-4fea-9c65-b9e1e14bfaf1.png)

[TW-355] Azure AD SSO docs update

---

src/pages/docs/publishing-your-api/run-in-postman/run-button-API.md

- Adds a new section for removing an existing environment
- Adds a new section for Getting all environments
- Wording edits based on running Vale

TW 405 Update Coding with Run in Postman

---

src/pages/docs/sending-requests/capturing-request-data/interceptor.md
src/pages/docs/sending-requests/capturing-request-data/syncing-cookies.md

Updated two Interceptor screenshots (there were minor changes from beta to prod I didn't catch)

Fix Interceptor screenshots

---

src/pages/docs/administration/billing.md
vale-styles/Vocab/LC/accept.txt

- Updates the screenshot for https://learning.postman.com/docs/administration/billing/#adding-custom-information-to-invoices
- Content updates based on Vale suggestions*
Thank you @cyrielle-hada for letting us know about this update! 🎉 
* There are some lingering Vale issues that I didn't clear up in this PR because they required some significant rewriting and are probably better suited to a whole-page refresh 😅

TW 412 Update billing information screenshot and run Vale

---

src/components/seo.jsx

Updating One Trust ID due to new version

Update One Trust ID for Learning Center

---

src/pages/docs/collaborating-in-postman/using-workspaces/public-workspaces.md
src/pages/docs/getting-started/settings.md
src/pages/docs/publishing-your-api/viewing-documentation.md

Fixed remaining icon images without #icon tags

Fix icon tags

---

src/pages/docs/collaborating-in-postman/adding-private-network.md
src/pages/docs/publishing-your-api/run-in-postman/run-button-API.md

Edits requested by @VaishnaviChallaPostman

TW-372 and TW-375

---

DOCS_STYLE_GUIDE.md

These were all minor typos or Vale fixes found when reconciling this with the internal guide.
This will never pass Vale, because it has examples of wrong text, and Vale doesn't like emojis.

TW-398 Update DOCS_STYLE_GUIDE.md

---

src/pages/docs/getting-started/navigating-postman.md

- New header image
- Reorder content to be broken up by region of the app
- Cut the number of screenshots, refresh remaining screenshots as needed

Tw 256 Refresh /getting-started/navigating-postman/

---

src/pages/docs/integrations/available-integrations/new-relic.md

TW 449 Update New Relic link to include referrer

---

src/pages/docs/api-security/token-scanner.md
src/pages/docs/designing-and-developing-your-api/managing-apis.md

Ty @tristandenyer for catching these!

TW 448 Links missing trailing slashes

---

src/pages/docs/collaborating-in-postman/version-control.md

I think there's a "to" missing here. ;-)

Add "to" in "Creating a fork"

---

src/pages/docs/running-collections/intro-to-collection-runs.md

- Numbered procedures
- General edits + ran Vale

TW 464 Collection Runner refresh

---

src/pages/docs/administration/audit-logs.md

- Updated content about audit logs
- Ran Vale (I can't resolve many of the suggestions about passive text because they are part of text in the UI)
I still need a screenshot of these updates and will work with Ronak to get one. 🤝

TW 435 Audit logs page

---

src/pages/docs/administration/scim-provisioning/configuring-scim-with-azure-ad.md
src/pages/docs/collaborating-in-postman/version-control.md
src/pages/docs/designing-and-developing-your-api/creating-an-api.md
src/pages/docs/designing-and-developing-your-api/defining-an-api.md
src/pages/docs/getting-started/creating-the-first-collection.md
src/pages/docs/integrations/available-integrations/working-with-openAPI.md
src/pages/docs/sending-requests/capturing-request-data/capturing-http-requests.md
src/pages/docs/sending-requests/intro-to-collections.md
src/pages/docs/sending-requests/visualizer.md
src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md

Covers:
- TW-434
- TW-452
- TW-466
- TW-470

[TW-434, TW-452, TW-466, TW-470] Another batch of devrel content for the sidebar

---

src/pages/index.jsx

* updated copy
* updated CTA label
* updated link

[MARKENG-1425] updated "Postman support" copy and CTA and link in card at bottom

---

src/pages/docs/collaborating-in-postman/version-control.md

Also ran Vale and made recommended changes.

TW 486 Add flows to forking docs

---

src/pages/docs/administration/sso/microsoft-adfs.md

Afaik the actual instructions haven't changed here, so this was just to update formatting (it was kind of all over the place). I also ran Vale.

TW 450 Refresh formatting for Microsoft AD FS SSO page

---

src/pages/docs/collaborating-in-postman/using-workspaces/conflicts.md
src/pages/docs/collaborating-in-postman/using-workspaces/public-workspaces.md
src/pages/docs/designing-and-developing-your-api/deploying-an-api/deploying-an-api-overview.md
src/pages/docs/developer/intro-api.md
src/pages/docs/integrations/available-integrations/ci-integrations/circleci.md
src/pages/docs/integrations/available-integrations/ci-integrations/jenkins.md
src/pages/docs/reports/all-apis-reports.md
src/pages/docs/reports/all-workspaces-reports.md
src/pages/docs/reports/reports-overview.md
src/pages/docs/reports/security-audit-reports.md
src/pages/docs/reports/summary-reports.md
src/pages/docs/reports/team-details-reports.md
src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md

- adds new content to sidebar
- fixes some subtitles in sidebar that reappeared

[TW-478][TW-490] Add content to sidebar

---

gatsby-node.js

display console error if frontmatter length exceeds 9999 bytes on build

Query frontmattter md char length

---

redirects.json
src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/designing-and-developing-your-api/deploying-an-api/deploying-an-api-aws.md
src/pages/docs/designing-and-developing-your-api/managing-apis.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/api-releases.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/api-statuses.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/api-versions.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/using-external-git-repo.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/versioning-an-api-overview.md
src/pages/docs/publishing-your-api/documenting-your-api.md

Split only, no content changes.

TW-457 Split versioning an API doc

---

src/pages/docs/writing-scripts/intro-to-scripts.md

Following the format of the preceding lines.

Missing word in intro-to-scripts.md

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/getting-started/settings.md
src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md
src/pages/docs/running-collections/using-newman-cli/continuous-integration.md
src/pages/docs/running-collections/using-newman-cli/installing-running-newman.md
src/pages/docs/running-collections/using-newman-cli/newman-custom-reporters.md
src/pages/docs/running-collections/using-newman-cli/newman-file-uploads.md
src/pages/docs/running-collections/using-newman-cli/newman-options.md

This is mostly a page split, but I also found missing flags in the options section, and did some other really quick cleanup.

TW-500 Newman page IA

---

src/pages/docs/getting-started/settings.md
src/pages/docs/getting-started/troubleshooting-inapp.md

These changes to the [app settings page](https://learning.postman.com/docs/getting-started/settings/) were originally part of https://github.com/postmanlabs/postman-docs/pull/4065, but since that's on hold I wanted to move forward with them now:
- Fixes list formatting (now sure how I missed this earlier! 🙈)
- Moves the hardware acceleration section to the [app troubleshooting guide](https://learning.postman.com/docs/getting-started/troubleshooting-inapp/)

Fix list formatting in Settings page

---

src/pages/docs/getting-started/proxy.md

These changes to the [proxy page](https://learning.postman.com/docs/getting-started/proxy/) were originally part of https://github.com/postmanlabs/postman-docs/pull/4065, but since that's on hold I wanted to move forward with them now!

Fix formatting for proxy page

---

src/pages/docs/getting-started/using-scratch-pad.md

The changes to this file in https://github.com/postmanlabs/postman-docs/pull/4063 haven't made it to Prod yet, so reverting for now.

Revert changes to using-scratch-pad.md

---

package-lock.json

- ran `npx browserslist@latest --update-db`
- this updates package-lock file with latest browsers support list for `caniuse-lite`

ran npx browserslist@latest --update-db to update browsers support list

---

src/pages/docs/designing-and-developing-your-api/creating-an-api.md

TW-550 Edit src/pages/docs/designing-and-developing-your-api/creating-an-api.md

---

src/pages/docs/sending-requests/managing-environments.md

Changed "it is" to "it's" in line 258.

[TW-551] Fixed a contraction error in the managing-environments.md file.

---

src/pages/docs/sending-requests/capturing-request-data/interceptor.md

[TW-549] Changed 'enables you to' to 'lets you'
[TW-549]: https://postmanlabs.atlassian.net/browse/TW-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Changed one word for training purposes

---

src/pages/docs/monitoring-your-api/faqs-monitors.md
src/pages/docs/monitoring-your-api/setting-up-monitor.md
src/pages/docs/monitoring-your-api/viewing-monitor-results.md

- Change default monitor timeout for paid plans to 15 minutes
- Fix vale errors

[TW-565] Doc new monitor timeout for paid plans

---

.github/workflows/deploy.yml

Updates beta's deploy script to point to new s3 bucket, which is created / maintained in cdk.

Update beta deploy script to point to new s3, created by cdk

---

src/pages/docs/sending-requests/visualizer.md

Add note to "Adding styling and interaction to visualizations" section of the "Visualizing responses" topic.

[TW-568] Add a note to the visualizer topic about interactions

---

src/pages/docs/monitoring-your-api/intro-monitors.md

* on /docs/monitoring-your-api/intro-monitors/, added new blog post tutorial for using Notion and Postman monitor

added blog post to /docs/monitoring-your-api/intro-monitors/ doc right side

---

.github/workflows/beta-deploy.yml

Update `beta` pipeline to point to new infra, as well as refactor out the `s3-deploy` package

[MARKENG-1600] Update beta pipeline to deploy to new infra

---

src/pages/docs/developer/collection-conversion.md
src/pages/docs/developer/collection-sdk.md
src/pages/docs/developer/resources-intro.md
src/pages/docs/developer/runtime-library.md
src/pages/docs/writing-scripts/pre-request-scripts.md

I reviewed and updated multiple topics to verify that content is current and in alignment with the style guide. Updates included fixing Vale suggestions, updating a screenshot, checking links, testing procedures, updating the updated date, and re-organizing content where needed.

[TW-584] Refreshed multiple topics

---

src/pages/docs/collaborating-in-postman/adding-private-network.md
src/pages/docs/collaborating-in-postman/version-control.md
src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
src/pages/docs/developer/collection-conversion.md
src/pages/docs/getting-started/creating-the-first-collection.md
src/pages/docs/integrations/available-integrations/github.md
src/pages/docs/integrations/available-integrations/slack.md
src/pages/docs/integrations/webhooks.md
src/pages/docs/monitoring-your-api/intro-monitors.md
src/pages/docs/publishing-your-api/documenting-your-api.md
src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
src/pages/docs/running-collections/intro-to-collection-runs.md
src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md
src/pages/docs/running-collections/working-with-data-files.md
src/pages/docs/sending-requests/authorization.md
src/pages/docs/sending-requests/capturing-request-data/interceptor.md
src/pages/docs/sending-requests/generate-code-snippets.md
src/pages/docs/sending-requests/managing-environments.md
src/pages/docs/sending-requests/variables.md
src/pages/docs/writing-scripts/intro-to-scripts.md
src/pages/docs/writing-scripts/pre-request-scripts.md
src/pages/docs/writing-scripts/script-references/test-examples.md
src/pages/docs/writing-scripts/test-scripts.md

(does not include one requested for flows @jkonrath-postman)

TW-589 Add case studies

---

src/components/Footer/Footer.scss
src/components/Shared/_variables.scss

* updated variables
* converted px to use closest variable
* matches www site

updating border-radius to support 10px grid

---

src/components/Header/Header.jsx
src/components/Header/HeaderStyles.jsx

- updated header component with styled components. 
- deleted scss file 
- created styles.jsx file as it is a long file

[markeng-1509-header] update header component with styled components

---

src/pages/docs/administration/billing.md
src/pages/docs/administration/buying.md

The billing team has launched some payment updates. We've kept the [billing page](https://learning.postman.com/docs/administration/billing/) largely abstracted, so these changes don't require us to make any specific updates. However, I took this opportunity to update two instances of H5s to H4s (our build system doesn't format H5s very nicely), as well as make a few other updates.

Updates to billing page

---

gatsby-config.js
src/pages/search.jsx

add dots and remove /search page from sitemap

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/designing-and-developing-your-api/defining-an-api.md
src/pages/docs/designing-and-developing-your-api/developing-an-api.md
src/pages/docs/designing-and-developing-your-api/generating-server-code.md
src/pages/docs/designing-and-developing-your-api/managing-apis.md
src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
src/pages/docs/designing-and-developing-your-api/observing-an-api/observing-an-api.md
src/pages/docs/designing-and-developing-your-api/testing-an-api.md
src/pages/docs/designing-and-developing-your-api/the-api-workflow.md
src/pages/docs/designing-and-developing-your-api/validating-elements-against-schema.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/api-releases.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/api-statuses.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/using-external-git-repo.md
src/pages/docs/integrations/available-integrations/gitlab.md
src/pages/docs/integrations/available-integrations/statuspage.md
src/pages/docs/sending-requests/graphql/graphql.md
src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md

I fixed typos and formatting issues multiple topics. I fixed one issue in the left nav.

[TW-627] Various typos and formatting fixes

---

src/components/modules/PreviousAndNextLinks.jsx

* updated the pagination to use latest link Arrow styling

updated pagination to use latest linkArrow styling

---

src/pages/docs/collaborating-in-postman/version-control.md

TW-640 minor VC fix

---

package-lock.json

Updated browserslist-db to 1.0.30001382

---

src/components/Header/Header.jsx

fixed a file name casing issue with SearchPreview and SearchStyles

Markeng 1509

---

src/components/Footer/Footer.data.json

Add Partner Program link to footer

---

src/components/Header/Dropdown.jsx
src/components/Header/Header.jsx

WARN is displaying when running `npm run dev` and is breaking merges into BETA.

Fix naming convention in searchStyles and searchPreview to fix Beta build

---

src/components/Header/HeaderStyles.jsx
styles/globalStyle.js

changed the bg color to white so page doesn't display under sticky nav
- MARKENG-1742 modal close btn border radius to new px grid

[MARKENG-1635B] update 2nd nav bg color 

---

package-lock.json
package.json

* discovered that react-tabs package is not being used
* removed form package.json
* regenerated package-lock.json
* no changes to build or UI

removed unused react-tabs package; regen'd package-lock

---

src/components/Header/Header.jsx
src/pages/docs/integrations/available-integrations/new-relic.md

* added Guide to API-First link in top nav
* deleted Postman Galaxy and Webinars from top nav

Dev --> Prod for topnav changes

---

src/pages/docs/api-governance/api-definition/api-definition-warnings.md
src/pages/docs/api-governance/api-testing/api-testing-warnings.md

cc @petewitcher for potential collaboration!

TW 545 API Governance and API Security linting with the Postman CLI

---

src/pages/docs/api-governance/api-definition/api-definition-warnings.md
src/pages/docs/api-governance/api-definition/openapi2.md
src/pages/docs/api-governance/api-definition/openapi3.md

This PR updates wording for selected OpenAPI 2.0 and 3.0 linting rules, based on reviews from the Open Tech team.

TW 639 Update linting wording

---

src/components/Header/Header.jsx

update nav to State of API report for consistency

[MARKENG-1796]update nav with State of API report

---

package-lock.json
package.json
src/components/modules/Modal.js
src/templates/doc.jsx

This update clears the [object object] text display on initial page load. There was an issue where the function was rendering an object within an object due to dangerouselySetInnerHTML. 
Full width images will still display a modal on click.
Tested on 4G/LTE speed, Cable 8mbps and throttled slow networks.
To test: Run build locally and go to http://localhost:9000/docs/getting-started/postman-account/
In Developer tools: Change network speed to "Fast3G" or "Slow3G" (Defaults from Google Chrome)
_Also updates aether-marketing to  version 1.11.0 (latest)_

[MARKENG-1550] Addressed [object object] loading issue

---

src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md
src/pages/docs/designing-and-developing-your-api/mocking-data/mocking-with-examples.md
src/pages/docs/getting-started/introduction.md
src/pages/docs/getting-started/navigating-postman.md
src/pages/docs/sending-requests/examples.md
src/pages/docs/sending-requests/requests.md
src/pages/docs/sending-requests/responses.md

I did a sweep of images that show a request response and that are missing the Security tab. 🧹

TW 648 post-v10 Security tab screenshot cleanup

---

.github/workflows/beta-deploy.yml
.github/workflows/ci.yml
.github/workflows/manual-rerun.yml
.github/workflows/prod-deploy.yml
bff.js
build/fetchPmTech.js

_Branched from `develop`_, this updates bff build scripts to use PM_TECH_RT.
Doing so makes it so we avoid potential API rate limiting.
_*no-visuals_

[MARKENG-1831][c] update bff build scripts to use PM_TECH_RT to avoid potential rate limiting

---

src/pages/docs/integrations/available-integrations/pagerduty.md

This PR:
- Removes PagerDuty UI screenshots (futureproofing against UI changes that don't belong to us)
- Updates Postman screenshots
- Updates instructions and formats them as numbered lists

TW 414 Refresh PagerDuty integration page

---

src/pages/docs/integrations/available-integrations/pagerduty.md

Ref https://github.com/postmanlabs/postman-docs/pull/4315#discussion_r988342401 🤦

Update frontmatter in pagerduty.md

---

src/pages/docs/administration/team-merge.md
src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md

**Note**: You can ignore the Migration FAQs section after the first question, I just had to indent all of the answers to get the bullet list in the first question to indent correctly

TW-665 Updates to multi-team

---

src/pages/docs/administration/updating.md
src/pages/docs/api-governance/api-definition/api-definition-warnings.md
src/pages/docs/api-governance/api-governance-overview.md
src/pages/docs/api-governance/api-testing/security-warnings.md
src/pages/docs/api-governance/configurable-rules/configuring-api-security-rules.md
src/pages/docs/collaborating-in-postman/adding-private-network.md
src/pages/docs/collaborating-in-postman/using-workspaces/partner-workspaces.md
src/pages/docs/collaborating-in-postman/working-with-your-team/collaborating-in-team-workspaces.md
src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md
src/pages/docs/designing-and-developing-your-api/creating-an-api.md
src/pages/docs/designing-and-developing-your-api/deploying-an-api/deploying-an-api-overview.md
src/pages/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements.md
src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
src/pages/docs/designing-and-developing-your-api/developing-an-api/validating-elements-against-schema.md
src/pages/docs/designing-and-developing-your-api/testing-an-api.md
src/pages/docs/designing-and-developing-your-api/versioning-an-api/using-external-git-repo.md
src/pages/docs/getting-started/exploring-public-api-network.md
src/pages/docs/getting-started/installation-and-updates.md
src/pages/docs/getting-started/introduction.md
src/pages/docs/integrations/available-integrations/new-relic.md
src/pages/docs/integrations/available-integrations/working-with-openAPI.md
src/pages/docs/monitoring-your-api/intro-monitors.md
src/pages/docs/postman-cli/postman-cli-overview.md
src/pages/docs/publishing-your-api/authoring-your-documentation.md
src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md
src/pages/docs/sending-requests/grpc/first-grpc-request.md
src/pages/docs/sending-requests/grpc/grpc-client-overview.md
src/pages/docs/sending-requests/grpc/test-examples.md

**Note**: Also renames "Space Camp" to "Intergalactic" in accordance with devrel plan

[TW-664 TW-675 TW-687 TW-709] Sidebar content additions

---

src/components/Header/Header.jsx
src/pages/docs/collaborating-in-postman/working-with-your-team/collaborating-in-team-workspaces.md
src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md
src/pages/docs/designing-and-developing-your-api/creating-an-api.md
src/pages/docs/designing-and-developing-your-api/deploying-an-api/deploying-an-api-overview.md
src/pages/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements.md
src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md
src/pages/docs/designing-and-developing-your-api/developing-an-api/validating-elements-against-schema.md
src/pages/docs/designing-and-developing-your-api/testing-an-api.md
src/pages/docs/getting-started/introduction.md
src/pages/docs/integrations/available-integrations/new-relic.md
src/pages/docs/integrations/available-integrations/working-with-openAPI.md
src/pages/docs/monitoring-your-api/intro-monitors.md
src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md
src/pages/index.jsx

[MARKENG-1864] [c] Update Postman Space Camp to Postman Intergalactic for Joyce

---

src/pages/docs/designing-and-developing-your-api/developing-an-api/adding-api-elements.md
src/pages/docs/designing-and-developing-your-api/managing-apis.md
src/pages/docs/designing-and-developing-your-api/testing-an-api.md
src/pages/docs/designing-and-developing-your-api/the-api-workflow.md

- Update "Adding API tests" section
- Add "Running API tests" section
- Correct last updated dates on a few pages

[TW-713] Doc adding API tests

---

src/pages/docs/developer/intro-api.md

* Updated the "Generating a Postman API Key" section's instructions and screenshots.
* Checked links to ensure they work as expected. Updated the external product link in the last section on the page because the page title and URL were outdated.
* Checked for Vale suggestions.
* Updated the last updated date.

[TW-724] Refreshed intro-api.md file

---

src/pages/docs/sending-requests/cookies.md

Make this clarification for calling `.clear()` and then `.set()` in sequence.

[TW-721] Clarify that cookie functions execute asynchronously

---

src/pages/docs/integrations/available-integrations/bigpanda.md

* Checked for Vale suggestions
* Fixed typos
* Added "Contents" section
* Reduced number of screenshots
* Updated instructions to match previously refreshed integration pages
* Updated last updated date

[TW-727] Refresh BigPanda integration

---

src/pages/docs/sending-requests/capturing-request-data/capturing-https-traffic.md

Screenshot conflicted with the written instructions in the step. Updated the screenshot to match the written instructions.

[TW-658] Updated Postman Proxy screenshot

---

src/pages/docs/sending-requests/grpc/postman-sandbox-api.md

Added details about the new pm.sendRequest API that is now available in gRPC request scripts.

Update gRPC docs to include `pm.sendRequest` API

---

gatsby-browser.js
package-lock.json
package.json
src/components/Header/Header.jsx
src/components/Header/HeaderStyles.jsx
src/components/LeftNav/LeftNav.jsx
src/components/layout.jsx
src/templates/doc.jsx
styles/globalStyle.js
styles/styles.scss
styles/theme.jsx

Added Sass Map
Added base 10 in globalstyles
Adjusted NavBar and dropdown menu items to equal styling in www.
Adjusted left nav to new base 10

added Sass Map, base 10 and adjusted styling

---

src/pages/docs/postman-cli/postman-cli-run-collection.md

Added info and edited the first paragraph of `Running a collection`.

[TW-749] pcli local

---

src/templates/doc.jsx
styles/globalStyle.js

Please check the table on the first page

 [markeng-1953] Fix font size in table

---

src/pages/docs/api-governance/api-governance-overview.md

This PR updates the introduction for the API Governance section at https://learning.postman.com/docs/api-governance/api-governance-overview/.

TW 743 Improve governance and security introduction

---

src/pages/docs/getting-started/postman-profile.md

Update link to point to the new video that deprecates the old video

Add contextual link to updated Level Up

---

.github/workflows/beta-deploy.yml
.github/workflows/prod-deploy.yml
bff.js
build/fetchNavbar.js
build/navbarDev.json
src/components/Header/Header.jsx

- Primary Navbar now pulls in data from the API in production env, and from the dummy data file in the repo in development env - for testing
- Header has been refractored from Class Component to functional component using React Hooks

[markeng-1950]  refractor Header

---

src/pages/docs/administration/scim-provisioning/configuring-scim-with-azure-ad.md

This PR updates the attribute mapping sections for Azure AD. Screenshot of the updated content:
@johnoffenhartzPM @phonomenal @PriyambadaMadala Please take a look and let me know whether this covers everything that customers need to know to set up the mappings successfully!

TW 800 Azure AD SCIM attribute mapping types

---

src/pages/docs/integrations/available-integrations/azure-devops.md
src/pages/docs/integrations/available-integrations/bitbucket.md
src/pages/docs/integrations/available-integrations/gitlab.md

Updated the API Sync section for Azure DevOps, BitBucket, and GitLab integrations (GitHub was already updated)

[TW-409] Emphasize API sync for SCM integrations

---

src/pages/docs/postman-flows/core-concepts/blocks-list.md
src/pages/docs/postman-flows/flows-query-language/conditional-data-selection.md
src/pages/docs/postman-flows/flows-query-language/data-manipulation.md
src/pages/docs/postman-flows/flows-query-language/getting-basic-values.md

In this PR: 
1) Added a bunch of new FQL examples based on user experiences and documentation
2) Fixed some incorrect wording on the block list

TW-803 FQL updates and examples

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/administration/billing.md
src/pages/docs/administration/resource-usage.md
src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md
src/pages/docs/developer/intro-api.md
src/pages/docs/getting-started/about-postman-agent.md
src/pages/docs/getting-started/navigating-postman.md
src/pages/docs/monitoring-your-api/monitor-usage.md
src/pages/docs/publishing-your-api/authoring-your-documentation.md
src/pages/docs/reports/summary-reports.md
src/pages/docs/reports/team-details-reports.md

- Added new "About resource usage" page under "Administration"
- Add links to "About resource usage" page on other pages that mention resource usage
- Removed references to serverless usage

[TW-790] Add  topic on what happens when resource limits are reached

---

src/pages/docs/postman-flows/flows-query-language/data-manipulation.md

https://github.com/postmanlabs/postman-docs/pull/4479/files

[quick-fix] Add missing env vars (algolia) back to prod pipeline

---

src/pages/docs/administration/team-merge.md

I believe it was wrongly written, edited from Distributed to centralized

Distributed to centralized

---

build/navbarDev.json
src/components/Header/Header.jsx

- add comments to clarify that topnavbarDataLocal file is only for local development.
- refactored Top Navbar to pull in API data in production and development environment (can be changed for testing)

refactor topnavbar

---

src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md

This PR updates https://learning.postman.com/docs/collaborating-in-postman/working-with-your-team/collaboration-overview/#creating-a-team to account for the limited roll-out of multi-team.

TW 830 Update the "create team" section

---

package-lock.json
package.json

removed as many vulnerabilities as possible

Vulnerability fix 2

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/postman-flows/flows-intro/using-response-data-in-a-request.md

This is a new tutorial for Postman Flows that shows how to take response data from one GET request and include it in a subsequent GET request.

[TW-808] flows - send info

---

src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md

@Raj-postman I revisited your comment in https://github.com/postmanlabs/postman-docs/pull/4500#issuecomment-1376738994 and realized that https://learning.postman.com/docs/collaborating-in-postman/working-with-your-team/collaboration-overview/#creating-a-team already has the information you were requesting! 😁 This PR adds a short clarifying sentence to bring it more in line with your suggestion.

TW 846 Add additional info to "create team" section

---

src/pages/docs/publishing-your-api/custom-doc-domains.md

Removed beta reference from two screenshots

[TW-893] Fix custom domain screenshots

---

src/templates/doc.jsx

[markeng-2161] update list style

---

src/pages/docs/sending-requests/variables.md

Add information about the Add button when no variables have been added yet

Add information about the Add button

---

build/navbarDev.json
src/components/Header/Header.jsx

This adds the Solutions column under the "Enterprise" dropdown to the global navbar.

[MARKENG-2022] Update global navbar with Solutions column

---

src/pages/docs/sending-requests/managing-environments.md
src/pages/docs/sending-requests/variables.md

- A few screenshot swaps to show the filter control
- A few mentions of the filter control on /sending-requests/managing-environments.md
- General cleanup

TW-928 doc environment variable filtering

---

src/pages/docs/collaborating-in-postman/roles-and-permissions.md
src/pages/docs/designing-and-developing-your-api/managing-apis.md

- Updated "Commenting on APIs" section
- Added resolving comments
- Added commenting on Git-linked APIs

[TW-925] Doc annotations support in API builder

---

src/components/Footer/Footer.jsx
src/components/Header/Header.jsx

This update will check if the keys returned from the bff match the expected values and act as a safeguard if the data comes back malformed.
If true, the production data will be set and fallback to the local version if false.

[MARKENG-2235] Add runtime check test for Navbar and Footer API

---

src/components/Shared/EditDoc.jsx

update "Edit this Doc" button to be Sentence case

---

src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md

Re-word if required but letting users know about this might solve confusion with the word "Personal"

Personal workspace in team context

---

package-lock.json

* ran `npx browserslist@latest --update-db` to update 
* gen'd new package-lock
* no changes to front-end

updated caniuse-lite db to latest

---

redirects.json

* manually ran about 80 of the `from` URLs, let resolve, and updated the redirects where applicable to reduce the multi-redirect situations
* this is for the app-level redirects

update (some) of the redirects.json

---

package-lock.json
redirects.json
src/templates/doc.jsx

added anchor link styling #4566
TW-979 Remove redirect #4614

Dev -> Prod

---

src/pages/docs/sending-requests/responses.md

Reverts postmanlabs/postman-docs#4626

Revert "[TW-986] http clear response"

---

src/pages/docs/api-governance/configurable-rules/configurable-rules-overview.md
src/pages/docs/api-governance/configurable-rules/configuring-api-governance-rules.md
src/pages/docs/api-governance/configurable-rules/configuring-api-security-rules.md
src/pages/docs/collaborating-in-postman/roles-and-permissions.md

Draft docs for:
* Ability to import additional libraries
* Switch security warnings count on or off

Governance TW-905 TW-910

---

src/pages/docs/sending-requests/responses.md

This is the new feature content. It is an un-revert of a merge that went too early and was reverted.
This reverts commit c343e293415b82cec15d0b4eaced16c6c259743f, reversing changes made to 0921b326295fedcebcdf6aa84612523112843b82.

TW-986 HTTP clear response

---

src/pages/docs/collaborating-in-postman/using-workspaces/partner-workspaces.md

Clarified instructions explaining how to invite people to a Partner Workspace.

[TW-1026] Inviting people to partner workspaces

---

build/footerDev.json
build/navtopicsdropdownDev.json
src/components/Footer/__snapshots__/Footer.spec.jsx.snap

updated 2nd Nav Dropdown with Blog link
updated footer with App Security link

Markeng-2382 NavDropdown & Markeng-2388 footer updates

---

src/components/Header/HeaderStyles.jsx

This fixes the spacing when the search menu is toggled

Update mobile spacing for search dropdown menu

---

redirects.json

added redirects as advised from SEO team

added redirects from SEO recommendations

---

src/pages/docs/administration/sso/intro-sso.md

Updated note about setting email address during IdP configuration.

[TW-1053] Update note on setting email address during config

---

src/pages/docs/integrations/available-integrations/datadog.md

Refreshed Datadog integration page
- Verified steps and updated as needed
- Edited for grammar and style
- Updated screenshot
- Changed `updated`

[TW-1068] Refresh Datadog

---

bff.js

 
_Branched from `main`_, this updates the web app to us G-CX7P9K6W67 for GA
  
So that metrics are accurately collected in GA
*no-visuals

[MARKENG-2419][c] Update LC to use G-CX7P9K6W67

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/developer/postman-api/intro-api.md

Per feedback from marketing, this updates the page title to optimize its SEO presence and visibility.

PAPI-1649 Update Postman API intro-api title for SEO optimization

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/postman-flows/gs/blocks-information.md
src/pages/docs/postman-flows/gs/the-interface.md
src/pages/docs/postman-flows/tutorials/building-your-first-flow.md
src/pages/docs/postman-flows/tutorials/passing-data-between-blocks.md
src/pages/docs/postman-flows/tutorials/running-requests-in-sequence.md
src/pages/docs/postman-flows/tutorials/top-level-array.md
src/pages/docs/postman-flows/tutorials/using-auth-with-flows.md
src/pages/docs/postman-flows/tutorials/using-response-data-in-a-request.md
src/pages/docs/postman-flows/tutorials/webhooks.md

Added content about grouping, renaming, and resizing blocks. Also updated several screenshots to include the minimap and other UI changes.

[TW-1100] Flows minimap grouping qol

---

src/pages/docs/api-governance/configurable-rules/configurable-rules-overview.md

Screenshot included a feature (Functions tab) that isn't released yet. Updated the screenshot with an existing one.

[TW-1145] Fix screenshot in the Configurable rule overview page

---

src/pages/docs/developer/echo-api.md

* Changed updated date for Echo API. Everything looks current on this page.
* Created refresh tickets for other pages included in this review.

[TW-1152] Maintenance review cycle 21-25

---

gatsby-config.js
package-lock.json
package.json
src/components/Header/Dropdown.jsx
src/components/Search/searchPreview.jsx
src/pages/search.jsx
src/utils/algolia.js

This PR splits up the content into smaller chuncks after each H2.
This will reduces the average record size to 1/4th.

[Markeng-2488] Algolia update indexing method to chuncking long text

---

gatsby-config.js
package-lock.json
package.json
src/components/Header/Dropdown.jsx
src/components/Search/searchPreview.jsx
src/utils/algolia.js

Reverts postmanlabs/postman-docs#4846

Revert "Algolia 2"

---

src/pages/docs/collaborating-in-postman/manage-public-elements.md
src/pages/docs/collaborating-in-postman/sharing.md
src/pages/docs/developer/postman-api/authentication.md

Reverts postmanlabs/postman-docs#4823

Revert "[TW-1143] Update around Collection Access Keys management"

---

src/pages/docs/integrations/available-integrations/statuspage.md

- Verified procedures
- Edited for style and grammar
- Fixed vale errors

[TW-1163] Refresh Statuspage integration page

---

src/pages/docs/collections/running-collections/working-with-data-files.md

Adds a CSV file formatting tip to preserve leading zeroes in large numbers

[TW-1201] CSV file formatting

---

src/pages/docs/sending-requests/soap/making-soap-requests.md

Updates screenshots and adds small copyedits

[TW-1160] Refresh "Using SOAP Requests" doc

---

build/footerDev.json
src/components/Footer/Footer.jsx

Updated footer across Postman platforms

[MARKENG-2655] Add Cookie notice link to Legal and Security column in footer

---

src/pages/docs/collections/running-collections/working-with-data-files.md

Updates admonition about formatting numbers with leading zeroes

[TW-1228] Doc you can’t get Excel to wrap CSV numbers in quotes

---

src/pages/docs/administration/token-scanner.md
src/pages/docs/collaborating-in-postman/using-workspaces/public-workspaces.md

Updated screenshots and steps for creating a public workspace and changing visibility to public, and added a bullet to the use cases that trigger the Secret Scanner.

[TW-1220] Trigger token scan

---

src/pages/docs/collections/using-collections.md

Reverts postmanlabs/postman-docs#4959

Revert "Update using-collections.md"

---

src/pages/docs/api-governance/api-governance-overview.md

Adds the enterprise flag to the API governance and security intro

[TW-1266] Audit plan/pricing info links

---

src/components/ContextualLinks/ContextualLinks.jsx
src/components/LeftNav/LeftNav.jsx
src/components/Shared/EditDoc.jsx

* added `pmt-edit-btn` to Edit This Doc btn
* added `pmt-rightnav-link` to right nav links
* added `pmt-leftnav-link` to left nav links

add classNames to leftnav links, rightnav links, edit btn

---

src/pages/auto-flex-policy.jsx

changed price on /auto-flex-policy/ page; added Hero

---

package-lock.json

update caniuse-lite db to latest using `npx browserslist@latest --update-db`

[c] update caniuse-lite db to latest

---

src/pages/docs/administration/managing-your-team/managing-your-team.md
src/pages/docs/administration/team-merge.md
src/pages/docs/collaborating-in-postman/working-with-your-team/collaboration-overview.md
src/pages/docs/publishing-your-api/setting-up-authentication-for-public-apis.md

TW-1285
* minor universe docs improvements
TW-1138
* updating "individual account" mentions in docs to "account" as per PM terminology request

TW-1285 Universe TW-1138 IAM

---

src/pages/docs/getting-started/basics/navigating-postman.md
src/pages/docs/getting-started/basics/work-with-your-team.md
src/pages/docs/getting-started/first-steps/creating-the-first-collection.md
src/pages/docs/getting-started/first-steps/creating-your-first-workspace.md
src/pages/docs/getting-started/first-steps/exploring-public-api-network.md
src/pages/docs/getting-started/first-steps/get-postman.md
src/pages/docs/getting-started/first-steps/next-steps.md
src/pages/docs/getting-started/first-steps/overview.md
src/pages/docs/getting-started/first-steps/sending-the-first-request.md
src/pages/docs/getting-started/first-steps/sign-in-to-postman.md
src/pages/docs/getting-started/first-steps/write-your-first-test.md
src/pages/docs/getting-started/overview.md

Add Postman Academy links to Additional Resources for various Get Started topics

TW-1313 - Add academy links to LC (first round)

---

src/pages/docs/designing-and-developing-your-api/developing-an-api/defining-an-api.md

Updates the create definition screenshot and surrounding text in defining-an-api.md
[Preview](https://tw-1224-update-screenshots-in-editing-an-api-definition.learning.postman-beta.com/docs/designing-and-developing-your-api/developing-an-api/defining-an-api/#generating-an-api-definition)

[TW-1224] Update screenshots in Editing an API definition

---

src/pages/docs/designing-and-developing-your-api/mocking-data/creating-dynamic-responses.md
src/pages/docs/designing-and-developing-your-api/mocking-data/matching-algorithm.md
src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md
src/pages/docs/designing-and-developing-your-api/mocking-data/mocking-with-examples.md
src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md

* Update remaining screenshots to include the multi-protocol selector UI updates.
* Updated occurrences of `Save Response > Save as example` to `Save as Example`.

[TW-1263] Multiprotocol selector screenshots

---

bff.js

_Branched from `develop`_, this removes gtm from the LearningCenter web app.
This is a trial run to see what the impact is in doing so.
_*no-visuals_

[MARKENG-2814][c] Trial removing GTM from Learning Center site

---

bff.js

Trial removing GTM from Learning Center site for production;
https://github.com/postmanlabs/postman-docs/pull/5064

[MARKENG-2814][c] Trial removing GTM from Learning Center site (directly load GA lib)

---

src/pages/auto-flex-policy.jsx

Update Annual price on the Auto Flex Policy page to correct $168
[MARKENG-2715](https://postmanlabs.atlassian.net/browse/MARKENG-2715)
[MARKENG-2715]: https://postmanlabs.atlassian.net/browse/MARKENG-2715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MARKENG-2715] update the annual price

---

redirects.json

Updated the `redirects.json` file to fix redirect chains.

[TW-1353] Update redirects file

---

src/pages/docs/administration/managing-enterprise-deployment.md
src/pages/docs/administration/scim-provisioning/configuring-scim-with-onelogin.md
src/pages/docs/administration/sso/azure-ad.md
src/pages/docs/collections/using-newman-cli/command-line-integration-with-newman.md

All tickets included in this maintenance review require more review. I created separate refresh tickets for each page.
In this PR, updated a few quick fixes.

[TW-1370] Maintenance review cycle 31 35

---

src/pages/docs/integrations/available-integrations/keen.md

This PR makes the following updates:
- Removed the screenshots from steps 1 through 3. This may help reduce some maintenance burden and did not seem necessary (and made the page longer).
- Updated some of the UI element references.
- Removed old/unused frontmatter.
- Minor wording update to the second intro paragraph.

[TW-1074] Update Keen integration doc

---

redirects.json

[TW-1409] Add redirect for removed Domain capture page

---

package-lock.json
package.json

_Branched from `develop`_, this removes the axios package. 
It does not appear that the web app directly uses it, not that any of the other packages see it as a peer dependency
*no-visuals

[MARKENG-2248][c] remove axios

---

src/pages/docs/collections/running-collections/building-workflows.md
src/pages/docs/getting-started/first-steps/creating-your-first-workspace.md
src/pages/docs/integrations/available-integrations/azure-devops.md
src/pages/docs/sending-requests/troubleshooting-api-requests.md

This updates the following:
**/docs/integrations/available-integrations/azure-devops/**
- Added a link to MS's documentation for Azure DevOps.
**/docs/collections/running-collections/building-workflows/**
- Updated out of date screenshots.
- Vale fixes.
- Removed the statement around UID in the request ID in the *Specify the next request using the request ID* section.
**/docs/getting-started/first-steps/creating-your-first-workspace**
- Updated screenshots.
- Updated the statement in step 4 from "visibility" to "access" to match UI.
- Added **Partner** as an option.
**/docs/sending-requests/troubleshooting-api-requests**
- Updated screenshots.
- Vale fixes.
> Some of the "Console" changes in this I wasn't 100% sure about, so if there's a place where "Console" doesn't work, let me know.

[TW-1367] Maintenance review cycle 9/23 16-20

---

src/pages/docs/postman-flows/concepts/automatic-runs.md

Refreshed the concepts doc for webhooks in Flows.
Deployed beta docs are [here](https://tw-1406-flows-update-webhooks.learning.postman-beta.com/docs/postman-flows/concepts/automatic-runs/).

[TW-1406] Flows update webhooks

---

vale-styles/Vocab/LC/accept.txt

Adding two terms, fixes ~100 errors.

Fix Vale errors

---

.github/workflows/beta-deploy.yml

https://postmanlabs.atlassian.net/browse/MARKENG-2860
We need to deploy LC's page-data JSON (which contains the docs content as HTML) into WWW bucket, to be fetched across teams internally.

[MARKENG-2860] Deploy LC page-data into WWW bucket

---

.github/workflows/beta-deploy.yml

Reverts postmanlabs/postman-docs#5120

Revert "[MARKENG-2860] Deploy LC page-data into WWW bucket"

---

.github/workflows/beta-deploy.yml

https://postmanlabs.atlassian.net/browse/MARKENG-2860
We need to deploy LC's page-data JSON (which contains the docs content as HTML) into WWW bucket, to be fetched across teams internally.

[MARKENG-2860] Deploy page-data.json files into Marketing website bucket

---

src/components/LeftNav/LeftNavItems.jsx

Updates level 3 headings in the leftnav based on style guide updates

[TW-1411] Update level 3 headings

---

build/footerDev.json
build/navbarDev.json
package-lock.json
src/components/Header/Header.jsx
src/components/Header/HeaderStyles.jsx

Markeng-2855  updated LC top navbar

---

src/pages/docs/sending-requests/cookies.md

- Added a new screenshot for the Manage cookies window (**Clear all cookies** button was missing)
- Mentioned the **Clear all cookies** button
- Updated the example cookie to match prod

[TW-1384] sending requests and cookies refresh

---

src/pages/docs/collaborating-in-postman/working-with-your-team/discussing-your-work.md

Changes in this PR include:
- Reducing the number of content headings by lowering some headers to H3.
- Updated screenshot in the "Commenting on a collection, folder, or request" section.
- Removed Markdown section and added it as a callout to the "Commenting on a collection, folder, or request" section.
- Minor format and phrasing updates.

[TW-1174] Doc refresh for "Discussing your work"

---

src/pages/docs/writing-scripts/intro-to-scripts.md

* In the scripting intro page, mentioned how scripts run in Postman.
* Updated Markdown syntax for a few images.

[TW-722] Scripts execute async

---

src/pages/docs/getting-started/basics/about-vs-code-extension.md
src/pages/docs/getting-started/installation/installation-and-updates.md

[TW-1447] VS Code extension updates

---

src/pages/docs/introduction/overview.md

- Changed gerunds in headings to imperatives
- Updated document titles in links

[TW-1424] intro overview refresh

---

src/pages/docs/postman-cli/postman-cli-run-collection.md

* Added clarification that you need to copy the configuration to your CI/CD pipeline.
* Updated an outdated screenshot and label.

[TW-683] Updates to run collection in CI/CD section

---

src/pages/docs/writing-scripts/test-scripts.md

Updates the screenshots, expands the intro, fixes typos

[TW-1421] Refresh writing-scripts/test-scripts

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/administration/admin-overview.md

Part of the Administration docs improvements
Styled after https://learning.postman.com/docs/collections/collections-overview/
Beta: https://tw-1272-add-overview-to-admin.learning.postman-beta.com/docs/administration/admin-overview/

TW-1272 add overview to admin section

---

package-lock.json

* the `package-lock` file was missing
* reran `npm run nvmrc; nvm install; npm i` to regenerate it
* no changes to packages, as we do not use `^`

replace the missing package lock file

---

package-lock.json
package.json

[MARKENG-2944](https://postmanlabs.atlassian.net/jira/software/c/projects/MARKENG/boards/399?assignee=62a78584979e6e006904329f&selectedIssue=MARKENG-2944)
Update the Aether-Marketing package
[MARKENG-2944]: https://postmanlabs.atlassian.net/browse/MARKENG-2944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MARKENG-2944] update Aether-marketing package

---

src/pages/docs/live-insights/live-insights-gs.md

[POA-318] Incorrect API key link

---

src/components/Header/Header.jsx
src/components/Header/HeaderStyles.jsx

This addresses issues with dropdown/button UI in the global and secondary navbar, making it more similar to the www version.
**Feature Branch**
https://markeng-2918.learning.postman-beta.com/
**Issues:** 
Breakpoint collapsing issue when switching to mobile
Space between menu

[MARKENG-2918] Navbars: web and mobile UI corrections for buttons and dropdowns

---

package-lock.json
package.json
src/components/ContextualLinks/__snapshots__/ContextualLinks.spec.jsx.snap
src/components/Footer/__snapshots__/Footer.spec.jsx.snap

update `googleapi` package to latest 
which updates package-lock file

[MARKENG-2942][c] update googleapis package to latest

---

src/components/Header/Header.jsx

This updates the navbar onClick dropdown animation to use a fade effect similar to the Product version.
Feature: https://markeng-2918-b.learning.postman-beta.com/

[MARKENG-2918] Nav dropdown animation update

---

src/pages/docs/integrations/available-integrations/datadog.md
src/pages/docs/integrations/available-integrations/keen.md
src/pages/docs/integrations/available-integrations/opsgenie.md
src/pages/docs/postman-flows/tutorials/make-your-own-automatically-scheduled-tasks.md

[TW-1499] Remove postman.postman links

---

package-lock.json
package.json

_Branched from `main`_, this makes the pmt package optional
So contributors can install w/o hassle  
*no-visuals

[MARKENG-2916][c] optional pmt (v2.0.17) package

---

src/pages/docs/live-insights/live-insights-gs.md

Updates the Insights tab screenshot to reflect the addition of graphs

[TW-1523] Replace the Insights tab screenshot

---

package-lock.json
package.json

_Branched from `develop`_, this updates pmt to v2.0.21 for the api update
 This update gets the api interface for persisting values across *[postman.com](http://postman.com/) web apps.  *no-visuals

[MARKENG-2959][c] pmt v2.0.21 (api)

---

src/pages/docs/writing-scripts/test-with-monitors.md

Made a quick change - going for lunch but will probably run a quick check for other similar quick examples after 💃🏻
- Updated test-with-monitors documentation to use new test syntax

chore: update Test with Monitors examples to use new syntax

---

src/components/Header/Header.jsx

Switch from local json file to navbar API

switch Navbar API

---

package-lock.json
package.json

updated Webpack to 5.89.0 and removed 2 critical vulnerabilities

updated Webpack to 5.89.0

---

src/pages/docs/writing-scripts/test-scripts.md

This updates the gif in the _Write tests using Postbot_ section to match the current UI. In reviewing the written workflow it appears that it remains the same. I scaled the image up as the current Postbot changes resulted in a larger screen presence (and a larger gif).

Update gif in Write tests using Postbot

---

src/components/Search/searchPreview.jsx
src/utils/algolia.js

update query to include early_access in index

Algolia early access

---

gatsby-config.js
src/components/Search/searchPreview.jsx
src/utils/algolia.js

dev to prod

---

src/pages/docs/live-insights/live-insights-gs.md

Updates screenshots based on the latest UI changes
[Preview](https://tw-1618-live-insights-ui-updates-1-15.learning.postman-beta.com/docs/live-insights/live-insights-gs/#observe-live-insights)

[TW-1618] Live Insights UI Updates 1/15

---

src/pages/docs/monitoring-your-api/intro-monitors.md
src/pages/docs/monitoring-your-api/setting-up-monitor.md

* Updated the featured snippet
* Reorganized and relocated content as needed
* Added links to and brief intros about majors topics in the section

[TW-1544] Monitors overview refresh

---

src/pages/docs/collections/collections-overview.md
src/pages/docs/collections/using-collections.md
src/pages/docs/introduction/overview.md

Refreshes the collections overview and the subsequent page

[TW-1534] Refresh /docs/collections/collections-overview

---

package-lock.json

ran `npm update ws --depth 4` as per suggestion from `npm audit` to clear 1 package VULN

[c] update ws package to depth of 4

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/collections/performance-testing/performance-test-configuration.md
src/pages/docs/collections/performance-testing/performance-test-data-files.md
src/pages/docs/collections/performance-testing/performance-test-errors.md
src/pages/docs/collections/performance-testing/performance-test-metrics.md
src/pages/docs/collections/performance-testing/testing-api-performance.md
src/pages/docs/collections/running-collections/intro-to-collection-runs.md

- Break `testing-api-performance.md` into separate overview and procedure pages
- Rewrite overview content and featured snippets
- Update links as needed

[TW-1536] Refresh /docs/collections/performance-testing/testing-api-performance

---

src/pages/docs/designing-and-developing-your-api/deploying-an-api/deploying-an-api-overview.md

Refresh includes:
- Minor revision to the opening statement.
- Rearranged the list of gateways based on their order in the UI.
- Updated the screenshot to match the current UI version.

[TW-1541] Refresh Manage API deployments in Postman

---

build/footerDev.json

[MARKENG-3111] update copyright date

---

.github/workflows/beta-deploy.yml
.github/workflows/prod-deploy.yml
src/components/Footer/__snapshots__/Footer.spec.jsx.snap
static/codex.test.js

Added jest test to lint codex file and added `npm run test` to github actions. 
Update snapshot

[markeng-3146] added test to lint codex json file

---

redirects.json
src/pages/docs/insights/insights-early-access.md
src/pages/docs/insights/insights-gs.md
src/pages/docs/insights/insights-overview.md
src/pages/docs/insights/insights-reference.md
src/pages/docs/insights/insights-troubleshoot.md

Renames Insights doc folders and file names for rebrand

[TW-1726] Rename Insights folder and file names

---

src/pages/docs/collaborating-in-postman/requesting-access-to-elements.md

* 15 days should be 30
* A quick vale fix

Approving requests for access - expiration deadline

---

src/pages/index.jsx

Low-hanging fruit; Tech debt item. 
- Removes unused imports in index.ts
- No behavioral changes

Remove unused imports in Index.ts

---

src/pages/docs/insights/insights-early-access.md
src/pages/docs/insights/insights-gs.md
src/pages/docs/insights/insights-overview.md
src/pages/docs/insights/insights-reference.md
src/pages/docs/insights/insights-troubleshoot.md

Updates all Insights topics for 3/11 release
Previews:
* [About Postman Insights Early Access](https://tw-1682-live-insights-onboarding-update.learning.postman-beta.com/docs/insights/insights-early-access/)
* [Postman Insights overview](https://tw-1682-live-insights-onboarding-update.learning.postman-beta.com/docs/insights/insights-overview/)
* [Get started with Postman Insights](https://tw-1682-live-insights-onboarding-update.learning.postman-beta.com/docs/insights/insights-gs/)
* [Diagnose and troubleshoot errors](https://tw-1682-live-insights-onboarding-update.learning.postman-beta.com/docs/insights/insights-troubleshoot/)
* [Postman Insights Agent reference](https://tw-1682-live-insights-onboarding-update.learning.postman-beta.com/docs/insights/insights-reference/)

[TW-1862] Live Insights onboarding update

---

src/pages/docs/sending-requests/capturing-request-data/capture-overview.md

- Updated featured snippet
- Changed headings to match new styles
- Fixed vale errors

[TW-1532] - Refresh /docs/sending-requests/capturing-request-data/capture-overview

---

src/pages/docs/collaborating-in-postman/requesting-access-to-elements.md
src/pages/docs/collaborating-in-postman/sharing.md
src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
src/pages/docs/getting-started/basics/about-vs-code-extension.md

Reverts postmanlabs/postman-docs#5440

[TW-1673] VS code - share collections invite to workspaces (revert)

---

src/pages/docs/getting-started/basics/about-vs-code-extension.md

Updated the hero image to include the invite to workspace button in the left pane.

[TW-1720] Update VS Code hero image

---

src/pages/docs/insights/insights-gs.md

Adds a sentence about adding selected endpoints to an existing Insights collection

[TW-1744] Add to existing Insights

---

src/components/LeftNav/LeftNavItems.jsx
src/pages/docs/collaborating-in-postman/public-api-network/share-collection-with-public-api-network.md

[TW-1708] Assist Network Evangelist with API Network Self-Serve Doc

---

src/pages/docs/collaborating-in-postman/using-workspaces/multipartner-workspaces.md
src/pages/docs/getting-started/basics/about-postman-agent.md

Updates the sign-up and availability note

[TW-1751] Multi-partner workspaces update
