_posts/06_api_testing_and_collection_runner/2016-07-11-sandbox.md
cc @shamasis Please review the version numbers and the link to library set for `xml2json`.
cc @numaanashraf
=> Updated sandbox docs with the version numbers of libraries relative to chrome vs native app

_data/doc_map.json, _posts/01_postman/03_collections/2017-05-04-examples.md, _posts/01_postman/03_collections/2017-05-04-using_markdown_for_descriptions.md, _posts/01_postman/04_scripts/2017-05-04-postman_sandbox_api_reference.md, _posts/03_enterprise/2017-05-04-apply_for_beta_access.md
- add examples page
- add descriptions for request attributes to markdown descriptions page
- fix typo on API sandbox reference page
- remove beta language on apply for enterprise beta page
@godfrzero  @madebysid could you please review?
=> add examples page

_posts/01_postman/06_collection_runs/2017-05-04-building_workflows.md
@loopDelicious 
The setNextRequest docs were wrong in saying that you can skip a request using it's own pre-request script. Have corrected this here.
=> Fix setNextRequest docs to correct behaviour

_data/doc_map.json, _posts/01_postman/08_api_documentation/2017-05-04-adding_team_name_and_logo.md, _posts/02_pro/01_managing_pro/2017-05-04-team_settings.md, _posts/03_enterprise/2017-05-04-intro_to_enterprise.md
move custom team urls out of `API documentation` section, and add as section under new page `Team Settings` in Postman Pro, with cross links to API documentation adding team name and logo, intro to enterprise, and Managing pro inviting and managing.
=> break out custom team urls to separate page

_posts/01_postman/01_launching_postman/2017-05-04-installation_and_updates.md
If the current installation directory is replaced with the new ones there is no gaurantee that unused files are removed. This might cause issues sometimes.
=> Make linux update docs clearer

_includes/_related_links.html
Reported by deepakpathania, and I confirmed, the next page btn on mobile lead to 404
for example this page. 
https://www.getpostman.com/docs/postman/launching_postman/sending_the_first_request
If you open it in a mobile browser, then ‘Creating first collection’ at bottom of page leads to a 404 (https://www.getpostman.com/postman/launching_postman/creating_the_first_collection)
=> fix next page link

v6/postman/collection_runs/command_line_integration_with_newman.md
It was incorrectly specified as `--global`, instead of `--globals`:
https://github.com/postmanlabs/newman#newman-run-collection-file-source-options
cc @joyous-joyce
=> Fixed Newman global variable CLI option

_data/v5_map.json, _data/v6_map.json
Adds the References and Videos links back, with additional trailing slash to avoid 301 from GH pages.
=> Add trailing slashes to the some docs routes to avoid undesirable redirection

v6/enterprise/sso/admin_sso.md
Current documentation for "Managing user accounts", found within [Single Sign-On for Admins](https://www.getpostman.com/docs/v6/enterprise/sso/admin_sso), is unclear and contains contradictory information regarding what is required for adding users to a team.
* Reworded flow for adding new users to a team.
* Fixed incorrect role.
* Fixed formatting for adding existing user accounts.
* Fixed inaccurate user removal flow.
=> Fix "Managing user accounts" to more accurately reflect current process

_config.yml, v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/environments_and_globals/manage_environments.md, v6/postman/environments_and_globals/variables.md, v6/postman/mock_servers.md, v6/postman/mock_servers/mock_with_api.md, v6/postman/team_library/setting_up_team_library.md, v6/postman/team_library/sharing.md, v6/postman_for_publishers/run_button/environments_run_button.md
Before v6.0, we referred to "local environments" and "environment templates".
After v6.0, environments can now be synced, so we should refer to "local environments" and "shared environments". Even though it might be correct by English standards, refrain from using "template" in the context of environments and sharing.
@staysea
=> Remove references to "environment template"

v6/postman/collection_runs/starting_a_collection_run.md
Fixing the hyperlink within Iterations so that it points to the right documentation – Running multiple iterations should point to `/docs/v6/postman/collection_runs/running_multiple_iterations`
=> Fix Hyperlink

v6/postman/collections/managing_collections.md
The change in prod looks like this:
=> Removed line that says 'Folders are ordered alphabetically'

v6/postman/collections/managing_collections.md
Removed undo delete information, modified content per new functionality. The docs page in prod looks like this:
=> Removed undo delete information 

v6/postman/launching_postman/navigating_postman.md
The snapshot was outdated in navigating_postman.md chapter. The new one's here:
=> Updated Main UI with callouts

v6/enterprise/intro_to_enterprise.md, v6/enterprise/purchasing_enterprise.md, v6/enterprise/using_static_IPs_to_monitor.md, v6/postman/api_documentation/intro_to_api_documentation.md, v6/postman/collection_runs/integration_with_travis.md, v6/postman/team_library/activity_feed_and_restoring_collections.md, v6/postman/team_library/searching.md, v6/postman/team_library/sharing.md, v6/pro/managing_pro/managing_your_billing.md, v6/reference/index.md, v6/videos/index.md
With the new Learning Center we can no longer process {:target=“_blank”} like what was done with previous docs setup. However, any external link will have target and relationship attributes applied to it with a Markdown transforming plugin.
We are also fully migrating from getpostman.com/docs over to learning.getpostman.com over the next several days.
=> Removing {:target=“_blank”}

v6/postman/migrating_to_v7.md
The incorrect name/slug was causing problems updating the learning center
=> Update and rename migrating_to_postman_v7.md to migrating_to_v7.md

v6/pro/what_is_pro.md
The hyperlink is currently pointing to /docs/postman/team_library – our legacy collaboration feature – which is causing some confusion when perusing the documentation.
@ArifPMan
=> Update Team Collaboration Hyperlink

v6/postman/collection_runs/newman_with_docker.md
The documentation erroneously pointed to the deprecated [postman/newman_ubuntu1404](https://hub.docker.com/r/postman/newman_ubuntu1404) image instead.
=> Corrected Newman docker image name

_includes/_search.html
This removes the Algolia logo from the search dropdown. This fixes Issue #1480.
=> [743] uncommented out the 'poweredBy' line

v6/postman_for_publishers/public_api_docs.md
Pro plan is not required to publish documentation
=> Remove "Pro" from the documentation page

v6/postman/collection_runs/newman_with_docker.md
Added missing 'run' cmd for docker instruction 4. Please review and approve.
=> Added missing 'run' cmd for docker instruction 4

v6/postman/design_and_develop_apis/managing_apis.md, v6/postman/design_and_develop_apis/sharing_apis.md, v6/postman/design_and_develop_apis/the_api_workflow.md, v6/postman/design_and_develop_apis/versioning_an_api.md
After the Design and Develop APIs renaming, the directory structure for links changed. The new directory was updated along with the following chapter name too. For instance,  [Managing API workflow](/docs/v6/postman/design_and_develop_apis/the-api-workflow). The chapter 'the-api-workflow' had an underscore originally, but got replaced with a hyphen. I updated all the links. They should be working now. Currently, most of the external links don't work.
=> 404 Error for all External Links

v5/postman/collection_runs/building_workflows.md, v6/postman/collection_runs/building_workflows.md
**Change:** setNextRequest -> scope -> clearer message
**Why**
The current message says "postman.setNextRequest() is always executed at the end of the current script" which is ambiguous to understand as the current script can be "Pre-Request" or "Test" 
due to misunderstanding, I ended up investing time in debugging the actual cause. 
Discussion with Joyce [here for reference](https://community.getpostman.com/t/workflow-how-to-run-another-test-in-loop/2126/7?u=p00j).
=> setNextRequest scope: clearer guideline

_config.yml, _includes/_footer.html, v6/postman/collection_runs/building_workflows.md, v6/postman/collection_runs/newman_with_docker.md, v6/postman/collections/data_formats.md, v6/postman/collections/sharing_collections.md, v6/postman/environments_and_globals/variables.md, v6/postman/launching_postman/installation_and_updates.md, v6/postman/scripts/postman_sandbox.md, v6/postman/sending_api_requests/authorization.md, v6/postman/sending_api_requests/making_soap_requests.md, v6/postman_pro_integrations/slack_integration.md, v6/pro/integrations/intro_integrations.md, v6/variables_and_environments/environments.md, v6/variables_and_environments/multiple_instances.md, v6/variables_and_environments/test_multi_environments.md
Fixes #1648 
— updated all /v6 docs with `http://blog` to us https (re-verified links resolved)
— updated any `/v6` docs links on page to resolved URL
— updated headings hierarchy (H1 > H2 > H3) to improve readability
=> 1648 blog link cleanup + heading formatting

v6/postman/sending_api_requests/capturing_http_requests.md
This fixes issue #1646 
— updated link for Apple as per O.P.
— updated header formatting to be hierarchical and SEO friendly (H1 > H2 > H3)
— updated links to blog images to remove http and redirects (making new issue to do global cleanup)
=> 1646 updated link to Apple + img links

v6/postman/launching_postman/keyboard_shortcuts.md, v6/postman/launching_postman/navigating_postman.md
This fixes issue #1640 
— moved keyboard shortcuts to a new page
— fixed redirecting links in Navigation page
— fixed hierarchy / headings to utilize SEO-friendly structure H1 > H2 > H3
=> 1640 split out Nav page into two pages

v6/postman/launching_postman/installation_and_updates.md
General cleanup of the first doc "Installation and updates". The first impression of the top of this doc was three headings stacked on top of each other:
Upon further inspection, there was some general cleanup that was needed:
— readjust headings to be hierarchical
— update 'postman' to be 'Postman'
— improve phrasing in a few areas
— remove redundant 'note'
— removed link to self
— added link to bulk import doc
— fixed inline code styling (tick marks usage)
=> Cleaned up headings, Postman name, links, duplicate words

v6/postman/design_and_develop_apis/reporting_faqs.md
page_ids should be lowercase and have no spaces. Now matches Contentful slug.
=> updated page_id slug

v6/postman/sending_api_requests/debugging_and_logs.md
Fixes issue #1670 
— updated broken link to support center.
— updated language around sending confidential info in your support request (to be more specific to Support Center and not confused with sending in GitHub issues tracker)
— updated headings hierarchy (headings were too deep; updated to use H2's and H3's)
=> 1670-broken link, and updated headings hierarchy

v6/postman/sending_api_requests/requests.md
This fixes issue #1671 
— updated broken link (at bottom of page), and link text to match title of page it is linking to (to help SEO linking strategy)
— updated hierarchy of headers (many were too deep, and should be H2's and H3's)
— updated some headers to be more descriptive
=> 1671-updated broken link, fixed headers hierarchy

v6/pro/pro_api/intro_api.md
Updating the Pro API URLs to point to the right place – https://go.postman.co/integrations/services/pm_pro_api
=> Update go links to Pro API Integration page

v6/postman/scripts/postman_sandbox_api_reference.md
- Added functions from the `pm.*` API that was missing from the docs
- Fixed a code block formatting issue
- Updated some examples and text for some functions
=> Updated to include missing `pm.*` functions

v6/postman/scripts/postman_sandbox.md
Replaced all old `postman.*` methods in the Environment and Globals section of the page on Postman Sandbox to use their corresponding `pm.*` methods. Also, added entries for `pm.environment.has()` and `pm.globals.has()` methods.
This PR fixes #1708.
=> [RUNTIME-945] Update env and global variable methods in Sandbox doc.

v6/postman/scripts/test_examples.md
Instead of removing or replacing the old syntax as I filed in #1711, I have marked the section of "Test Examples" page with a `deprecated` notice.
This PR will close #1711.
=> [RUNTIME-945] Mark deprecated section in Test Examples and improve content hierarchy

v6/postman/mock_servers/intro_to_mock_servers.md, v6/postman/mock_servers/matching_algorithm.md, v6/postman/mock_servers/mock_with_api.md, v6/postman/mock_servers/mocking_with_examples.md, v6/postman/mock_servers/setting_up_mock.md
This PR fixes markdown lint issues and reorders content hierarchy for the Mock Servers section.
Pages affected:
- `Mock Servers/Intro to Mock Servers`
- `Mock Servers/Setting up Mock`
- `Mock Servers/Mocking with Examples`
- `Mock Servers/Mocking with API`
- `Mock Servers/Matching Algorithm`
=> Fix lint issues and redo hierarchy for Mock Servers section

v6/postman/scripts/postman_sandbox.md, v6/postman/scripts/postman_sandbox_api_reference.md
This PR adds all new dynamic variables (the `$random*` ones) introduced as part of Faker integration in the Postman Sandbox API Reference page in the docs. I have additionally segmented the variables into easily identifiable sections.
Apologies for a really long diff. This was the most I have worked with Markdown tables in a go.
Question for @postmanlabs/runtime, should these stay in the Sandbox API Reference page, or should I create another page just to list all the dynamic variables and link to it from the Sandbox API Reference page?
[**Rendered**](https://github.com/postmanlabs/postman-docs/blob/feature/runtime-943-add-dynamic-vars-in-sandbox-reference/v6/postman/scripts/postman_sandbox_api_reference.md)
=> [RUNTIME-943] Add all new dynamic variables to Sandbox API Reference

v6/postman/scripts/test_examples.md
This PR removes rendering of `<code>` tags in headings for the Test Examples page.
Fixes #1719.
=> Change headings to contain only text

v6/postman/mock_servers/mocking_with_examples.md
Added a small section in `Mocking with Examples` about using dynamic variables in Mock Response Body.
[**Rendered**](https://github.com/postmanlabs/postman-docs/blob/feature/APIDMOCK-43-faker-support-in-mock-body/v6/postman/mock_servers/mocking_with_examples.md#using-random-data-dynamic-variables)
=> APIDMOCK-43 Add section on using dynamic variables in Mock body

v6/postman/mock_servers/mocking_with_examples.md
A quick fix for typo that skipped review in #1733.
=> Fix typo in Mocking with Examples that escaped review

v6/enterprise/sso/saml_okta.md
Was working with @aamir-ahmed on edits to this page to fix some image and formatting bugs. When I went to verify the latest changes, there was one small image bug. So, I fixed it.
While in there, I noticed my Markdown linter picked up on numerous small issues also causing some not-so-obvious formatting issues.
As I was checking the page, I noticed that the steps were hard to distinguish, so I improved them for 1) readability, and 2) adding in anchor tags for sharing.
**Things to look for:**
— all images now show (no raw code showing for images)
— no codeblocks present
— doc starts with an H2, steps are H3s
— converted ordered list to H3s to improve readability
— prepended each step with unique section word to 1) make anchor tagging unique (i.e. Okta - Step 2, Postman - Step 4), and 2) …
=> Fixed img bug; updated formatting; ran thru linter

v6/postman/environments_and_globals/variables.md
Fix for #1718 
Changed the link in the docs to the Sandbox API reference. 
The only issue is I don't know how to do an anchor by id in Jekyell so I only did a hard link to the site's anchor on dynamic variables. 
If someone can find and show me an example of an anchor link on a header that'd be helpful and I can make that change.
=> #1718 changed dynamic link to postman sandbox api reference

v6/postman/sending_api_requests/visualizer.md
This PR introduces a new document for Visualizers in Postman. I have added a short description, a quick idea of how the feature works, a video screencast of Visualizers in action and a Run-in-Postman button for the template demonstrated in the screencast.
This page should have more details in future, including, info on `pm.getData()` method, further explanation of the possibilities with Visualizer, and more examples. For now, let's get the ball rolling.
Reviewers, let me know if you think this is headed in the right direction and if the video snippet will render in production.
Note: this page is not linked from the left sidebar in Learning Center yet. I'll add that separately later on.
[Rendered](https://github.com/postmanlabs/postman-docs/blob/feature/RUNTIME-941-visualizer/v6/postman/sen …
=> [RUNTIME-941] Add initial docs on Visualizer

v6/postman/sending_api_requests/visualizer.md
Remove usage of `{% raw %}` liquid tags in Visualizer doc. Jekyll threw error without them, but looks like we don't need it.
@tristandenyer FYI, this happened because Jekyll would throw Liquid parsing errors while rendering locally, but Contentful does not require those? This is a quick fix, so pushing without a review.
=> visualizer: Fix non-rendering of raw liquid tags

v6/postman/collection_runs/starting_a_collection_run.md
Added the following pieces of information to "starting a collection run" section:
1. Customising the execution of requests, specifically, the order and the state of execution i.e. if a request will be executed or not.
2. Saving the cookies for after the collection run to the collection manager.
=> [Runtime-1059] Collection runner: Describe customizing requests and saving cookies

CODE_OF_CONDUCT.md
fixes #1764 
— added Code of Conduct page
— linked it to the Code of Conduct we link all Postman communities to.
=> [1764] adding Code of Conduct page

v6/postman/monitors/faqs_monitors.md
Fix #1707 .
This PR updates the answer to "Who can see my Monitors?" to explain that monitors stay within the workspace they were created in regardless of where their associated collections are shared. 
It also adds "Who can edit my Monitors?", as the original version of the aforementioned answer verged into discussing editing permissions. I think it makes sense to separate the two for clarity.
=> Update Monitoring FAQ

v5/postman/team_library/sharing.md
Fix #1805 . 
[V5 page](https://learning.getpostman.com/docs/postman/team_library/sharing/) is still indexed and accessible to users. Link to Activity Feed is correct in V6 file.
=> Fix broken link in Sharing (v5)

v6/pro/managing_pro/migrating_to_v7.md, v6/pro/managing_pro/roles_and_permissions.md
Files changed:
- `v6/postman/migrating_to_v7.md` -> `v6/pro/managing_pro/migrating_to_v7.md`
- `v6/postman/roles_and_permissions.md` -> `v6/pro/managing_pro/roles_and_permissions.md`
These files were deleted in #1789. They were in the `v6/postman/` directory, but Contentful had picked those changes initially. Moving them to their rightful positions and will observe if Contentful borks.
This will close #1814.
=> Bring back deleted files that belong to the managing_pro section

README.md
Fixes #1830 
— added logo to top
— added description of LC
— updated instructions
— added resources and license sections
=> 1830 updated info and instructions

v6/pro/integrations/github.md
This pull request fixes the issue #1833 where the Github integrations page renders markdown instead of the image under Backup collections to Github on custom domain.
=> Fix: image link being rendered instead of actual image.

v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/api_documentation/intro_to_api_documentation.md
Added:
- RiP button mention to [What gets automatically generated?](https://learning.getpostman.com/docs/postman/api_documentation/intro_to_api_documentation/#what-gets-automatically-generated) in "Intro to API documentation".
- RiP button mention to [Environments in public documentation](https://learning.getpostman.com/docs/postman/api_documentation/environments_and_environment_templates#environments-in-public-documentation) in "Local environments and shared environments".
=> [DOCUMENTER-1243] Add Run in Postman button to documentation docs

src/components/Header/Header.scss, src/components/LeftNav/LeftNav.jsx, src/components/LeftNav/replacements.json
This is a hold over, I would like to find a way to do this in frontmatter but it's tricky because each parent has multiple children which all have their own frontmatter, so it's wide open for conflicts. maybe fix it in the future by creating an index.md file that informs parent name and child order but doesn't render a page?
=> pulls replacements from json file

src/pages/docs/postman/design-and-develop-apis/managing-apis.md
Added docs for schema changelog under `Design and Develop APIs -> Managing APIs`.
=> Add docs for schema changelog

src/pages/docs/postman/mock-servers/matching-algorithm.md
Added docs in the list under Mock Servers -> Matching Algorithm.
=> Add wildcard request matching docs for Mocks

package.json
added a script in package.json to run the Markdown linter locally with `npm run test:mdlint`.
Added this line to the contribution doc in an earlier PR.
=> added script in package.json

src/pages/docs/postman/sending-api-requests/visualizer.md
This fixes #1913 
— I added a "Templates" section to the right sidebar for the /visualizer/ page
— Added 3 links to interesting templates demos
=> 1913 - added Templates and links to right sidebar

src/pages/docs/postman/sending-api-requests/interceptor-extension.md
Anchor link had a trailing '/' - causing the browser to not scroll to the heading.
Install the [Interceptor bridge](#installing-the-interceptor-bridge/)
Have removed it to fix it.
=> Fixed anchor link for step 1 - "Install the Interceptor bridge"

src/pages/docs/postman/scripts/postman-sandbox-api-reference.md, src/pages/docs/postman/scripts/postman-sandbox.md
Adds `pm.environment.name` to the documentation in the Postman -> Scripts -> Postman Sandbox section. See #1922. 
Edit: Added updates to the Postman Sandbox API References too
=> Document pm.environment.name

src/pages/docs/postman/launching-postman/installation-and-updates.md
Generic redraft of installation guide, content hasn't really changed, just restructured etc - I did remove some of the troubleshooting section on specific problems, thinking if it's a temporary issue it probably belongs in the forum rather than docs..
I _think_/_hope_ this fixes #1960, fixes #1773, and fixes #1731 - also referencing postmanlabs/postman-app-support#7581
=> Installation doc redraft

.github/stale.yml
This bot sends a notification to the assignee and adds the label 'stale' to 
- PRs that are older than 7 days 
- Issues that are older than 14 days
As soon as an interaction with PR/issue has occured, the label is removed. 
This helps keeping track of open/stale PRs and Issues
=> Stalebot implementation for old PRs & issues

src/components/Header/Header.scss, src/components/Search/_search.scss
fixes #1998 
— added 16px of padding to left and right of buttons in navbar
— also added some top and bottom padding to make them fill the height of the navbar so as to be no space where there wasn't a click area.
— checked mobile sizes
— ran linter
=> 1998 increase spacing between buttons in navbar

legacy-documentation/v5/api_testing_and_collection_runner/sandbox.md, legacy-documentation/v5/postman/environments_and_globals/variables.md, legacy-documentation/v5/postman/scripts/postman_sandbox.md, legacy-documentation/v5/variables_and_environments/environments.md, src/pages/docs/postman/environments-and-globals/variables.md, src/pages/docs/postman/scripts/postman-sandbox-api-reference.md, src/pages/docs/postman/scripts/postman-sandbox.md
After some initial confusion over this value being displayed in seconds or milliseconds, I've updated the learning docs in various places, to include `(Unix timestamp in seconds)` as part of the description.
=> Update to the description on the `timestamp` dynamic variable

src/pages/docs/postman/scripts/test-scripts.md
While using the documentation I noticed an typo so I fixed it :)
=> Correcting a typo on link to youtube video on test script doc

src/pages/docs/postman/mock-servers/setting-up-mock.md
Documented remaining mock server flows through collection sidebar and history request.
**[Rendered](https://github.com/postmanlabs/postman-docs/blob/feature/devrel-71-mock-creation-gaps/src/pages/docs/postman/mock-servers/setting-up-mock.md#collection-sidebar)**
Fixes #1498
=> [DEVREL-71] Document remaining mock server creation flows

redirects.json
fixes #1802 
The app points to an old URL that does not self-resolve using the built-in logic we set up.
I added a redirect to resolve to the latest and most-similar page: "Test Scripts" https://learning.getpostman.com/docs/postman/scripts/test-scripts/
=> 1802 updated redirects for old page

src/pages/docs/postman/variables-and-environments/variables.md
Fix example for environment variable usage in script : "variable_value" and not "variable_key" as second argument.
=> Fix example for environment variable

src/pages/docs/postman-pro/managing-pro/managing-your-team.md
A bad `localhost` URL was left from local development; removed it in favor of a directory link.
=> Removed a localhost:8080 URL

src/pages/docs/postman/variables-and-environments/variables.md, src/utils/algolia.js
added a code_keyword to frontmatter in docs yml file. That way we can capture terms from within <code> and <pre> tags that we want to have indexed by Algolia
=> added code_keyword to frontmatter

src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md, src/pages/docs/postman/mock-servers/setting-up-mock.md
Completes #1955 with the new flow of creating a Mock from the API section of the app. 
- Added a create Mock from API Dev in Setting up a Mock https://learning.getpostman.com/docs/postman/mock-servers/setting-up-mock/
- Added Actions on Mock servers in Developing an API https://learning.getpostman.com/docs/postman/design-and-develop-apis/the-api-workflow/#developing-an-api
=> Update mock docs for API Dev 

gatsby-config.js, package-lock.json, package.json, src/components/LeftNav/__snapshots__/LeftNav.spec.jsx.snap, src/pages/docs/postman/sending-api-requests/visualizer.md, src/templates/doc.jsx
@SueSmith  Markdown does not support iFrames and therefore a Youtube video cannot be embedded with the iFrame code.
I included two Gatsby plugins: gatsby-remark-embed-video and gatsby-remark-responsive-iframe.
This allows very easy embedding in Markdown with this syntax: 
`video: <url to video>`
=> Issue #2098

src/pages/docs/postman/scripts/postman-sandbox-api-reference.md
Describe the need to whitelist domains when using `pm.cookies.jar`. Prevents running into this unclear error (fixing this separately):
=> Clarify prereqs for pm.cookies.jar usage

src/pages/docs/postman/launching-postman/collaboration.md
This link is in a notification that shows when users are reaching their limit of APIs created but the documentation page doesn't actually mention APIs. This fixes it.
=> Adding APIs to the list of items listed in usage limits

src/pages/docs/postman/sending-api-requests/visualizer.md
The table rendered in dark mode has poor contrast as the text and background are black in color.  
Hardcoding the `bgcolor` for the table will ensure proper contrast for the table.
=> Add bgcolor to html table for dark mode support

src/pages/docs/postman/design-and-develop-apis/validating-elements-against-schema.md, src/pages/docs/postman/sending-api-requests/validating-requests-against-schema.md
Some users were surprised that nothing was happening when validating their schema/requests (https://github.com/postmanlabs/postman-app-support/issues/6614#issuecomment-580116252) so I've added the release version from which this is available in the documentation.
cc @dushyantchillale
=> Added release version for schema validation

src/pages/docs/postman/workspaces/changelog-and-restoring-collections.md
This adds the notion of being able to filter by API entity in the activity feed.
ETA for prod is 27th of Jan.
=> added API entity in activity feed filtering

src/pages/docs/integrations/github.md
Old gif mentioned both `user` and `repo` scope when only `repo` is needed.
=> Updated gif for 2 way sync github integration

src/pages/docs/postman/collection-runs/sharing-a-collection-run.md
Mainly copy changes and image updates (all attached) but also added additional information around exporting/imported multiple collections run results.
There's a broken image link on the page, this is for a new image of the multiple exports that would need to be uploaded before publishing.
=> Updates to the importing and exporting collection runs

src/components/Header/Header.jsx
The 'SignIn' Button did not change to 'Dashboard' after user signed in. This has been fixed now.
=> Sign in button bug fixed

src/pages/docs/postman/scripts/postman-sandbox-api-reference.md
There are a few methods missing from the `pm.*` API that needed to be included in the Learning Center documentation. Also, a rename of an existing method was required as this was causing confusion.
- `pm.request.method` was missing and is part of the `pm.request` object.
- `pm.request.body` mentioned in this issue https://github.com/postmanlabs/postman-docs/issues/1994
- `pm.request.headers.delete()` This was incorrect and should have been `.remove()` 
- `pm.response.reason()` This was renamed to `.status`
- `pm.response.responseSize` This was missing from the documentation
-  Included the `.replaceIn()` function to each variable scope as this was missing from the documentation. https://github.com/postmanlabs/postman-docs/issues/2181
=> Updated file to include missing pm.* API methods

src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md
Since the notion of "Max # of APIs" wasn't clear, we've published a blog post about it and we thought it'd be a good idea to add it to the LC too.
Ref: https://blog.postman.com/2020/01/24/what-does-max-of-apis-mean-in-postman/
=> Added ref to max number of api blogpost

src/pages/docs/postman/mock-servers/setting-up-mock.md
@vvs11 kept it pretty simple for now but can def add more detail later - just added two sections to the setting up mocks page, one on mock call logs generally and one on troubleshooting.
=> Add mock call logs

src/pages/docs/postman-for-publishers/run-in-postman/creating-run-button.md, src/pages/docs/postman-for-publishers/run-in-postman/environments-run-button.md, src/pages/docs/postman/api-documentation/documenting-your-api.md, src/pages/docs/postman/api-documentation/viewing-documentation.md, src/pages/docs/postman/collection-runs/integration-with-jenkins.md, src/pages/docs/postman/collection-runs/integration-with-travis.md, src/pages/docs/postman/collections/creating-collections.md, src/pages/docs/postman/collections/intro-to-collections.md, src/pages/docs/postman/mock-servers/intro-to-mock-servers.md, src/pages/docs/postman/mock-servers/mock-with-api.md, src/pages/docs/postman/monitors/intro-monitors.md, src/pages/docs/postman/monitors/viewing-monitor-results.md, src/pages/docs/postman/postman-api/continuous-integration.md, src/pages/docs/postman/scripts/intro-to-scripts.md, src/pages/docs/postman/scripts/test-examples.md, src/pages/docs/postman/scripts/test-scripts.md, src/pages/docs/postman/sending-api-requests/authorization.md, src/pages/docs/postman/sending-api-requests/generate-code-snippets.md, src/pages/docs/postman/workspaces/creating-workspaces.md, src/pages/docs/postman/workspaces/using-workspaces.md
This fixes #2277 
— updated 404 and 301 links to case studies
— added in links to new case studies
— added right sidebar to page where it was missing.
=> [2277] updated case study URLs, and added new ones

legacy-documentation/v5/postman/collection_runs/integration_with_jenkins.md, src/pages/docs/postman/collection-runs/integration-with-jenkins.md
closes #1985 
- Replaces --exitCode with --supress-exit-code
- Adds missing run keyword to the example
Shown below:
=> V3 migration for `exitCode` option

src/pages/docs/postman/variables-and-environments/variables-list.md, src/pages/docs/postman/variables-and-environments/variables.md
There's a few github issues/topics on discourse (https://github.com/postmanlabs/postman-app-support/issues/7868#issuecomment-608340391, https://github.com/postmanlabs/postman-app-support/issues/886, https://community.postman.com/t/using-dynamic-variable-values-in-tests/959) around being able to use dynamic variables from the pre-request or test scripts so I thought we could add that as a note to the docs to make it clearer.
=> added precision for dynamic variables

src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md
So... I know I've asked before whether this should be in the docs but this isn't quite a bootcamp lesson (can't be triggered from there, and its purpose is to show features rather than teach a skill) therefore I added a little note about the tour at the top of the api worflow page. Hope that works. 😬
=> Added info for api builder tour

src/pages/docs/postman/monitors/intro-monitors.md, src/pages/docs/postman/monitors/setting-up-monitor.md, src/pages/docs/postman/monitors/viewing-monitor-results.md
This PR includes the revamped "Viewing monitor results" page (basically entirely rewritten). I moved the "Monitor dashboard" section to that page as I felt it made more sense to lead with that. I also updated for branded terms (see confluence). Lastly, noticed I had previously used "re-run" instead of "rerun" in "Setting up a monitor", so I fixed that.
Oh and my first gif! (let me know if it looks good, I couldn't get the 1px border to work @SueSmith)
@ArjunSingh-PM let me know if I'm missing anything or what pieces could be better worded, was working off of the notes from syncs we had a bit ago.
=> Viewing monitor results

src/pages/docs/postman/collection-runs/command-line-integration-with-newman.md
The `--data` option doesn't exist (newman --version : 4.5.7)
```bash
$ newman run mycollection.json --data data.json
error: unknown option '--data'
```
Works well with `--iteration-data` as specified in the help of newman :
```
$ newman run --help |grep "data file"
-d, --iteration-data <path>     Specify a data file to use for iterations (either json or csv).
```
=> Update : Options --data [file] & --no-color + tips on --suppress-exit-code for CI/CD

src/pages/concepts.jsx
Fix #2374 
Fix some card components which display wrong 'no of items' in subheading .
1 . 
2. 
3.
=> Fix #2374 , Fix 'no of items' display in cards.

src/pages/docs/postman/collection-runs/using-environments-in-collection-runs.md, src/pages/docs/postman/collections/creating-collections.md, src/pages/docs/postman/collections/intro-to-collections.md, src/pages/docs/postman/collections/managing-collections.md, src/pages/docs/postman/scripts/test-scripts.md
We have a new Ping Identity case study. I added it to the right sidebar on some pages that are relevant to the topics in case study.
=> adding new contextual Ping Identity links to right sidebar

src/components/CookieAlert.jsx
_Branched from `develop`_, this changes the label on the button for the cookie consent alert to "Close".
=> [2394] consent button label; Close

CONTRIBUTING.md
@ch264 made a couple of minor edits here to hopefully avoid people including `package-lock` file changes when they make content prs (mainly running `npm install` while they're still on `develop` branch, then creating their own branch - hopefully should allow people to run the site locally without editing / committing `package-lock` on their branch..)
=> Alter contribution flow

src/components/CookieAlert.jsx
This fixes a cookie alert bug.
To recreate:
If you open the site in an incognito window, the CookieAlert will pop up. Inspect the Alert box and you can see the CookieDiv in the dom. When you click 'Close' this will remove the CookieDiv from the page.
The issue is when you refresh / continue to browse. The CookieDiv gets rendered and then the CookieConsent component checks for cookies, detects the cookie and doesn't render itself. However, the CookieDiv still gets rendered, preventing interaction with certain elements on the page.
This fix checks document.cookie and conditional renders the correct markup accordingly
=> Cookie consent rerender issue

src/pages/docs/postman/sending-api-requests/authorization.md
NTLM was spelled wrong and so was the anchor link, this caused the page not to jump to the section when clicking the link in the content list.
=> Fixed NTLM spelling and anchor link.

src/pages/docs/postman/launching-postman/installation-and-updates.md
From v7.25.1 onwards, minimum version of macOS supported is 10.10
=> Update minimum macOS version supported

src/utils/algolia.js
Re #2509 this adds headings as a searchable attribute in Algolia
I have just tested this out very briefly in the demo site I had used for the restructure but here's what I've got set up in my own test Algolia index:
* increased typo tolerance to five chars (fixes "fork" query issue)
* selected searchable attributes as follows - to rank title, headings among other detail
When I search in the **Browse** tab in Algolia I get better results (e.g. "console" returns troubleshooting page first and top five are all more relevant, "variables" returns dynamic and using variables / environments pages etc), however:
* I'm not seeing the same results in my live demo site which may be on account of me missing some part of the build process (ran out of time to continue investigating this 🙃), but am …
=> Search subheadings

src/pages/docs/designing-and-developing-your-api/the-api-workflow.md
Updating the docs as we're removing the limit of the number of APIs you can create and share with the free plan.
=> Removed limit on free plan for APIs

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/setting-up-monitor.md, src/pages/docs/designing-and-developing-your-api/monitoring-your-api/using-static-IPs-to-monitor.md
Updated static IP page for new feature (automatically enabled static IPs for business and enterprise teams). 
Note that:
- #creating-a-new-monitor-to-run-from-a-static-ip-address shows the feature live in Artemis
- #changing-an-existing-monitor-to-run-from-a-static-ip-address will need to be updated once the feature is available in the dashboard
=> Updated Static IP 

src/pages/docs/sending-requests/authorization.md
@claireriley this is actually in 7.35 although it's temporarily been disabled so won't be relevant until 7.35 is available for installation again 😅
=> Shareable OAuth tokens

src/pages/docs/administration/team-merge.md
Fixes #2705 
edited file _docs/administration/team-merge.md_
added a slash to the link: `docs/designing-and-developing-your-api/mocking-data/setting-up-mock/`
contact Postman Support changed to `https://www.postman.com/support/`
@ch264 please review this
=> resolve error 404 in team-merge.md

src/pages/docs/administration/onboarding-checklist.md
correct link for 'Security and Compliance: A Shared Responsibility Model' is https://www.postman.com/security/shared-responsibility/ 
fixes #2694
=> fixes #2694 correct link to shared responsibility

src/components/Footer/Footer.jsx
Changed 2020 --> 2021 in global footer.
=> updated year in global footer

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors.md
Navigating to usage dashboard, it is quite hard to find "View detailed monitoring usage" so included additional information for more clarity. 
Also, monitoring usage page does not provide a breakdown of requests made by each monitor, so removed this part.
=> updated monitor usage doc

src/pages/docs/publishing-your-api/add-templates.md
Fixes: #2770 
This PR fixes the broken Enable Profile image link specified in the issue.
Please review it and suggest the changes required
=> Fix Enable Profile image link

src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
The data parameter used in pm.visualizer.set is a JSON object. Since the documentation mentions object, it could make the user feel that it is a Javascript object and they would try to pass other types of Javascript objects to it eg. functions which a JSON object does not accept. Hence the change.
=> Specify data parameter used while scripting in visualizations is a JSON object

src/pages/docs/sending-requests/capturing-request-data/interceptor.md
I was downloading the postman interceptor addon and the current link sends you to the third "support" tab in Chrome webstore. I feel it should send you to the main "overview" tab instead.
=> Fixed typo in URL for chrome interceptor extension

package.json
Removed babel-preset-gatsby, iddentity-obj-proxy, prettier and react-test-renderer from devDependencies in package.json. Ran develop and everything looks good. Warnings no longer show on CLI.
Anything listed under dependencies will always download regardless or production/develop and anything in devDependencies will install additionally specific to the develop environment.
=> [WEBSITES-1586] Update devDependencies to remove duplicated packages

src/pages/docs/sending-requests/certificates.md
Fixes #2858 
Updated echo links to be inline code (they are referenced as code in this case), and added call to action link to Postman Echo Collection to keep connection.
=> Updated echo links

src/components/ContextualLinks/ContextualLinks.scss
Added spacing to right sidebar to make the subtitle more readable.
=> added spacing to sidebar subtitles

src/pages/docs/collaborating-in-postman/version-control-for-collections.md
Reverts postmanlabs/postman-docs#2904
Since the feature release is blocked due to a product issue, reverting it back.
=> Revert "PR watching"

src/pages/docs/sending-requests/authorization.md
Updating the OAuth 2.0 callback URL with the new URL `https://oauth.pstmn.io/v1/browser-callback` due to the old callback URL being deprecated.
=> Updating OAuth 2 Callback URL

src/pages/docs/running-collections/using-newman-cli/newman-with-docker.md
The API link currently points to www.postman.com instead of api.getpostman.com
=> Correct Link to API

src/components/Header/Header.jsx
This fixes the on click bug we are coming across for mobile browsers. I added a conditional to check the search box output and to update state only if theres input.
We are using the react-onclickout package so that when a user clicks outside of the search box, the menu will disappear. The bug only appears on mobile browsers and doesn't appear on web.
=> LC Bug: Update conditional for onClickOut function for mobile browsers

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/integrations-for-alerts.md, src/pages/docs/integrations/available-integrations/keen.md
- adjusted the spelling of "worksapce" to read as "workspace"
- adjusted "Github" to read as "GitHub"
Resolves: fix/small-spelling-fix
=> Small Spelling Fix

gatsby-browser.js
This forces the window to the top of page on load, resolving the bug described in MARKENG-88.  (Was able to recreate).
I spent some time researching.. This appeared as a bug in Gatsby issue in 2018 and was resolved, but people still encounter from time to time, which has led people to suspect that it is the way Gatsby interacts with page CSS, specifically on the body tag. Only thing is the CSS fix wouldn't apply to our app? Thinking the bug isn't necessarily on our side, or on Gatsby's side, but with the way the two are interacting. Will need a little more investigation but this fixes the immediate problem.
Useful links:
https://stackoverflow.com/questions/55336831/how-to-fix-gatsby-js-link-component-retaining-scroll-position-and-not-resetting …
=> [MARKENG-88] Forces window to top of page, when switching between routes.

src/pages/index.jsx
Update the "Intro To Postman" YouTube embed URL, fixes broken embed.
Currently:
Fixed
=> Update Intro To Postman YouTube Embed URL, fixes broken embed

gatsby-browser.js
This updates the double clicking anchor issues for links under /contents/
=> [MARKENG-156] Remove scrollTo function in gatsby-browser to fix double click anchor bug

gatsby-config.js
This updates the starting URL for the manifest file to be absolute instead of relative. (This is the URL people's homescreen app icons are set to—should they add LC to their homepscreen.)
=> updated start URL for manifest file

gatsby-config.js
This reverts the start)url change back to using the root. See Chrome console WARN:
=> remove URL and use root for manifest file

legacy-documentation/v5/managing_collections/creating_documentation.md, legacy-documentation/v5/postman/api_documentation/how_to_document_using_markdown.md, legacy-documentation/v5/postman/api_documentation/publishing_public_docs.md, legacy-documentation/v5/postman/collections/using_markdown_for_descriptions.md, legacy-documentation/v5/postman/mock_servers.md, legacy-documentation/v5/postman/mock_servers/mock_with_api.md, legacy-documentation/v5/postman/monitors/intro_monitors.md, legacy-documentation/v5/reference/index.md, src/pages/docs/collaborating-in-postman/commenting-on-collections.md, src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md, src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md, src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md, src/pages/docs/getting-started/creating-the-first-collection.md, src/pages/docs/publishing-your-api/authoring-your-documentation.md, src/pages/docs/publishing-your-api/publishing-your-docs.md, src/pages/docs/sending-requests/intro-to-collections.md, src/pages/docs/sending-requests/visualizer.md, src/pages/docs/writing-scripts/test-scripts.md
Greetings team,
as requested by @tristandenyer on issue #3023 Kindly find the proposed changes to the docs
The second commit seeks to get some clarification on how to edit (remove) the links returning a 404
Issue #3023: Update all documenter.getpostman.com links to use new domain
=> update links to use new domain

CONTRIBUTING.md, legacy-documentation/v5/postman/scripts/postman_sandbox_api_reference.md, legacy-documentation/v5/pro/integrations/microsoft_flow.md, src/pages/docs/sending-requests/capturing-request-data/proxy.md
* fixed console WARN by declaring language w/ prism on /docs/sending-requests/capturing-request-data/proxy/ (bottom code block)
* ...which corrected the first code block (below) that was truncating the first line (thinking it was language)
* updated other code blocks missing language
* updated CONTRIBUTING.md to explain usage of code blocks and Prism
Before:
After:
=> [MARKENG-155] fixed console WARN by declaring language w/ prism

src/pages/docs/getting-started/installation-and-updates.md
We had an old notice that the web version was in beta, and it's not anymore.
=> Remove beta notice for web

src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md, src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md, src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md, src/pages/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors.md, src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md, src/pages/docs/publishing-your-api/authoring-your-documentation.md, src/pages/docs/publishing-your-api/custom-doc-domains.md, src/pages/docs/publishing-your-api/documenting-your-api.md, src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md, src/pages/docs/publishing-your-api/viewing-documentation.md, src/pages/docs/running-collections/using-newman-cli/continuous-integration.md, src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md, src/pages/docs/running-collections/using-newman-cli/integration-with-travis.md, src/pages/docs/sending-requests/authorization.md, src/pages/docs/sending-requests/examples.md, src/pages/docs/sending-requests/generate-code-snippets.md, src/pages/docs/sending-requests/intro-to-collections.md, src/pages/docs/writing-scripts/intro-to-scripts.md, src/pages/docs/writing-scripts/test-scripts.md
Updated URLs to case studies.  Current URLs cause a redirect on our marketing page.  These new urls avoid redirects.
=> MARKENG-230 - Update case study url, fixes redirect

src/pages/docs/integrations/available-integrations/new-relic.md
=> [GH-3073] fixed broken image link

src/pages/index.jsx
learning.postman.com/#upcoming-postman-livestreams would deeplink to the section at the bottom. Fixes #3069.
=> [GH-3069] added ID to header for anchorllinking

src/pages/docs/integrations/webhooks.md, src/pages/docs/publishing-your-api/publishing-your-docs.md, src/pages/docs/sending-requests/supported-api-frameworks/graphql.md, src/pages/docs/sending-requests/visualizer.md, src/pages/index.jsx
* added updated `allow` attributes to youtube embeds
* added `-nocookie` to embed URLs to fix white screen of death in youtube iframes. (YouTube embeds were not showing videos and request was being "stalled" in Network tab.)
=> Video embed nocookies

src/pages/docs/sending-requests/supported-api-frameworks/websocket.md
Two links in the WebSocket doc don't have a trailing slash, so they hit a redirect.
=> Fix redirected links

package.json
We only want to use NR in production so I've updated the build and build:beta commands in our scripts. This also removes the log for a missing GATSBY_NEWRELIC_ENV environment during build.
=> Fixed build error for GATSBY_NEWRELIC_ENV env variable

src/pages/docs/getting-started/introduction.md
**Remove shortened URLs #3115** 
In src/pages/docs/getting-started/introduction.md there are two links to bit.ly URLs. Change those to the actual URLs.
Replace three bit.ly links in src/pages/docs/getting-started/introduction.md with urls
=> #3115 replaced three bit.ly urls in introduction.md with full urls

src/pages/docs/integrations/available-integrations/gitlab.md
https://gitlab.com/-/profile/personal_access_tokens, missing hyphen after domain leads to 404 error page.
=> Edited the access token URL

src/components/Header/Header.jsx, src/pages/docs/getting-started/installation-and-updates.md, src/pages/docs/getting-started/postman-account.md, src/pages/docs/getting-started/syncing.md
Fixes #3141
Updated the `go.postman.co/build` HREFs to `go.postman.co/home`
=> Updated `go.postman` links

src/pages/docs/getting-started/settings.md, src/pages/docs/running-collections/intro-to-collection-runs.md, src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md, src/pages/docs/running-collections/using-newman-cli/continuous-integration.md, src/pages/docs/running-collections/using-newman-cli/integration-with-jenkins.md, src/pages/docs/running-collections/using-newman-cli/integration-with-travis.md, src/pages/docs/running-collections/using-newman-cli/newman-with-docker.md, src/pages/docs/running-collections/working-with-data-files.md, src/pages/docs/writing-scripts/script-references/test-examples.md
* macOS
* command-line hyphenated when used as an adjective
* some other minor edits
=> Style guide edits

src/pages/docs/sending-requests/intro-to-collections.md
Added the heading so https://learning.postman.com/docs/sending-requests/intro-to-collections/#recovering-deleted-collections works. (This is due to a link in the pricing page)
This involved reordering the Managing section a bit. I also made some minor style edits while I was there.
=> TW-66 added heading for recovering collections

README.md, src/pages/docs/administration/sso/microsoft-adfs.md, src/pages/docs/administration/upgrading-to-v8.md, src/pages/docs/api-security/security-warnings.md, src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md, src/pages/docs/sending-requests/cookies.md, src/pages/docs/sending-requests/managing-environments.md, src/pages/docs/sending-requests/supported-api-frameworks/making-soap-requests.md, src/pages/docs/sending-requests/variables.md
Every fenced code block should have a language after the three backticks. It causes a warning on build otherwise.
=> Add language to every fenced code block

package.json, redirects.json, src/pages/docs/administration/managing-your-team/managing-your-team.md, src/pages/docs/administration/sso/saml-okta.md, src/pages/docs/administration/team-merge.md, src/pages/docs/administration/team-settings.md, src/pages/docs/administration/upgrading-to-v8.md, src/pages/docs/collaborating-in-postman/public-workspaces.md, src/pages/docs/collaborating-in-postman/version-control-for-collections.md, src/pages/docs/designing-and-developing-your-api/monitoring-your-api/setting-up-monitor.md, src/pages/docs/designing-and-developing-your-api/the-api-workflow.md, src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md, src/pages/docs/getting-started/importing-and-exporting-data.md, src/pages/docs/getting-started/using-scratch-pad.md, src/pages/docs/integrations/available-integrations/statuspage.md, src/pages/docs/publishing-your-api/publishing-your-docs.md, src/pages/docs/sending-requests/capturing-request-data/proxy.md, src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
* i (temporarily) installed the https://www.gatsbyjs.com/plugins/gatsby-remark-check-links/ plugin to find broken links.
* it came back with a redirect chain and anchor links that have rotted away.
* I fixed the LONG redirect chain
* I updated all anchor links (some required reassigning to other / new page topics for them)
=> removed redirect chaining and updated anchor links

gatsby-config.js, package-lock.json, package.json
added gatsby-plugin-catch-links to keep page from reloading to top when cookie notice is closed.
When you click on the cookie notice, the page jumps to the top.
With this plugin, it appears to keep that from happening by treating it as a React / SPA type link.
**Reproduce issue:**
* open https://learning.postman.com/
* ensure the cookie notice is visible (otherwise clear Application data in Inspect toolbar)
* scroll down page
* close cookie notice
* note that the page scrolls to top
**Acceptance criteria with this plugin:**
* build app as production (gatsby clean, gatsby build, gatsby serve)
* ensure the cookie notice is visible (otherwise clear Application data in Inspect toolbar)
* scroll down page
* close cookie notice
* note that the page does NOT scroll to top
I also noticed that …
=> added gatsby-plugin-catch-links plugin

src/pages/index.jsx
**Ticket/Issue:**
MARKENG-263
_Branched from `develop`_, this implements a CSS-based (JS minimal) solution to suppress expired events.
Why make these changes?
RE: the reported “link offset issue”, the culprit is runtime date logic (expiration). By eliminating runtime date evaluation logic & using CSS to suppress expired events, we can avoid the link offset suppression issue.
link offset suppression issue (JS-based)
*It’s a private video; use your postman email address to log-in to Youtube, to see it:
https://youtu.be/XQsHt9aU2ls
=> [MARKENG-263] home events, css-based event expiration; avoid link offset issue

package.json
**Ticket/Issue:**
MARKENG-378
**Root Cause**
We use the engines:node entry in the package directory to denote the version of NodeJS to use when running the app. The version specified in `postman-docs` (_12.11.0_) is behind compared to the version in `postman-marketing-website-www` (_12.13.0_).
**Solution Description**
_Branched from `develop`_, this bumps the node version in the package file.
*no visuals
=> [MARKENG-378][c] bump node version in package to 12.13.0

package.json
Revert the GDPR plugin back down to `1.0.7`
Branched out of MASTER to avoid getting any changes sitting in DEVELOP
=> HOTFIX - revert gdpr cookies plugin down to 1.0.7

.gitignore, package.json
**Root Cause**
If you are using the wrong version of node, when you run the app or install dependencies, errors may occur.
**Solution Description**
_Branched from `develop`_, this adds an npm script to easily install & run the correct version of NodeJS w/ `npm run build:nvmrc; nvm install`; similar to postman-marketing-website-www
=> [MARKENG][c] npm run build:nvmrc

gatsby-config.js, package-lock.json, package.json, src/pages/docs/getting-started/importing-and-exporting-data.md
**REVIEW, BUT HOLD ON MERGE.**
This package was added previously and tested out, cleaned up links, then removed.
Adding in now to test it out through build and deployment.
* added package
* added to gatsby config (no options)
* addressed and fixed one broken link (anchor tag). All links should be clean going into this.
To test locally:
1. pull down
2. npm i
3. npm run build (should run clean in terminal)
break a link URL or anchor tag, and rerun. (should see WARN and ERR in terminal, showcasing link you broke)
=> [MARKENG-388] added gatsby package for link checker on build

gatsby-config.js, package-lock.json, package.json
fixes #3223 
* removed from package.json
* removed from gatsby config file
* `npm i` to gen up new package-lock.json
=> [GH-3223] removed 'gatsby-plugin-catch-links' plugin; update package-lock

src/pages/docs/writing-scripts/script-references/variables-list.md
Addresses the following customer-raised issue which was raised on GitHub:
https://github.com/postmanlabs/postman-app-support/issues/10168
Customer determined that the range of `$randomInt` is actually different to the listed range (0-1000 rather than 1-1000).
I also observed that `$randomPrice` is using a specified range, and by testing this I found that the range was also different to that listed.
Validated behaviour via the following pre-request script:
```
numbers = [];
for (i = 1; i < 10000; i++) {
numbers.push(pm.variables.replaceIn('{{$randomInt}}'));
}
numbers.sort((function(a, b){return a-b}));
console.log("Numbers range from " + numbers[0] + " to " + numbers[numbers.length-1]);
prices = []
for (i = 1; i < 100000; i++) {
prices.push(pm.variables.replaceIn('{{$randomPrice}}'));
} …
```
=> Correct the documented range of randomInt and randomPrice

package-lock.json, package.json
* running `npm i` then `npm run build` no longer shows dep WARN in terminal
* * web app builds and runs as expected—no changes should be noticeable on front-end
=> [MARKENG-449] installed typescript package to clear dep WARN

src/pages/docs/administration/team-merge.md, src/pages/docs/collaborating-in-postman/collaboration-intro.md, src/pages/docs/getting-started/introduction.md, src/pages/docs/getting-started/postman-account.md
As we're moving the public roadmap from Trello to GitHub, I'm trying to find all of the links that need updating, including these ones. Feel free to double-check if I've missed any!
=> [MARKENG-478][c] update links to public roadmap

src/pages/docs/collaborating-in-postman/public-workspaces.md, src/pages/docs/integrations/available-integrations/aws-api-gateway.md, src/pages/docs/integrations/available-integrations/slack.md, src/pages/docs/integrations/intro-integrations.md, src/pages/docs/integrations/webhooks.md
There shouldn't be links to postman.postman.com - use go.postman.com instead.
=> [TW-143] Remove postman.postman.com links and use go.postman.co

redirects.json, src/pages/docs/collaborating-in-postman/version-control-for-collections.md, src/pages/docs/designing-and-developing-your-api/creating-an-api.md, src/pages/docs/designing-and-developing-your-api/defining-an-api.md, src/pages/docs/designing-and-developing-your-api/developing-an-api.md, src/pages/docs/designing-and-developing-your-api/managing-apis.md, src/pages/docs/designing-and-developing-your-api/observing-an-api.md, src/pages/docs/designing-and-developing-your-api/testing-an-api.md, src/pages/docs/designing-and-developing-your-api/the-api-workflow.md, src/pages/docs/designing-and-developing-your-api/versioning-an-api.md, src/pages/docs/designing-and-developing-your-api/watching-an-api.md, src/pages/docs/integrations/available-integrations/github.md, src/pages/docs/publishing-your-api/documenting-your-api.md
* Move https://learning.postman.com/docs/collaborating-in-postman/versioning-an-api/ to be under /docs/designing-and-developing-your-api
* Adjust order so it's after Creating APIs
* Edit https://learning.postman-beta.com/docs/designing-and-developing-your-api/the-api-workflow/ to refer to this task and link correctly. (Move the link out of the next steps list)
* Fix all other internal links
* Add a redirect
=> [TW-131] Move API versioning page

src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
Not all business plans [have access to reporting](https://www.postman.com/pricing/), but older business plans do. This update is intended to reflect the current state.
=> Clarify API reports availability between plans

src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md
escape '|' character otherwise the text will be influenced incorrectly
if '|' character occurs in a markdown table, (I guess) it will make the text display incorrectly
Let me show the text before and after this change
=> escape '|' character

src/pages/index.jsx
The events include live streams + webinars so changing it to upcoming events instead.
I haven't switched the id on purpose this time, because #upcoming-livestreams is used on the app release notes. I will switch that whenever a new build goes out for a new version or later in a separate PR.
=> Rename the Upcoming Livestreams section to Upcoming Events

src/components/ContextualLinks/ContextualLinks.scss, src/components/Header/Header.scss, src/components/layout.scss, src/templates/doc.jsx, src/templates/doc.scss
* removed blur from primary navbar
* added border to second navbar
* removed thin white space on far left (.container-fluid needed overrides)
* refactored how we do spacing around docs and right sidebar
* added HR on sm breakpoint between docs and right sidebar
* adjusted padding for all breakpoints to allow for better content viewing.
=> updated grid layout for smaller breakpoints; fixed navbar styling

src/components/Header/Header.jsx, src/components/Header/Header.scss
Added a work around for `backdrop-blur` incompatibility with firefox.
=> [MARKENG-686] [c] Added in Firefox backdrop-blur workaround

src/components/LeftNav/LeftNav.scss
Removing the dark highlight from left nav second levels
- fixed up the padding between parents of open drawers in left nav
=> updated left nav styles to fix seceond level highlight

src/templates/doc.scss
Markdown applies a <p> to contents in an LI that has an indented UL below it. Targeting the li > p left an odd space to the left, so had to revert how we do bullets for these.
BEFORE
AFTE
R
=> [MARKENG-719] updated LI bullets to accept p tag inside li

package-lock.json
Ran locally, Docs working as expected. Running "npm run dev" no longer shows the warning message.
.
=> [MARKENG-625] Updated caniuse-lite to synchronize version across different tools

package-lock.json, package.json
1. This clears the moderate warnings around Jest when running npm audit. To test, run gatsby clean; npm i; npm run test.
Before
After
2. Webpack is required to run Gatsby services after jest upgrade; similar to WWW.
All functionalities still work (Nav / Fixed scrolling etc). zero console errors related to webpack.
3. Logs were showing a missing New Relic ENV so I added it to our build script. 
==============================================================
Version v27.0.0 requires different settings and breaks the test after installation. 
Upgrading to Version 27 will be completed in a separate ticket followed my updated tests for components.
=> [MARKENG-395] Updated Jest v26.0 and Webpack  / fixed New Relic warning on build

src/pages/docs/administration/managing-enterprise-deployment.md, src/pages/docs/api-security/token-scanner.md, src/pages/docs/collaborating-in-postman/adding-private-network.md, src/pages/docs/designing-and-developing-your-api/deploying-an-api.md, src/pages/docs/designing-and-developing-your-api/the-api-workflow.md, src/pages/docs/designing-and-developing-your-api/versioning-an-api.md, src/pages/docs/getting-started/navigating-postman.md, src/pages/docs/integrations/ci-integrations.md
Adds new batch of devrel blogs to docs sidebar
This PR covers issues:
#3496
#3471
#3450
#3467
#3453
#3452
#3419 
Note: there are a series of blogs titled "The New Postman API Platform: (insert phrase here)". It seemed a bit too wordy to me for users to scan through (see attached), so I cut off the first part of the title in the text.
=> Add devrel content batch 3

src/components/layout.scss, src/templates/doc.scss
- updated the inline <code> to match styles in Sandbox (see screesnhot)
- update <p> tag line-height to match styles in Sandbox
=> updated inline code block styles + line-height for <p>

src/templates/doc.scss
Removes this hover state on linked images, while retaining the bottom-border on inline links.
=> [MARKENG-723] removed hover state from linked images

src/templates/doc.scss
in the effort to remove all the pasted in symbols and non-alpha and non-numeric values, changing ✦ to use CSS code value in CSS
=> update ✦ to use CSS code value

gatsby-config.js, package-lock.json, package.json
* in support of #3522 
* removes Gatsby package
* removes two additional requests to polyfil in network tab
BEFORE:
AFTER:
=> removed polyfil plugin in favor of loading specific features of polyfil

src/components/LeftNav/LeftNav.jsx, src/components/LeftNav/LeftNav.scss, src/templates/doc.jsx, src/templates/doc.scss
- left nav styles updated to improve spacing between items
- docs grid layout improved to better support xl screens (see screens below)
- fixed spacing between caret and label to now be linked
- added cursor pointer to caret
=> updated left nav styles, and docs layout for xl screens

src/pages/docs/collaborating-in-postman/collaboration-intro.md
the link https://assets.postman.com/postman-docs/Screen%20Shot%202019-11-11%20at%205.38.16%20PM.png was missing a %20 which meant its was being rendered as text rather than an image.
=> update link to include missing %20 so the image renders

bff.js, src/pages/404.jsx
_Branched from `develop`_, this embeds code (at build time) to eliminate a possible race condition, seen w/ some clients (Newrelic), do to timing on loading the page versus loading & parsing the SDK.
The is the second step; first step was safe-gurading pmt-tech functions, to eliminate q potential race condition, seen (a small amount) for some browsers, on the NewRelic dashboad.
_*no visual (regressive)_
=> [MARKENG-957][c] eliminate potential race condition for load events with pm-tech

package-lock.json, package.json
* saw `npm WARN gatsby-transformer-remark@4.11.0 requires a peer of gatsby@^3.0.0-next.0 but none is installed. You must install peer dependencies yourself.` in terminal
* downgraded plugin to match gatsby v2.x we are using to clear WARN
=> downgrading gatsby-transformer-remark to match gatsby version

package-lock.json, package.json
_Branched from `develop`_, this specifies an isolated version (v2.12.69) of gatsby-cli in the package json file.
In recent weeks, there has been a console error, when doing npm run dev, tied to the micromark-extension-mdxjs package. It was determined to be a dependency brought in by gatsby-cli.
Before:
=> [MARKENG-980][c] newer gatsby-cli is causing console error; this specifies an older version, but latest patch possible

src/components/ContextualLinks/ContextualLinks.jsx, src/components/CookieAlert.jsx, src/components/Footer/Footer.jsx, src/components/Header/Header.jsx, src/components/Hellobar.jsx, src/components/Shared/EditDoc.jsx, src/components/__snapshots__/CookieAlert.spec.jsx.snap, src/pages/auto-flex-policy.jsx, src/pages/index.jsx
* removing `noreferrer` from Postman properties
* fixing up interlinkning strategy for all target="_blank" to adhere to latest ruleset
* assigning the 'home' link to go to the main intro doc page instead of the homepage/root.
* ran tests and rebuilt spec
=> updated interlinking strategy for target="_blank"

src/pages/docs/administration/audit-logs.md, src/pages/docs/administration/billing.md, src/pages/docs/administration/buying.md, src/pages/docs/administration/managing-enterprise-deployment.md, src/pages/docs/administration/managing-your-team/managing-your-team.md, src/pages/docs/administration/onboarding-checklist.md, src/pages/docs/administration/sso/admin-sso.md, src/pages/docs/administration/sso/intro-sso.md, src/pages/docs/administration/sso/user-sso.md, src/pages/docs/administration/team-merge.md, src/pages/docs/administration/team-settings.md, src/pages/docs/api-security/token-scanner.md, src/pages/docs/collaborating-in-postman/adding-private-network.md, src/pages/docs/collaborating-in-postman/collaboration-intro.md, src/pages/docs/collaborating-in-postman/public-workspaces.md, src/pages/docs/collaborating-in-postman/roles-and-permissions.md, src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md, src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md, src/pages/docs/collaborating-in-postman/version-control-for-collections.md, src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md, src/pages/docs/getting-started/postman-account.md, src/pages/docs/integrations/available-integrations/github.md, src/pages/docs/integrations/available-integrations/keen.md, src/pages/docs/monitoring-your-api/faqs-monitors.md, src/pages/docs/monitoring-your-api/intro-monitors.md, src/pages/docs/monitoring-your-api/setting-up-monitor.md, src/pages/docs/monitoring-your-api/using-static-IPs-to-monitor.md, src/pages/docs/publishing-your-api/custom-doc-domains.md, src/pages/docs/sending-requests/intro-to-collections.md
This PR updates plan names and screenshots in the docs for the dec 1st plan/pricing change.
Summary of changes:
```
Free -> Free, no changes
Team -> Basic, no pricing or feature changes
Business -> Professional, price change but no feature change
Enterprise -> Enterprise, price change and optional control over app version (must be requested, not an external feature)
```
=> Update for plan changes dec 1

CONTRIBUTING.md, README.md
Updated READMEs to instruct contributors to use Node v14.15.0.
This is required by the latest Gatsby v4 (we just updated from Gatsby v2).
=> updated to reflect node v14.15.0

gatsby-browser.js, gatsby-config.js, styles/config/print.css
* added basic print stylesheet
* hid everything but the main doc / content area
* made images 50% page-width to save space and retain readability.
* converted text to full black and backgrounds to full white to save ink
* excluded it from purge CSS plugin
* cmd-p / cntrl-p to see print dialog and print example.
=> [MARKENG-1077] added print stylesheet

.eslintrc.js, gatsby-node.js, gatsby-ssr.js, package-lock.json, package.json, src/components/Hellobar.jsx, src/components/LeftNav/LeftNavItems.jsx
Packages installed due to new ESLint and @babel/eslint-parser
- https://www.npmjs.com/package/@babel/eslint-parser
- https://www.npmjs.com/package/eslint
- https://babeljs.io/docs/en/babel-preset-react
`babel-eslint `has been deprecated. I updated the `ESLint` versionand switched `babel-eslint `to the recommended `@babel/eslint-parser` package, which requires `babel-preset-react` for our scripts to work correctly.
Verify and test locally with `npm run test:lint` to visually list errors and `npm run test:lint-fix` to automatically fix errors if applicable.
=> Updated ESLint with updated babel/eslint-parser package

src/assets/icons/solution.svg, src/pages/index.jsx
Hey there! 👋 
The [Postman Answers public workspace](https://www.postman.com/postman/workspace/postman-answers) is pretty popular so we wanted to highlight it on the LC too, I've currently added it at the bottom of the homepage but if you can think of specific pages where it would make sense to highlight it, or to plug some specific collections I'm happy to add it there too. 
Also this creates a new line of icons at the bottom which I didn't feel was a problem, but happy to work on it and make them all fit on one line (if possible) when on full screen. 👍
=> Added link to Postman Answers on homepage

gatsby-browser.js, src/components/LeftNav/LeftNav.jsx, src/templates/doc.jsx
- Created Class component for LeftNav to use state
- Broke out the sectionHandler() and renderTwoLevelList() functions outside of class component
- Why? Calling the functions inside the render causes the component to completely re-render when a user clicks on a link
- Updated test due to capitalization on L and l for leftNavLinks
New behavior:
- No flickering up and down when user clicks link
- Side nav maintains active link
- Navigating between sub menus is much cleaner 
For visual, compare current side nav versus this branch locally.
=> Refactored Left Nav to reduce flicker and maintain structure when navigating through pages

README.md, package.json
_Branched from `develop`_, this updates the README file to explain how to use `npm run nvmrc; nvm use` to ensure the correct version of node (& npm).
The web app has a convenience script, but the workflow is not documented anywhere. This update make the app more consistent with the other Postman web apps.
*no visuals; _regressive_
=> [MARKENG-1128] update with instructions for using `npm run nvmrc; nvm use`

src/components/layout.scss
Updated layout.scss and removed the @-moz-document rule causing the text to look very thin with high contrast.
=> Removed @-moz-document url-prefix() causing lighter text issues on Doc pages

src/pages/docs/sending-requests/variables.md
* switched mentions of 'string' to be 'default'
* uploaded new screenshots (as JPG and optimized.)
Screenshot of section with changes:
=> Switched 'string' to 'default'; updated screenshots

DOCS_STYLE_GUIDE.md, src/pages/docs/administration/managing-your-team/configuring-scim.md, src/pages/docs/administration/team-merge.md, src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md, src/pages/docs/getting-started/exploring-public-api-network.md, src/pages/docs/getting-started/postman-account.md, src/pages/docs/integrations/intro-integrations.md, src/pages/docs/monitoring-your-api/intro-monitors.md, src/pages/docs/monitoring-your-api/setting-up-monitor.md, src/pages/docs/running-collections/collection-webhooks.md, src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
* Converts absolute LC URLs to relative URLs: `https://learning.postman.com/docs/<rest of the URL>` becomes `/docs/<rest of the URL>`
=> TW-301 Convert absolute URLs to relative

src/pages/docs/getting-started/installation-and-updates.md
- Adds "Find and replace" to the list of limitations for the Postman web client
- Removes "Live preview" and "Saving responses to file" from the list of limitations for the Postman web client (both options are available on web now)
- General copyedits
=> TW-295 Add Find and replace to /getting-started/installation-and-updates/#web-limitations 

src/pages/docs/designing-and-developing-your-api/versioning-an-api.md, src/pages/docs/integrations/available-integrations/github.md, src/pages/docs/integrations/available-integrations/gitlab.md
This also covers GitLab self-managed.
=> TW-203 add that GitHub Enterprise requires a Postman Enterprise account

src/templates/doc.jsx
http://localhost:8000/docs/designing-and-developing-your-api/the-api-workflow/
https://learning.postman.com/docs/designing-and-developing-your-api/the-api-workflow/
This adds a p tag to the text element and allows it to render below an image instead of the side.
=> Update edge case bug for "Last modified" date

src/components/modules/BreadCrumbsLinks.jsx, src/components/modules/BreadCrumbsLinks.scss, src/templates/doc.jsx, src/templates/doc.scss
This adds Breadcrumbs functionality to Breadcrumbs docs
- Broke out component into /components/modules folder
- Uses LeftNavLinks as a single source of truth for our navigation links
- Keeps docs.jsx clean by separating the feature components 
- added a11y
- pmTech-ready
Ex: Home / Sending Requests / Supported API Frameworks
=> [MARKENG-1081] Breadcrumbs Navigation Links

src/pages/docs/collaborating-in-postman/collaboration-intro.md
* Removes the [Archiving section](https://learning.postman.com/docs/collaborating-in-postman/collaboration-intro/#how-archiving-works) based on information in WORKSPACES-2084 and confirmed by Preetham.
* Updates screenshots as needed and removes all PNG files
* Removes content covered sufficiently elsewhere (https://learning.postman.com/docs/collaborating-in-postman/collaboration-intro/#how-archiving-works and https://learning.postman.com/docs/collaborating-in-postman/collaboration-intro/#creating-a-new-workspace-from-the-menu) and adds links to those other pages 
* Reorganizes content, general copyedits
=> TW 206 Refresh collaboration intro

src/pages/docs/designing-and-developing-your-api/versioning-an-api.md, src/pages/docs/integrations/available-integrations/azure-devops.md
Added note that Azure on-prem integration requires an Enterprise plan:
/docs/designing-and-developing-your-api/versioning-an-api/
/docs/integrations/available-integrations/azure-devops/
=> [TW-314] Doc Azure on-prem git integration

gatsby-config.js, package-lock.json, package.json, src/components/Header/Header.jsx
1. To resolve external a links from scrolling after click, I installed https://www.gatsbyjs.com/plugins/gatsby-plugin-catch-links/
This will need to be tested in beta since localhost does not automatically scroll. I suspect the upgrade to Gatsby V4 could  be the reason as our other platforms don't have this scroll issue.
2. Cleared up SVG errors on homepage
=> [339] Resolve LC cookie notice scroll issue + clear errors on homepage

gatsby-config.js, package-lock.json, package.json
Removed gatsby-plugin-catch-links package. Issue for scroll top for One Trust cookie still remainds.
The issue is that locally, the page does not scroll to the top when compared to beta which does scroll. I suspect this could be coming from an update in Gatsby V4 as the issue does not persist on WWW which is on V2.
=> [MARKENG-339] Remove scroll packages; not working in develop / production

package-lock.json
Missing Gatsby package isn't in develop and causing develop build to break.
=> gatsby-react-router-scroll added back to develop

src/components/LeftNav/LeftNav.jsx, src/components/modules/PreviousAndNextLinks.jsx, src/pages/index.jsx
**Bug/Issue:** Previous and Next links are hitting a dead end when navigating between a second level folder above or below the section causing the UI to feel broken. Current logic does not support this case.
**Solution:** 
I updated the logic into two parts. The first part filters out the left nav data depending on window location. The second part checks which active  link the user is on then pushes items into an array based on index and availability [last item from previous section, current items in active section, first item in next section]
- Added React Hooks useState and useEffect. Cleaner imo.
**Expected functionality:**
- Adds the ability to navigate docs another level deeper using "Previous" or "Next" methods (mouseclick, arrow keys on web or swipe on mobile)
- Example: Designing …
=> [MARKENG-1212] Improved navigation for "Previous" and "Next" links for Docs 

src/components/Footer/Footer.data.json, src/components/MarketingPages/Line.scss, src/pages/docs/administration/onboarding-checklist.md, src/pages/docs/getting-started/syncing.md, src/pages/docs/monitoring-your-api/faqs-monitors.md
changelog:
- updated links to Security pages in docs to use new Trust Center 
- updated footer to use new Trust Center label and link
=> Updated footer links to point to new Trust Center; updated doc links for /security/ also

.github/workflows/deploy.yml, .github/workflows/prod-deploy.yml, gatsby-config.js
Right now, Beta's site map uses `postman.com` when it should be `postman-beta`.  This PR makes the config file grab  the URL from the env vars, which I added in GH secrets and set to beta and prod respectively./
=> Markeng 1227 - Point gatsby-config to use env vars when generating  site map url

src/pages/docs/collaborating-in-postman/version-control-for-collections.md, src/pages/docs/sending-requests/intro-to-collections.md
- Updates screenshots
- Reorganizes content 
- Reformats instructions into numbered lists
(Follow-up work is necessary for the [Resolving conflicts](https://learning.postman.com/docs/collaborating-in-postman/version-control-for-collections/#resolving-conflicts) section and to document the use of **Refresh**, new ticket is TW 371)
=> TW 245 Refresh  /collaborating-in-postman/version-control-for-collections

src/pages/docs/getting-started/installation-and-updates.md
Postman Linux application doesn't require any special privilege to launch the application on the Linux platform. The example shared on the installation docs might make users think that a sudo privilege is needed to run the postman application. The example mentioned should be very simple where the user generally ends up downloading the application and extract it inside the `Downloads` directory
=> Modify the installation docs to stop mentioning about any sudo privileges

src/pages/docs/getting-started/importing-and-exporting-data.md, src/pages/docs/getting-started/using-scratch-pad.md
* Updates instructions for exporting Scratch Pad data - since users are logged out, data dumps are downloaded directly rather than being emailed to them.
=> TW 386 Update instructions for Scratch Pad export

src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md
Incorrect URL present in the documentation, edited them to mocks as per the Postman API documentation here: https://documenter.getpostman.com/view/12959542/UV5XjJV8?&_ga=2.180632995.569170397.1646627375-2114194575.1644467674#296628ed-d49b-4206-b4a7-d622e693945c
=> Edited the Mock URL for Mock creation

src/pages/docs/integrations/available-integrations/github.md, src/pages/docs/integrations/intro-integrations.md, src/pages/docs/integrations/webhooks.md, src/pages/docs/sending-requests/cookies.md, src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md
Based on the precedent set in TW-306, I used `allowlist` as a drop-in replacement for `whitelist`. There's [one remaining instance](https://github.com/postmanlabs/postman-docs/compare/tw-84-allowlist?expand=1#diff-e9b299aa8f1d236d9686af8300c111cca1173b23f75a5cd9d64d741a006862c9R95) that reflects the term's use in the Postman UI.
=> TW 84 Use allowlist

src/components/modules/BreadCrumbsLinks.jsx, src/components/modules/BreadCrumbsLinks.scss, src/templates/doc.scss
* refactored how we build the breadcrumb to use <ol>, which is preferred for a11y to show hierarchy
* applying `aria-hidden` to separators to hide from screenreaders
* added `title` to "Home" link to explore how this affects the SEO preview card on LinkedIn (which currently prints "Home" instead of "Learning Center")
=> refactored Breadcrumbs to use <ol> making it more accessible and semantic

src/components/seo.jsx, src/pages/index.jsx
* added `twitter:description` and `og:description` to produce dynamic value prepending `${title}` of page to " : documentation for Postman, the collaboration platform for API development. Create better APIs—faster."
* improved `twitter:title` and `og:title` to now be dynamic, prepending `${title}` of page to "  | Postman Learning Center"
* this will improve SEO, as well preview cards' content on social media platforms in that they will pull the URL of the page shared, now have a description declared (of which LinkedIn Card Validator was issuing a warning about it missing). 
* Updated homepage title to be "Learning Center" instead of "Home"
Current:
See changes in Head for those listed above:
=> SEO.jsx component updates

src/pages/docs/administration/managing-your-team/user-groups.md, src/templates/doc.scss
* Adding support support for appending inline icons with `#icon` as a CSS hook to help style them to be more inline with text.
* updated one page's icon to show as an example.
=> added #icon to add CSS hook for inline icons

styles/config/print.css
* icons would blow up to block-level size on print 
* targeting #icon, we can now keep them inline and 18pt width
BEFORE:
AFTER:
=> Updated print.css styles to target #icon and keep them from becoming block-level

src/pages/docs/administration/billing.md
This PR:
- Adds Apple Pay and Google Pay to the [Paying by invoice](https://learning.postman.com/docs/administration/billing/#paying-by-invoice) section of the Billing page
- Reformats the [Paying by invoice](https://learning.postman.com/docs/administration/billing/#paying-by-invoice) section to make the note about only being available to Enterprise customers more prominent
=> TW 378 Add Apple Pay and Google Pay to Invoicing section

src/pages/docs/getting-started/troubleshooting-inapp.md
- Adds a link to https://status.postman.com/ from https://learning.postman.com/docs/getting-started/troubleshooting-inapp/
- Adds a new introduction and a note about the type of troubleshooting page this is
=> TW 424 Add link to status page

scripts/pm-vale-stats
To test, run `scripts/pm-vale-stats` from the repo root. It should look like this:
```
% scripts/pm-vale-stats
Running Vale... (this takes a minute)
Total wordcount: 22538
Error total:     1606
Error rate: 7.12%
```
=> TW-369 Vale reporting script

src/components/seo.jsx, src/pages/index.jsx
* using waterfaller.dev, we found that "polyfill.min.js is blocking the render of your page wasting 230ms"
* using same pattern as `math` script, I moved the polyfill script to bottom of page
* removed from SEO.jsx (head)
* will retest in https://waterfaller.dev/ when on BETA
=> moving polyfill script to bottom to keep from being a render-blocking file

scripts/fetchBlogPosts.js, scripts/fetchEvents.js, scripts/fetchPmTech.js
_Branched from `develop`_, this modifies the bff fetch scripts to pass an additional request header.
The url to fetch bff data is getting updated to support runtime requests. Access to the endpoint will need to be authorized for access. From node processes, auth will be achieved with this additional header.
*no-visuals (regressive)
=> [MARKENG-1338] additional header for node fetching of bff content

src/pages/index.jsx
* YouTube video now uses youtube.com instead of youtube-nocookie.com
* this will clear the new CORS errors coming from Google Play
=> revert YouTube video to not use `-nocookie` domain to clear CORS errors from Google

gatsby-node.js, src/components/seo.jsx, src/templates/doc.jsx
Issue: Add article:publisher and article:modified_time to meta for SEO
Added static article:publisher tag and an exec.sync command to grab the latest modified time that runs on build which appends the tags to the HTML head.
article:publisher
Modified Time
=> [MARKENG-1159] Added metatags for docs

scripts/qualtrics.js, scripts/useQualtrics.js, src/components/modules/loadQualtrics.jsx, src/components/seo.jsx, src/templates/doc.jsx
Adding Qualtrics script to Learning Center docs for content ranking survery.
I created an JSX element and a js file to load the qualtrics script on load. Qualtrics requires a css selector so I wrapped the parent with 'pm-qualtrics-embedded'.
=> [MARKENG-1408] Qualtrics added to LC

src/components/modules/Modal.js
* on hover, `e-remove` would show as the title
* changed title to be "Close"
=> changed 'e-remove' to 'Closed' on modal X button title

gatsby-node.js
This creates a new node to grab the length of all frontmatter from the md files.
I added two console logs you can enable / disable so you can view the query in the terminal. 
GraphQL query can be found under (http://localhost:8000/___graphql)
```
frontmatterLength {
value
}
```
Terminal (for testing)
GraphQL query
=> Created node for frontmatter character count of all md files 

src/pages/docs/designing-and-developing-your-api/deploying-an-api/deploying-an-api-aws.md, src/pages/docs/designing-and-developing-your-api/importing-an-api.md
Added IAM policy permissions needed for exporting or deploying an HTTP API schema from Postman to Amazon API Gateway
=> [TW-498] Add permissions to import or deploy AWS API

src/templates/doc.jsx
This clears up the [object object] text displaying when viewing the individual doc pages. Usually seen on slower connections.
=> [MARKENG-1550] Clear up object-object display for slow connections

CONTRIBUTING.md, README.md, package-lock.json, package.json
* npm install brought up a number of packages looking for `{"node":"^12.22.0 || ^14.17.0 || >=16.0.0"}`
* we are running `v14.10.0`
* `v14.17.1` is the LTS ("long-term support") version for v14
* I updated the package file, and all mentions of it in the docs
* checked that `npm run nvmrc; nvm use` works
* npm installed and notice all WARN fo incompatible Node versions were gone 
* npm run dev ran clean from a UI perspective (need more eyes on this, especially around any other features and packages relying on Node.)
=> Updating Node to 14.17.1 to support npm packages

src/pages/docs/writing-scripts/script-references/test-examples.md
In the Test script examples topic, fixing broken anchor link in TOC and other updates. Other updates include updating external link to CSV parse utility and fixing contraction typo.
=> [TW-576] Fixing broken anchor link in Test script examples TOC

src/pages/docs/getting-started/installation-and-updates.md, src/pages/docs/getting-started/settings.md
Where we mention the update feature, I clarified that this feature is only available on the Postman Desktop App. In the Installing and updating topic, I updated mentions of the Postman Desktop App to follow the same format. Also, I fixed 2 Vale suggestions.
=> [TW-580] Clarified that the update feature is only available on desktop

src/pages/index.jsx
_Branched from `develop`_, this addresses a footer render bug by finding an alternative to updating state for runtime bff events.
A rendering error was discovered on the homepage of the Learning Center. The culprit was isolated to an update to state for runtime events data.
=> [MARKENG-1639][c] address footer render bug w/ alt to updating state

src/components/Shared/EditDoc.jsx, src/pages/index.jsx
- converted button CTAs (2) to use Sentence case as per design guide
Currently:
=> converted button CTAs to use Sentence Case

bff.js, gatsby-config.js, package-lock.json, package.json
_Branched from `develop`_, this removes `gatsby-plugin-google-tagmanager`, disables the Gatsby configuration of both two plug-ins _(gatsby-plugin-google-analytics & gatsby-plugin-google-tagmanager)_, and implements Postman's pattern for GTM/GA script insertion.
By implementing our own pattern, we have finite control of how GTM & GA behaves. This aims to serve as a model for our other web apps that use GA/GTM.
*While `gatsby-plugin-google-tagmanager` was removed from the package json file, `gatsby-plugin-google-analytics` was not. This is because components import the package for `trackCustomEvent` & `OutboundLink`.
=> [MARKENG-1638][c] implement PMs pattern for GTM/GA

src/components/layout.scss
=> Updated the styling for h3 on mobile

src/pages/docs/integrations/available-integrations/new-relic.md
Hi Postman devs,
We have many users on our platform who are using Postman and would like to instrument it. We’d love to provide a smooth experience for Postman users who need to use commercial monitoring solutions, such as New Relic. Please see our documentation [here](https://newrelic.com/instant-observability/postman/d465bf08-b737-4bc5-b5ad-dd5be272967b) .
Please consider adding a link for your direct users to provide an option for New Relic.  For your convenience, we have submitted this PR with our proposed content.
Please feel free to let us know if you have any questions or concerns.
Thank you for your consideration.
=> Added Postman's NewRelic integration quickstart link

src/pages/docs/designing-and-developing-your-api/defining-an-api.md
This PR _only_ covers the UI for the governance and security warnings for the API definition. This PR will be merged into `tw-603-v10-api-security` once it's approved and ready to go. I'm holding off on screenshots until closer to release date to account for any UI and/or behavior changes.
=> TW-634 API definition linting

src/pages/docs/integrations/ci-integrations.md
@savageCoder55 Since each individual integration page has a section about the Postman CLI with a step that mentions API Governance and API Security (for example: https://learning.postman.com/docs/integrations/available-integrations/ci-integrations/bitbucket-pipelines/#configuring-the-postman-cli-for-bitbucket-pipelines, step 5), I think this wording update covers your request in TW 688. Let me know if you'd like any additional information added here!
=> TW 688 Add a note about Governance to the CI page

src/pages/docs/sending-requests/capturing-request-data/interceptor.md
Link for manual download / install of interceptor when extension fails to provide one. It was difficult to find this information, since my workflow did not proceed as described in the installation instructions. This should save other users some time when they run into the same issue.
=> Update interceptor.md to include links for manual install

.github/workflows/beta-deploy.yml, .github/workflows/ci.yml, .github/workflows/manual-rerun.yml, .github/workflows/prod-deploy.yml, build/fetchPmTech.js
_Branched from `develop`_, this switches out the endpoint to use the WORKER secret for building the app.
This makes it similar to how the www app does it. The reason LC doesn't do it the www way is because there'd be some extraneous stuff in the build payload that doesn't concern LC. But more importantly, doesn't seem prone to this new build constraint.
_*no-visuals_
=> [MARKENG-1826][c] update fetchPmTech script to use WORKER to avoid new build constraint

src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md
This PR adds a section to https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections/ about the ability to hide and unhide diffs from the changelog.
=> TW 655 Doc ability to hide a diff in the changelog

src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md, src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md, src/pages/docs/publishing-your-api/run-in-postman/run-button-API.md
* Made "Run in Postman" display in bold when referring to the button.
* Reorganized content as needed.
* Updated outdated instructions.
* Updated outdated GIF.
* Fixed issue with inline "Run in Postman" button.
* Fixed Vale suggestions.
=> [TW-387] Run in Postman button doc refresh

src/pages/docs/integrations/available-integrations/ci-integrations/bitbucket-pipelines.md, src/pages/docs/integrations/available-integrations/ci-integrations/circleci.md, src/pages/docs/integrations/available-integrations/ci-integrations/github-actions.md, src/pages/docs/integrations/available-integrations/ci-integrations/gitlab-ci.md, src/pages/docs/integrations/available-integrations/ci-integrations/jenkins.md, src/pages/docs/integrations/available-integrations/ci-integrations/travis-ci.md, src/pages/docs/postman-cli/postman-cli-options.md, src/pages/docs/postman-cli/postman-cli-overview.md
In each CI integration page:
* Added a section about viewing API linting results.
* Removed brief explanation about viewing rule violations because the instructions are not specific to CI integrations. Viewing instructions are now in the new "Viewing API linting results" section.
**Note:** Screenshots in the "Viewing API linting results" section are placeholders for now.
=> [TW-685] Added API linting results sections to CI integrations

.github/workflows/beta-deploy.yml
MARKENG-1837 - set AWS_MAX_ATTEMPTS to 10 retries to prevent develop from failing to invalidate CloudFront, develop branch only
=> MARKENG-1837 - set AWS_MAX_ATTEMPTS to 10 retries

src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
- Refresh "Setting up mock servers" page
- Add section "Editing the mock server configuration"
- Add section "Matching request body and headers"
- Add section "Using variables in mock servers"
- Update screenshots
- Fix vale errors
=> [TW-723] Doc header/body matching in mock server UI

src/pages/docs/getting-started/postman-account.md, src/pages/docs/integrations/available-integrations/slack.md
* To receive PR notification via Slack, users must mention you in PR comments. I added a note explaining this in more detail.
* Updated the "Notification preferences" screenshot to match the UI.
* Updated written instructions for accessing the "Notification preferences" screen.
=> [TW-541] Clarified how to receive PR notifications in Slack

src/pages/index.jsx
* updated icon for Intergalactic card on homepage
* updated copy to match Intergalactic page it points to
* updated CTA label
=> updated icon for Intergalactic card on homepage

src/pages/docs/writing-scripts/script-references/variables-list.md
For the description 'A random boolean value' I removed the brackets containing (true/false) as this example exists in the 'Example' column. Also removed the second set of true and false in the examples column.
For the description 'A random bank account name' I removed the brackets containing (savings account, checking account) as there are already examples in the 'Example' column.
For the description 'A random transaction type' I removed the brackets containing (invoice, payment, deposit) as this example exists in the 'Example' column.
For the description 'A random company suffix' I removed the brackets containing (Inc, LLC, Group) as this example exists in the 'Example' column.
Changed '3 random paragraphs of lorem ipsum text' to be within the same cell and added <p> and <br /> tags to …
=> Removal of repetition

src/pages/docs/postman-cli/postman-cli-installation.md
```pwsh
$POSTMAN_CLI_PATH = "$Env:USERPROFILE\AppData\Local\Microsoft\WindowsApps"
New-Item -type directory -path "$POSTMAN_CLI_PATH" -Force | `Out-Null`
$client = New-Object System.Net.WebClient
$client.DownloadFile("https://dl-cli.pstmn.io/download/latest/win64", "$POSTMAN_CLI_PATH\postman-cli.zip")
Expand-Archive "$POSTMAN_CLI_PATH\postman-cli.zip" "$POSTMAN_CLI_PATH" -Force
Remove-Item "$POSTMAN_CLI_PATH\postman-cli.zip"
mv "$POSTMAN_CLI_PATH\postman-cli.exe" "$POSTMAN_CLI_PATH\postman.exe" -Force
echo "The Postman CLI has been installed"
```
=> Windows CLI installation doesn't set path

src/pages/docs/running-collections/building-workflows.md
This section says that the setNextRequest function "only works in Collection Runner", but this is slightly misleading as it also works with the command line too. 
I have altered the following section to include a reference to Postman CLI and Newman.
The `postman.setNextRequest()` function has no effect when you run a request using **Send** and is only used when you run a collection using the Collection Runner, Postman CLI, or Newman.
=> Added a reference for Postman CLI and Newman

src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md
- Add `x-mock-response-delay` header
- Add autocomplete support for `x-mock` headers
- Fix vale errors
=> [TW-762] Doc custom delay header for mock servers

src/pages/docs/monitoring-your-api/setting-up-monitor.md
- Removed text about creating a monitor from an API (no longer possible in v10)
- Minor page refresh
=> [TW-757] Remove creating a monitor from an API

src/pages/docs/designing-and-developing-your-api/creating-an-api.md
Also, changed occurrences of 'update' to 'upgrade' because this is a one-time action on an API. The header still uses 'update' because we link to this section from the product, and changing the header will change the URL.
=> [TW-764] Clarified how to trigger the v10 upgrade prompt

src/pages/docs/integrations/available-integrations/ci-integrations/bitbucket-pipelines.md, src/pages/docs/integrations/available-integrations/ci-integrations/circleci.md, src/pages/docs/integrations/available-integrations/ci-integrations/github-actions.md, src/pages/docs/integrations/available-integrations/ci-integrations/gitlab-ci.md, src/pages/docs/integrations/available-integrations/ci-integrations/jenkins.md, src/pages/docs/integrations/available-integrations/ci-integrations/travis-ci.md
* Updated `To view a build...` to `To open a build...` because "open" clarifies that the user will open the build in the CI tool, not in Postman.
* Clarified in the "Configuring the Postman CLI" section that Postman CLI runs Postman collections with API tests, not API tests.
=> [TW-774] Wording changes to CI integrations

src/templates/doc.jsx
updated .doc-page a tags styles so they do not change Breadcrumbs styles
=> [breadcrumbStyles] fix breadcrumbs/doc page styles for the a tag

src/pages/docs/monitoring-your-api/faqs-monitors.md, src/pages/docs/running-collections/viewing-scheduled-collection-runs.md, src/pages/docs/sending-requests/troubleshooting-api-requests.md, src/pages/docs/writing-scripts/script-references/test-examples.md
I added information about the new `console.clear()` method. Users can now add this method to their pre-request or test scripts to clear the console. I searched the documentation for sections that already explain/mention the `console.*` methods, and added a line about the `console.clear()` method.
There are other sections that mention console-related logs, such as `/docs/monitoring-your-api/troubleshooting-monitors/#viewing-failed-monitors`, `/docs/monitoring-your-api/viewing-monitor-results/#console-log`, and `/docs/running-collections/viewing-scheduled-collection-runs/#console-log`. Since these sections focus on viewing logs for scheduled collection runs and monitors, I chose to exclude any mentions of the clear method. Please let me know if you think we should still mention the clear …
=> [TW-805] console clear method

src/pages/docs/collaborating-in-postman/roles-and-permissions.md
Question for the group - Since the availability for these workspace roles is on Basic, Professional, and Enterprise plans and that's pretty lengthy for a list entry, I used "Paid plans only" as shorthand for that, with a link to the [pricing page](https://www.postman.com/pricing/). In your opinions, is that clear enough? Or should I use "Basic, Professional, and Enterprise plans only" instead? 🤔
=> TW 821 Clarify workplace roles availability

src/pages/docs/getting-started/troubleshooting-inapp.md
The older Postman app section is no longer present, which leads to the error screen "The page you are looking for no longer exists"
=> Updated the link to FAQs directory

src/templates/doc.jsx
* brought in `UnorderedListStyles` and `OrderedListStyles` from Aether-Marketing
* this updates the list styles to match across sites, and fixes spacing issue reported
* ordered list should now be indented, as per spec
* unordered (stars) list updates as well to now match other sites
* see `/docs/collaborating-in-postman/adding-private-network/` for examples of both in one page
=> added UL and OL styles from Aether-Marketing to doc template

src/pages/docs/integrations/available-integrations/ci-integrations/circleci.md, src/pages/docs/integrations/available-integrations/ci-integrations/jenkins.md, src/pages/docs/integrations/available-integrations/ci-integrations/travis-ci.md
Instructions mentioned that you can open a build in the CI tool by hovering over a build and selecting "View build details", which isn't correct.
I confirmed with the Integrations squad that users only need to select the build name in Postman.
=> [TW-839] Select build name in CI integrations

src/pages/docs/sending-requests/authorization.md
Based on user report, reference: https://community.postman.com/t/schedule-and-monitor-cause-401-when-manual-collection-run-works/42392/2
=> Refresh token limitations

src/pages/docs/administration/managing-your-team/configuring-domain-capture.md
Currently, we document that teams must be on version 9 to use domain capture. Since v10 is released, I updated the text to explain that teams can be on version 9 or later.
=> [TW-894] Update version prerequisite for domain capture

src/pages/docs/administration/sso/microsoft-adfs.md, src/pages/docs/administration/sso/okta.md
* Updated written instructions and screenshots, reorganizing as needed. Expanded/simplified written instructions where applicable.
* Switched the Postman app and custom SAML app instructions, making the Postman app instructions display first. The reason is that this seems like the more common, recommended approach.
* Added a reference to setting up SSO in Postman
* Wording and grammar changes where applicable
* Updated Markdown syntax for images
* Ran Vale on the page, and found no major issues
* Updated front matter, removing deprecated key-values
* Updated the Prerequisite link to match other recently updated configurations (Azure AD and OneLogin)
=> [TW-358] Refresh Okta SSO

src/pages/docs/administration/scim-provisioning/scim-provisioning-overview.md
* Clarified that roles assigned to a group are also assigned to its group members.
* In the **Create group** and **Update group members** bullet points, updated/added links pointing to:
* updating group roles
* controlling additional group access/permission
=> [TW-770] Assign users to roles via SCIM

src/pages/docs/sending-requests/examples.md
* Explained how users can open saved example responses as requests. Users can then send the request, enabling them to try the example.
* Explained an alternative user flow for editing saved example responses.
=> [TW-934] Consuming saved example responses

src/templates/doc.jsx
anchor link size is now relative to the text size it sits next to.
Check any doc page that has anchor links next to it's headings
=> added anchor link styling

src/components/LeftNav/LeftNav.jsx
Current implementation of the LeftNav in the /docs/ paths causes a hard browser navigation when an accordion is clicked to expand.
Current Implementation:
This MR modifies the CaretWrapper styled component to be a `Link` instead of an `a`, which does a proper in-app navigation.
It also changes the sectionHandler function to use Gatsby's built in `navigate` feature rather than the browser api for changing current url.
Improved Implementation:
=> Fixing leftnav accordion hard load

src/components/ContextualLinks/ContextualLinks.jsx
Adds missing `key` attribute to ContextualLinks develop mode error message.
Before:
After:
=> fixing contextual links map/key error in dev mode

src/pages/docs/administration/managing-your-team/configuring-domain-capture.md
The user can verify their domain without the need to contact support. Only enabling domain capture requires the user to contact support. Also, added a note to set expectations that it may take up to 24 hours for the successful verification of a TXT record.
=> Domain verification is self-serve

src/pages/docs/collaborating-in-postman/manage-public-elements.md, src/pages/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections.md, src/pages/docs/getting-started/navigating-postman.md, src/pages/docs/sending-requests/requests.md
Users can no longer view their team's activity from the Homepage
=> [TW-1050] Removed mentions of team activity on Homepage

bff.js
 
_Branched from `develop`_, this remove the tag call..  
 
It's cruft, meant for www
  *no-visuals
=> [MARKENG-2381][c] remove gtag

styles/config/print.css
* updated print CSS file to keep `#icons` from showing up too small
Use `/docs/collections/running-collections/working-with-data-files/` or `/docs/publishing-your-api/run-in-postman/introduction-run-button/` and cmd-p to print to verify. Icons should be of a good readable size, like screen.
=> [MARKENG-1813] update print CSS file for icons that were too small

src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md
* Added note explaining that you can't change a workspace's visibility to personal.
* Removed "Personal" from the list of visibility options because it isn't actually an option.
=> [TW-983] You can't change visibility to personal

src/components/LeftNav/LeftNav.jsx
[fix eplanation](https://stackoverflow.com/questions/46965309/react-functional-component-calling-as-function-vs-as-component)
If you call functional component directly, you are calling a custom hook actually.
example:
```
function A() {
const [state] = useState([])
return (
<div>{state}</div>
)
}
A()
<A />
```
If you call `A()`, the `state` mounts in parent fiber, but if you use `<A />`, React will call `createElement` to create a new fiber on which to mount `state`.
In addition, I added useLayoutEffect instead of useEffect for actions that change the screen, as it runs synchronously after all DOM mutations. This can help prevent flickering issues caused by the asynchronous nature of useEffect.
=> Markeng-2359-christina fix hydration error 

src/pages/docs/getting-started/troubleshooting-inapp.md, src/pages/docs/sending-requests/grpc/understanding-grpc-types.md
This PR addresses the following:
**/docs/getting-started/troubleshooting-inapp/**
- Updated the `update` field, as there were nothing that appeared in need of fixing.
**/docs/sending-requests/grpc/understanding-grpc-types/**
- Should the **Protofbuf type** table entries be in code format?
- The table notes did not end with a period (`.`), so I updated this because they are complete sentences.
- The table formatting was really hard to read/manage, so I cleaned it up to make it more manageable.
- Updated the `updated` field.
I opened tickets for the following because they need a (screenshot) refresh:
- /docs/integrations/available-integrations/splunk-on-call/ — https://postmanlabs.atlassian.net/browse/TW-1075
- /docs/integrations/available-integrations/keen/ — …
=> [TW-1069] Maintenance review cycle 4/23 11-15

bff.js
_ Branched from `develop`_, this uses Google’s suggested syntax to tag “UA-43979731-4”.
   
  The updates the web app’s to GA code for GA4
=> [MARKENG-2419][c] Update LC to gtag UA-43979731-4

src/pages/docs/collections/using-newman-cli/command-line-integration-with-newman.md, src/pages/docs/collections/using-newman-cli/installing-running-newman.md, src/pages/docs/collections/using-newman-cli/integration-with-jenkins.md, src/pages/docs/collections/using-newman-cli/integration-with-travis.md, src/pages/docs/collections/using-newman-cli/newman-custom-reporters.md, src/pages/docs/collections/using-newman-cli/newman-file-uploads.md, src/pages/docs/collections/using-newman-cli/newman-options.md, src/pages/docs/collections/using-newman-cli/newman-with-docker.md, src/pages/docs/designing-and-developing-your-api/mocking-data/mock-with-api.md, src/pages/docs/developer/postman-api/authentication.md, src/pages/docs/developer/resources-intro.md, src/pages/docs/publishing-your-api/run-in-postman/run-button-API.md
* To match the page's new title, updated the title from "Postman API overview" to "Postman API documentation".
* Removed deprecated key-value pairs from front matter.
=> [TW-1113] Update postman api front matter

redirects.json
Updated redirects to point to the page's new URL at `docs/collaborating-in-postman/requesting-access-to-elements/`
Related to the redirect on lines `2155`-`2156`
=> [TW-1118] Update redirects

src/pages/docs/designing-and-developing-your-api/versioning-an-api/using-external-git-repo.md
Clarify that connecting to an on-prem git repo:
- Requires an Enterprise plan
- Requires using the Postman desktop app
- Doesn't require allowing Postman IPs, as all communication is between desktop app and the repo
=> [TW-1111] Clarify on-prem git doesn’t go through Postman servers

src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md, src/pages/docs/sending-requests/visualizer.md
* Updated the Run in Postman button in the Visualizing responses page, which wasn't working correctly
* Clarified that the button points to a collection, not a request
* Updated instructions about creating a Run in Postman button, which now requires you to select different icons
=> [TW-1134] Update Run in Postman button, and instructions

src/pages/docs/integrations/available-integrations/azure-devops.md
This updates the `/docs/integrations/available-integrations/azure-devops` documentation. Namely:
- Cleaning up the frontmatter.
- Added new frontmatter prereq link to the "Using a remote Git repository" doc.
- Changing the link for "Postman to Azure DevOps" integration to point at the on-prem section of the "Using a remote Git repository" doc. It seems like it makes more sense since the Azure DevOps document focuses on an on-premises integration.
- Updated the "API sync with Azure DevOps":
- Removed the v10 specific mention — I'm not sure if that is necessary any longer?
- Linked out to the API Builder at its mention.
- Split the note into two paragraphs so it was a little easier to read.
=> [TW-1153] Maintenance 5/23 updates

src/templates/doc.jsx
Fixes issue where long lines overflow to the right in code reference tables when using the `<pre>` tag.
Solution is to add the following css to the `<pre>` tag in `/src/templates/doc.jsx`:
```
overflow-x: auto;
white-space: pre-wrap;
word-wrap: break-word;
```
Tested the fix in Chrome, Safari, and Firefox.
Source of this solution: https://www.w3docs.com/snippets/css/how-to-wrap-text-in-a-pre-tag-with-css.html
=> Add overflow css to <pre> tag

src/components/Search/searchPreview.jsx
This PR adds a catch to display a message to the user if a index endpoint cannot be found and prevent the app from breaking.
=> [markeng-2488] add catch to Agolia for index switching

src/components/seo.jsx
* added `async` to the OneTrust script
* suggested by page speed insights tool
* OT banner should still render as it has been—no changes
=> add async to OneTrust script to keep from blocking rendering

src/components/seo.jsx
Applied the same logic to the Marketing web app. Preload is disabled.
=> [MARKENG] Address font flicker on page load

src/pages/docs/designing-and-developing-your-api/creating-an-api.md, src/pages/docs/developer/postman-api/intro-api.md
Added note that v9 API format has been deprecated and recommend users upgrade APIs to the new v10 format
=> [TW-1195] Doc APIB deprecation upgrade to V10

src/components/Header/HeaderStyles.jsx, src/components/seo.jsx
This removes the OneTrust load script in seo.jsx since it is already being loaded from the bff. 
https://onetrust-fix.learning.postman-beta.com/
Discovered it was loading twice.
=> Remove script to load OneTrust

src/components/seo.jsx
Received an email about repeated monitoring errors in the Postman app. This adds the OneTrust scrip back to seo.jsx  to resolve the issue.
=> Add back OT script due to failing monitor

redirects.json, src/components/LeftNav/LeftNavItems.jsx, src/pages/docs/administration/about-postman-enterprise.md, src/pages/docs/collaborating-in-postman/private-api-network/adding-private-network.md, src/pages/docs/collaborating-in-postman/private-api-network/managing-private-network.md, src/pages/docs/collaborating-in-postman/private-api-network/organizing-private-network.md, src/pages/docs/collaborating-in-postman/private-api-network/private-network-requests.md, src/pages/docs/collaborating-in-postman/roles-and-permissions.md, src/pages/docs/collaborating-in-postman/using-workspaces/managing-workspaces.md, src/pages/docs/collections/using-collections.md, src/pages/docs/designing-and-developing-your-api/managing-apis.md, src/pages/docs/designing-and-developing-your-api/versioning-an-api/api-versions.md, src/pages/docs/getting-started/navigating-postman.md, src/pages/docs/reports/api-gov-reports.md, src/pages/docs/reports/api-security-reports.md, src/pages/docs/reports/content-activity-reports.md
This PR reorganizes the **Your Private API Network** document by splitting it up into separate pages:
For the most part I just took the existing content and moved it to the new articles.
The **Organizing your Private API Network** article is the bulkiest of these documents, but I didn't think that the information contained needed further splitting. I tried to keep the articles contained as follows:
- **Organizing your Private API Network** — Adding, editing, and managing folders and elements.
- **Managing your Private API Network** — Managing user permissions, reporting.
- **Private API Network requests** — Requests (making and managing) to the Private API Network.
For the naming of these articles, I borrowed a little from the **Sharing to the Public API Network** section:
While reviewing …
=> [TW-1188] Break up "Private API Network"

src/components/ContextualLinks/ContextualLinks.jsx
https://update-blog-tag-logic.learning.postman-beta.com/docs/publishing-your-api/documenting-your-api/
This adds a node environment check to prevent the develop mode banner from displaying if blog tags are 0. 
Develop mode
Production
=> Bugfix: Add environment check to hide develop mode blurb in production

src/pages/docs/integrations/available-integrations/ci-integrations/azure-pipelines.md, src/pages/docs/integrations/available-integrations/ci-integrations/bitbucket-pipelines.md, src/pages/docs/integrations/available-integrations/ci-integrations/circleci.md, src/pages/docs/integrations/available-integrations/ci-integrations/github-actions.md, src/pages/docs/integrations/available-integrations/ci-integrations/gitlab-ci.md, src/pages/docs/integrations/available-integrations/ci-integrations/jenkins.md, src/pages/docs/integrations/available-integrations/ci-integrations/travis-ci.md
Adds a step about viewing collection runs/updates screenshots based on CircleCI/Travis CI demos. Removes duplicate screenshots.
[Preview](https://tw-684-collection-run.learning.postman-beta.com/docs/integrations/ci-integrations/)
=> [TW-684] Add "Viewing collection run details" sections to all CI/CD integrations

src/pages/docs/collaborating-in-postman/working-with-your-team/collaborating-in-team-workspaces.md
This updates the **Collaborating in team workspaces** page to include mention of flows in the lede paragraph.
As part of this work, I updated the *Moving elements to team workspaces* section to include flows where applicable. I did not include a bulletpoint for flows in that section because it did not appear that there were any restrictions for moving flows.
I checked the following entries as well, but didn't see that we needed to include "flows" in them:
- `enabling-team-discovery.md`
- `discussing-your-work.md`
- `collaboration-overview.md`
=> [TW-1280] Add mention of flows to "Collaborating in team workspaces" page

src/components/seo.jsx
- add back in the performance improvements we reverted when we got CORS issues.
- @mclausaudio fixed up CORS, so we should not see red on BETA for fetching the .css file
- Should no longer see this in Inspect > Performance test tab
=> fetch performance improvements on font css file and OT

build/marketo.munchkin.js, src/components/layout.jsx
_Branched from `develop`_, this reinstates munchkin.js from the LC web app.
High priority task to reenable the library to see how it affects the reporting of signups.
*no visuals
=> [MARKENG-2749][c] Reinstate munchkin.js

src/pages/index.jsx
_Branched from `develop`_, this remove the pixel.math pixel.
A request from from Jenny and Security.
*no-visuals
=> [MARKENG-2793][c] Remove `pixel.mathtag.com` from LC

build/bffData.js
_Branched from `develop`_, this hardcodes MKAPI_URL envvar when it is unavailable.
Otherwise contributors may not have data necessary to build the web app.
*no-visuals
=> [MARKENG-0001][c] hardcode api url when envvar is unavailable

src/pages/auto-flex-policy.jsx
Update prices on Auto Flex Page
- $144 per User per year → $196 
- (i.e. $216 total → $252)
[Markeng-2715](https://postmanlabs.atlassian.net/jira/software/c/projects/MARKENG/boards/399?assignee=62a78584979e6e006904329f&selectedIssue=MARKENG-2715)
=> [MARKENG-2715][c] update prices on Auto Flex Page

src/components/LeftNav/LeftNavItems.jsx, src/pages/docs/getting-started/importing-and-exporting/importing-from-swagger.md
Added a new doc on importing a Swagger API. Included a leftnav item for a separate doc from TW-1391 to avoid a merge conflict.
=> [TW-1392] migration guide swagger

src/pages/docs/sending-requests/authorization/oauth-20.md
Anchors (like `#authorization-code`) do not work if they do not match the (implicitly generated) header id.
Example: right now the link https://learning.postman.com/docs/sending-requests/authorization/oauth-20/#client-credentials leads you to the top of the page while, I guess, it was supposed to lead to the corresponding section on this page.
There is also a small preposition issue...
=> Fixed anchors in docs

src/pages/docs/integrations/available-integrations/slack.md
- Reworded headings to match options in Postman
- Changed gerunds to imperatives
- Added then removed content for **Post uptime monitor notifications**. The Slack Integrations page includes an option for this, but the feature was canceled after last year's beta and few users have or can create uptime monitors. We decided to ignore this content in the LC.
=> [TW-1376] update slack integrations

src/pages/docs/live-insights/live-insights-troubleshoot.md
Adds troubleshooting FAQs to the Live Insights troubleshooting topic
[Preview](https://tw-1496-migrate-troubleshooting-faq-to-lc.learning.postman-beta.com/docs/live-insights/live-insights-troubleshoot/)
=> [TW-1496] Migrate troubleshooting FAQ to LC

src/pages/docs/getting-started/installation/installation-and-updates.md
In fedora , the postman linux version cashes right after signing in. The reason is the absence of openssl library.
[redit post](https://www.reddit.com/r/Fedora/comments/16had56/postman_is_crashing/)
=> requirement of openssl in linux desktop client.

src/pages/docs/collaborating-in-postman/private-api-network/publish-private-network-elements-with-api.md, src/pages/docs/developer/postman-api/make-postman-api-call.md, src/pages/docs/developer/postman-api/postman-api-rate-limits.md
The previous phrasing did not make it clear that the limit applies to a specific api-key/users. After developer analysis, we want to support only the rate limit by user. This PR updates the phrasing to reference account/users instead of API keys. Further information/details are available in [PAPI-2306](https://postmanlabs.atlassian.net/browse/PAPI-2306).
[PAPI-2306]: https://postmanlabs.atlassian.net/browse/PAPI-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PAPI-2306] Update Postman API rate limit statements

src/pages/docs/live-insights/live-insights-gs.md
Replaces the Insights tab screenshot to reflect slowest endpoints
=> [TW-1578] Replace Insights tab screenshot

build/navbarDev.json
This adds POST/CON under Community and Events in the top nav bar.
=> [MARKENG-2991] Update top nav bar to include POST/CON

src/pages/docs/publishing-your-api/custom-doc-domains.md
- Clarify that you can't host documentation on a main domain, only a subdomain
- Updated screenshots to show `docs.example.com`
View the beta docs here: [Host API documentation with a custom domain](https://tw-1577-fix-custom-domains.learning.postman-beta.com/docs/publishing-your-api/custom-doc-domains/)
=> [TW-1577] Root domain can't be used as custom domain

src/pages/docs/getting-started/basics/about-vs-code-extension.md, src/pages/docs/getting-started/importing-and-exporting/importing-and-exporting-overview.md
* Added new bullet points about importing collections, and collection documentation.
* Mentioned on the importing and exporting overview that you can also import using the VS Code extension.
* Updated the hero image screenshot.
[Beta site](https://tw-1503-vs-code-doc-view-import-collections.learning.postman-beta.com/docs/getting-started/basics/about-vs-code-extension/)
=> [TW-1503] Full doc view and import collections in VS Code

src/pages/docs/collaborating-in-postman/roles-and-permissions.md, src/pages/docs/collaborating-in-postman/user-groups.md
This adds a small callout on `collaborating-in-postman/user-groups.md` and `collaborating-in-postman/roles-and-permissions.md` that mention the Postman API.
This actually links to the main landing page of the Postman API in the Postman Public Workspace because the API doesn't exist yet. I can provide a subsequent update at a later date if needed that points directly to the specific collection folder (it will be Workspaces -> Roles).
**Note:**
I wasn't sure about updating the `updated` field in the frontmatter because it was such a minor update that I did not want to push the pages down the line for a refresh update.
=> [TW-1490] Add note about the Workspace roles API

src/pages/docs/administration/managing-your-team/managing-your-team.md, src/pages/docs/collaborating-in-postman/private-api-network/adding-private-network.md
Updated the Private API Network and Admin pages to reflect the read/write separation, replaced a screenshot
=> [TW-1567] Doc Private network read/write separation for new enterprise packaging

src/pages/docs/administration/managing-your-team/managing-api-keys.md
This PR updates the **Manage API Keys** interface documentation around the updates to now include exposed keys in Postman documentation. This primarily updates:
- Screenshots to reflect the UI updates.
- Minor phrasing revisions to include Postman documentation as a scanned resource.
=> [TW-1522] Updates for the Manage API Key interface

src/pages/docs/live-insights/live-insights-troubleshoot.md
Adds a troubleshooting topic for out-of-memory issues
[Preview](https://tw-1585-add-a-memory-allocation-troubleshooting-entry.learning.postman-beta.com/docs/live-insights/live-insights-troubleshoot/#ecs-memory-issues-troubleshooting)
=> [TW-1585] Add a memory allocation troubleshooting entry

src/pages/docs/collaborating-in-postman/user-groups.md
As it turns out, the images that were mentioned as being in need of updating in the [Jira ticket](https://postmanlabs.atlassian.net/browse/TW-1154) were, in fact, still correct. This task instead resolves one Vale error (`broadly`) and adjusted the TOC format to not have spaces in between each entry (like the other files in this folder).
This topic could use some splitting, and I've [proposed solution in the ticket](https://postmanlabs.atlassian.net/browse/TW-1154?focusedCommentId=660506). I checked the TW backlog and did not see any open tickets around doing this, so I created a [Jira ticket](https://postmanlabs.atlassian.net/browse/TW-1609).
=> [TW-1154] Minor refresh and Vale fix

src/pages/docs/writing-scripts/intro-to-scripts.md
This PR primarily updates the screenshots in the document. Vale returned "previous" as a suggested change, but in this particular context "earlier" does not make sense. 
Minor revisions include adding a link out to Node.js's page and a minor revision from "one" to "script" at line 40 for clearer context.
=> [TW-1187] Updating "Scripting in Postman" screenshots

src/pages/docs/developer/postman-api/intro-api.md
This adds the new **Roles** and **Workspace roles** sections to the Postman API intro page. I broke **Workspace roles** into its own subsection because there is another roles-based endpoint in the works (collections), so this section will get bigger in time.
=> [PAPI-2405] Add "Roles" to Postman API intro

package-lock.json
* ran `npm audit`
* ran suggested `npm update msgpackr --depth 10` to clear VULN
* generated new package-lock file
=> [c] update-msgpackr npm package at depth of 10

src/pages/docs/administration/enterprise/managing-enterprise-deployment.md
The standard behavior with .msi installers is that all-caps properties are considered Public and available in the command-line installations we have documented.
[Public Properties - Win32 apps | Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/msi/public-properties)
Properties that are lowercase are considered private and would not be available in the command-line install.
Also, fixing the spelling, as the currently documented property should have an underscore as opposed to a hyphen.
=> Updating team-ids to TEAM_IDS on the MSI Installation Doc

src/components/LeftNav/LeftNavItems.jsx, src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md
- Updated the page title/header and LeftNav title.
- Updated the introduction statement a bit with some links out to other LC documentation (like forks, and the additional Run in Postman articles).
- Made some minor revisions, including moving the warning about sensitive data to the end of the overview section so that it's more visible.
=> [TW-1559] Update Run in Postman overview

src/pages/docs/administration/domain-verification-and-capture/add-and-verify-a-domain.md, src/pages/docs/administration/domain-verification-and-capture/domain-capture-overview.md
Clarified the overview about adding users to a team when the user's email is verified with the relevant domain. If the organization's domain is verified, Team Admins can invite a user to join the team, which adds them to the team without having to accept an invite. If the organization's domain isn't verified, the user must accept an invite and complete extra steps to join the team.
**Beta site**:
* [Domain verification and capture overview](https://tw-1677-domain-verification-clarification.learning.postman-beta.com/docs/administration/domain-verification-and-capture/domain-capture-overview/)
* [Verify your organization’s domain](https://tw-1677-domain-verification-clarification.learning.postman-beta.com/docs/administration/domain-verification-and-capture/add-and-verify-a-domain/)
=> [TW-1677] Clarify inviting verified users to join a team

src/pages/docs/getting-started/importing-and-exporting/exporting-data.md, src/pages/docs/getting-started/installation/settings.md
- Removed two notes mentioning the Scratch Pad (another Scratch Pad note was already removed in #5373)
- The information in these notes is already included on the Scratch Pad page: `/docs/getting-started/basics/using-scratch-pad/`
[View the beta docs](https://tw-1633-remove-scratch-pad-refs.learning.postman-beta.com/docs/collections/running-collections/intro-to-collection-runs/)
=> [TW-1633] Remove unneeded references to Scratch Pad

src/pages/docs/developer/postman-api/authentication.md
This is a minor update to remove the mention of using an API key query parameter, as this is planned for deprecation/unsupported (see https://postmanlabs.atlassian.net/browse/PAPI-2380 for further details).
=> [PAPI-2400] Remove line about apiKey query param in "Generate and use Postman API keys"

src/components/Header/Header.jsx
Removes `undefined` from the `classNames` by checking if `link.link` exists before adding it to the class
Preview Branch:
https://markeng-3101.learning.postman-beta.com/
=> [MARKENG-3101] remove undefined from classNames in global nav

lint-front.js, src/pages/docs/administration/domain-verification-and-capture/add-and-verify-a-domain.md, src/pages/docs/introduction/overview.md, src/pages/docs/postman-cli/postman-cli-overview.md, src/pages/docs/postman-flows/gs/flows-usage.md, src/pages/docs/sending-requests/cookies.md
Also adds to the logging message to say where missing title files actually are.
=> Remove smart quotes from titles

src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
Updated two screenshots to show new, more-detailed timestamps for mock call logs
View the beta docs here: [Viewing mock calls](https://tw-1705-mock-timestamps.learning.postman-beta.com/docs/designing-and-developing-your-api/mocking-data/setting-up-mock/#viewing-mock-calls)
=> [TW-1705] Doc better readability on mock call logs

src/pages/docs/sending-requests/postman-vault-secrets.md
In this release, Postman won't preserve your vault secrets after signing out of the web app. Previously we documented that the web app was required to preserve secrets on sign out.
* Clarified that you need your vault key to access your Postman Vault, and not your vault secrets. The reason is that the vault key doesn't give you access to your secrets because secrets aren't preserved, and the key is required when you sign in.
* Clarified that secrets aren't preserved when you sign out, and this might be a reason why your secrets are unresolved when you sign in.
* There are now only features that require the desktop app. Updated referenced to the "Feature availability" section to reflect this.
* Updated a screenshot with copy changes.
---
[Beta …
=> [TW-1650] Postman Vault March non-Enterprise

src/pages/docs/designing-and-developing-your-api/versioning-an-api/using-on-prem-git-repo.md
Add required permissions for GitHub and GitLab when creating an installed app
View the beta docs here: [Creating an installed app](https://tw-1730-gitlab-api-scope.learning.postman-beta.com/docs/designing-and-developing-your-api/versioning-an-api/using-on-prem-git-repo/#creating-an-installed-app)
=> [TW-1730] Permissions required for a GitLab API key

src/pages/docs/collaborating-in-postman/using-version-control/creating-pull-requests.md
Adds user groups to the PR creation procedure.
[Beta docs](https://tw-1661-pr-review-groups.learning.postman-beta.com/docs/collaborating-in-postman/using-version-control/creating-pull-requests/)
=> [TW-1661] pr review groups

src/pages/docs/collaborating-in-postman/using-workspaces/creating-workspaces.md, src/pages/docs/getting-started/basics/navigating-postman.md, src/pages/docs/getting-started/first-steps/creating-the-first-collection.md, src/pages/docs/sending-requests/create-requests/request-basics.md, src/pages/docs/sending-requests/grpc/first-grpc-request.md, src/pages/docs/sending-requests/grpc/grpc-request-interface.md, src/pages/docs/sending-requests/mqtt-client/first-mqtt-request.md, src/pages/docs/sending-requests/mqtt-client/mqtt-request-interface.md, src/pages/docs/sending-requests/soap/making-soap-requests.md, src/pages/docs/sending-requests/websocket/create-a-websocket-request.md
This updates the CNX images to match that you can't create a new API via this method. I also updated the text in `/docs/getting-started/basics/navigating-postman` to omit "API" from the sentence at line 111.
Part of this update was to remove the use of animated gifs in the following:
- `/docs/sending-requests/grpc/grpc-request-interface/`
- `/docs/sending-requests/create-requests/request-basics/`
These now use static images of the menu so it is much easier to maintain as this changes over time.
You can view each change at the follow beta preview links:
- https://tw-1731-update-cnx-images.learning.postman-beta.com/docs/getting-started/first-steps/creating-the-first-collection/
- https://tw-1731-update-cnx-images.learning.postman-beta.com/docs/getting-started/basics/navigating-postman/#sideb …
=> [TW-1731] Update CNX images
