01_getting_started/install_mac.md
Just added the windows references, since it doesn't seem worth a separate document and screenshot. Was unclear if the file name should change
=> update install_mac.md to include  windows

_posts/02_sending_and_viewing_responses/2016-07-11-requests.md
See how it looks now:  https://www.getpostman.com/docs/requests
=> bold (**) and :entity

_posts/02_sending_and_viewing_responses/2016-07-11-working_with_cookies.md
Update cookie docs to reflect changes in app
=> Update cookie docs to reflect changes in app

_posts/07_postman_for_public_apis/2016-07-11-run_partner_prog.md
Remove reference to march launch, highlight partnering as an ongoing
activity
=> Update Partnership program

_posts/06_api_testing_and_collection_runner/2016-07-11-sandbox.md, _posts/06_api_testing_and_collection_runner/2016-07-11-testing_examples.md
As pointed out in postmanlabs/postman-app-support#2391, adding documentation to relevant pages:
https://www.getpostman.com/docs/testing_examples
https://www.getpostman.com/docs/sandbox
=> Add documentation for getEnvironmentVariable & getGlobalVariable

_posts/01_getting_started/2016-07-11-errors.md, _posts/01_getting_started/2016-07-11-why_native.md
=> Updated error and why_native to include details on Postman Console

_includes/_footer.html, _includes/_header.html, _includes/_navigation.html
This is to be merged & deployed along with the next prod deployment
=> Update footer & navigation

_includes/_footer_scripts.html, _includes/_meta.html, _layouts/default.md, _layouts/home.md
Static site transitioned to using a bundled JS file ~3 versions ago. Transitioning the docs to use that package as well. Added fingerprinting & removed an unused font while I was at it.
=> Asset cleanup

_posts/11_miscellaneous/2016-07-11-monitors.md
Update Monitor pricing docs to reflect /pricing verbiage
=> update Monitor pricing

_posts/03_managing_collections/2016-07-11-creating_documentation.md, _posts/05_postman_for_teams/2016-07-11-cloud_team_setup.md
=> Custom domain docs

_includes/_meta.html
Add title and meta tags to documentation pages from front matter
=> Title and meta tags

_data/doc_map.json, _layouts/home.md, _posts/01_getting_started/2016-07-11-install_native.md, _posts/01_getting_started/2016-07-11-introduction.md
Update copy to differentiate between native app and Chrome app
Increase prominence of native app
Update Postman Cloud copy to Postman Pro
@godfrzero would you please code review?
=> Prefer the native app

_posts/05_postman_for_teams/2016-07-11-buying_cloud.md
@godfrzero removed an image with Cloud pricing
=> remove Cloud pricing image

_posts/06_api_testing_and_collection_runner/2016-07-11-newman_intro.md
The URL dump.getpostman.com does not exist any longer.
=> Removed reference to URL: dump.getpostman.com

_posts/06_api_testing_and_collection_runner/2016-07-11-pre_request_scripts.md
Minor typo for timestampHeader doc
=> fix typo for timestampHeader

_data/doc_map.json, _data/video_tutorials.json, _layouts/home.md, _posts/12_postman_pro_integrations/2016-07-11-apimatic.md, _posts/12_postman_pro_integrations/2016-07-11-dropbox_integration.md, _posts/12_postman_pro_integrations/2016-07-11-github_integration.md, _posts/12_postman_pro_integrations/2016-07-11-gitlab_integration.md, _posts/12_postman_pro_integrations/2016-07-11-keen_integration.md, _posts/12_postman_pro_integrations/2016-07-11-pagerduty_integration.md, _posts/12_postman_pro_integrations/2016-07-11-slack_integration.md
Add apimatic integrations page
Update video tutorial links
=> Add apimatic integrations page

_posts/05_postman_for_teams/2016-07-11-buying_cloud.md
=> remove screenshots of cloud pricing

_posts/06_api_testing_and_collection_runner/2016-07-11-integrating_with_jenkins.md
@czardoz @loopDelicious  Updated newman command for running collection in docs.
=> Update newman command in jenkin integration docs

_posts/06_api_testing_and_collection_runner/2016-07-11-newman_intro.md
Includes details on:
* Creating custom reporters 
* Using custom reporters
cc @czardoz @godfrzero
=> Added Newman custom reporter docs

_posts/11_miscellaneous/2016-07-11-monitors.md
=> Added more details on monitor debugging

_posts/01_postman/02_sending_api_requests/2017-05-04-requests.md, _posts/01_postman/09_monitors/2017-05-04-monitoring_apis_websites.md, _posts/01_postman/09_monitors/2017-05-04-pricing_monitors.md, _posts/01_postman/09_monitors/2017-05-04-setting_up_monitor.md, _posts/01_postman/09_monitors/2017-05-04-viewing_monitor_results.md, _posts/01_postman/2017-05-04-mock_servers.md, _posts/01_postman/2017-05-04-notifications.md, _posts/02_pro/01_managing_pro/2017-05-04-billing_and_pricing.md, _posts/02_pro/01_managing_pro/2017-05-04-inviting_and_managing.md, _posts/02_pro/02_pro_api/2017-05-04-continuous_integration.md, _posts/03_enterprise/01_sso/2017-05-04-admin_sso.md, _posts/03_enterprise/01_sso/2017-05-04-intro_sso.md, _posts/04_postman_for_publishers/01_run_button/2017-05-04-collections_run_button.md, _posts/04_postman_for_publishers/01_run_button/2017-05-04-creating_run_button.md, _posts/04_postman_for_publishers/01_run_button/2017-05-04-environments_run_button.md, _posts/04_postman_for_publishers/01_run_button/2017-05-04-security.md, _posts/04_postman_for_publishers/01_run_button/2017-05-04-using_run_button.md, _posts/04_postman_for_publishers/2017-05-04-public_api_docs.md
- update copy on setting up a monitor
- update copy on notifications
- fix missing image
- add screenshots to inviting and managing page
- general copy and screenshots per abhinav annotations
=> Update copy and screenshots

_posts/12_api_testing_and_collection_runner/2016-07-11-newman_intro.md
=> Restored Newman custom reporter docs

_posts/01_postman/06_collection_runs/2017-05-04-command_line_integration_with_newman.md
=> Re-restored Newman custom reporter docs

_posts/01_postman/06_collection_runs/2017-05-04-command_line_integration_with_newman.md, _posts/12_api_testing_and_collection_runner/2016-07-11-newman_intro.md
Last release pushed to the old page, which was being 301'd to this one.
=> Releasing restored Newman custom reporter docs

_posts/01_postman/04_scripts/2017-05-04-postman_sandbox.md, _posts/12_api_testing_and_collection_runner/2016-07-11-sandbox.md
=> Added deprecation notice for Sandbox Sugar.js

_includes/_side_accordion.html, _layouts/default.md, _layouts/home.md, index.html
temporary fix - remove swiftype search field due to service issues.
=> remove search box from home page and side accordion

.travis.yml, _config.yml, _includes/_footer.html, _layouts/default.md, _posts/01_postman/03_collections/2017-05-04-managing_collections.md, _posts/01_postman/09_monitors/2017-05-04-intro_monitors.md, _posts/01_postman/09_monitors/2017-05-04-setting_up_monitor.md, _posts/01_postman/09_monitors/2017-05-04-viewing_monitor_results.md, _posts/01_postman/10_mock_servers/2017-05-04-setting_up_mock.md
- remove canary tags from multi-level folders
- update mocks (shared in collections, CORS support)
- update monitors (multi-region)
- update footer
- add config for travis ci to autoindex pages for search
=> Add multi-region monitoring, mocks collaboration, multi-folder

_data/doc_map.json, _posts/03_enterprise/01_sso/2017-05-04-admin_sso.md, _posts/03_enterprise/01_sso/2017-05-04-saml_duo.md, _posts/03_enterprise/01_sso/2017-05-04-saml_gsuite.md, _posts/03_enterprise/01_sso/2017-05-04-saml_okta.md, _posts/03_enterprise/01_sso/2017-05-04-saml_onelogin.md
- duo
- gsuite
- okta
- onelogin
=> Add 4 custom SAML pages to enterprise

_posts/01_postman/07_team_library/2017-05-04-activity_feed_and_restoring_collections.md
Just changing title for url to have HipChat instead of Slack
=> Changing title for url to hipchat integration

_posts/01_postman/04_scripts/2017-05-04-postman_sandbox_api_reference.md
=> Updated sandbox libraries

_posts/01_postman/04_scripts/2017-05-04-postman_sandbox_api_reference.md
=> Added native app disclaimer for pm API

_posts/01_postman/01_launching_postman/2017-05-04-navigating_postman.md, _posts/01_postman/03_collections/2017-05-04-examples.md, _posts/01_postman/06_collection_runs/2017-05-04-starting_a_collection_run.md
- add status bar to navigating postman
- update examples screenshots
=> Status bar

_posts/01_postman/04_scripts/2017-05-04-postman_sandbox_api_reference.md
* Removed duplicate `util` from native module list
* Clarified Lodash v4 usage.
=> Improved Sandbox library reference

_data/doc_map.json, _posts/01_postman/07_team_library/2017-05-04-setting_up_team_library.md, _posts/02_pro/01_managing_pro/2017-05-04-activating_trial.md, _posts/02_pro/01_managing_pro/2017-05-04-inviting_and_managing.md
- add new team library setup page
- link to new page from inviting and managing page
- link to new page from activating trial page
@66eli77 could you please review?
=> Team library

_posts/01_postman/04_scripts/2017-05-04-intro_to_scripts.md, _posts/01_postman/04_scripts/2017-05-04-pre_request_scripts.md, _posts/01_postman/04_scripts/2017-05-04-test_examples.md, _posts/01_postman/04_scripts/2017-05-04-test_scripts.md
- update test examples page with pm snippets @madebysid could you please ensure decoding and case sensitive headers are correct?
- update writing test scripts page, plus screenshots
- update screenshots on pre-request and intro to scripts page
we will update the tests section for now, and as we update pages going forward, will make sure we have the new PM API referenced.
=> New pm tests

_posts/01_postman/02_sending_api_requests/2017-05-04-capturing_http_requests.md, _posts/01_postman/02_sending_api_requests/2017-05-04-proxy.md
- add 2 notes clarifying capture proxy and system proxy usage
=> Proxy updates

_posts/01_postman/01_launching_postman/2017-05-04-postman_account.md, _posts/01_postman/07_team_library/2017-05-04-searching.md
Changed /docs to relative path.
=> Postman Accounts (switching user accounts) 3

_posts/01_postman/09_monitors/2017-05-04-intro_monitors.md
first wording update, part of larger change to come later.
=> update from "monitors" to "monitoring"

_posts/01_postman/09_monitors/2017-05-04-intro_monitors.md
Updated language to use "monitoring" as the service, "monitors" as the specific item set up within Postman.
=> Updated monitoring language

_posts/01_postman/09_monitors/2017-05-04-intro_monitors.md
changes merged to develop. Keeping this open until reviewed.
=> Update monitoring language

_posts/03_enterprise/01_sso/2017-05-04-intro_sso.md
WIP, waiting on comments on Develop branch
=> add SSO providers

_posts/01_postman/01_launching_postman/2017-11-20-newbutton.md
---
categories:
- "postman"
- "launch"
title: "New button"
page_id: "new button"
warning: false
---
=> Added page metadata

_posts/01_postman/01_launching_postman/2017-05-04-postman_account.md, _posts/01_postman/03_collections/2017-05-04-creating_collections.md
=> Creating collections Btwisted patch 4

_posts/01_postman/03_collections/2017-05-04-creating_collections.md
Replace existing content with my updates.
=> Creating collection new button

_data/doc_map.json
=> Syntax correction

_posts/01_postman/01_launching_postman/2017-11-20-newbutton.md
=> Revised page ID

_posts/01_postman/01_launching_postman/2017-05-04-newbutton.md
=> Changed file name and header metadata

_posts/01_postman/05_environments_and_globals/2017-05-04-manage_environments.md
resolving environments issues pertaining to the New button
=> btwisted- environments-edits

_posts/01_postman/05_environments_and_globals/2017-05-04-manage_environments.md
=> Btwisted environments

_posts/01_postman/08_api_documentation/2017-05-04-intro_to_api_documentation.md
Added new button functionality.
Btwisted patch 8
=> Intro to documentation

_posts/01_postman/02_sending_api_requests/2017-05-04-authorization.md
Incorporated recent ENG Input.
=> Btwisted patch 3 - Authorization

_posts/01_postman/01_launching_postman/2017-05-04-navigating_postman.md
Added new tab functionality. Need updated screen shots for Data editor section.
=> Btwisted patch 1 -Navigating Postman

_posts/01_postman/01_launching_postman/2017-05-04-navigating_postman.md
Added tab improvements. Need updated screenshots for Data editor section.
=> Update 2017-05-04-navigating_postman.md 

_posts/01_postman/07_team_library/2017-05-04-searching.md
=> Btwisted patch 12 - Searching

_posts/01_postman/07_team_library/2017-05-04-searching.md
Using different syntax for anchors.
=> Btwisted patch 12 -  Searching

_posts/02_pro/01_managing_pro/2017-05-04-activating_trial.md
screenshots and workflow change
=> Btwisted activate pro trial

_posts/01_postman/04_scripts/2017-05-04-postman_sandbox_api_reference.md
Source changeset on the parent project: https://github.com/postmanlabs/postman-sandbox/pull/243
=> Update `lodash` version to `4.17.4` in Postman Sandbox API reference

_posts/01_postman/02_sending_api_requests/2017-05-04-authorization.md, _posts/01_postman/04_scripts/2017-05-04-intro_to_scripts.md, _posts/01_postman/04_scripts/2017-05-04-pre_request_scripts.md, _posts/01_postman/04_scripts/2017-05-04-test_scripts.md, _posts/01_postman/05_environments_and_globals/2017-05-04-variables.md
add collection and folder level elements like scripts and variables to the following pages:
- variables
- tests
- pre-request
- authorization
=> Collection elements

_posts/01_postman/02_sending_api_requests/2017-05-04-authorization.md
Added different screenshot 
Added Inherit from parent setting; minor edits to new information added by jlin.
=> Btwisted Auth 120717

_posts/01_postman/02_sending_api_requests/2017-05-04-authorization.md
replaced white theme with black theme screenshots to make the look consistent. Most screenshots will be white theme in the future.
=> Btwisted auth update120817

_posts/01_postman/09_monitors/2017-05-04-setting_up_monitor.md
Setting up a monitor. Updated screenshots and workflows as needed.
=> Btwisted monitor 120917

_posts/01_postman/10_mock_servers/2017-05-04-setting_up_mock.md
Updated screenshots and workflows as needed.
=> Btwisted mock dec1017

_posts/01_postman/08_api_documentation/2017-05-04-intro_to_api_documentation.md
updated screenshots and workflow as needed.
=> Btwisted intro docs 121117

_posts/01_postman/02_sending_api_requests/2017-05-04-requests.md
Updated screenshots and workflows as needed
=> Btwisted requests 121217

_posts/01_postman/01_launching_postman/2017-05-04-newbutton.md
Updated screenshots and workflow as needed. Also added sections for Templates and the API Network.
=> Btwisted new button 121317

_posts/01_postman/05_environments_and_globals/2017-05-04-variables.md, _posts/01_postman/06_collection_runs/2017-05-04-command_line_integration_with_newman.md, _posts/01_postman/06_collection_runs/2017-05-04-working_with_data_files.md
- update data variables syntax in scripts to pm.iterationData.get()
- update variable scope hierarchy
- add screenshots
- correct user reported typo in data variables
@66eli77 please review
=> Variables 2

_posts/01_postman/09_monitors/2017-05-04-viewing_monitor_results.md
=> Btw monitoring 010318

_posts/01_postman/03_collections/2017-05-04-using_markdown_for_descriptions.md
=> Btw markdown 010218

_posts/01_postman/07_team_library/2017-05-04-activity_feed_and_restoring_collections.md
=> Btw teamlib feed010418

_posts/01_postman/08_api_documentation/2017-05-04-viewing_documentation.md
Updated screenshots. Need to rewrite the workflow.
=> Btw docs viewing010418

_posts/01_postman/08_api_documentation/2017-05-04-how_to_document_using_markdown.md
=> Btw docs markdown010418

_posts/01_postman/08_api_documentation/2017-05-04-publishing_public_docs.md
=> Btw docs pubdocs010418

_posts/01_postman/08_api_documentation/2017-05-04-adding_and_verifying_custom_domains.md
=> Btw docs add verify domain010418

_posts/01_postman/01_launching_postman/2017-05-04-syncing.md
=> Btw syncing 010218

_posts/01_postman/03_collections/2017-05-04-examples.md
=> Btw collections examples010418

_posts/01_postman/09_monitors/2017-05-04-troubleshooting_monitors.md
Added failed monitor screenshot and revised some text.
=> Btw monitoring tblshting010318

_posts/01_postman/11_postman_api/2017-05-04-intro_api.md
=> Btw postman api010318

_posts/02_pro/03_integrations/2017-05-04-pagerduty.md
=> Btwisted pagerduty update

_posts/02_pro/03_integrations/2017-05-04-github.md
=> Btwisted GitHub update

_posts/02_pro/03_integrations/2017-05-04-gitlab.md
=> Btwisted gitlab update

_posts/02_pro/03_integrations/2017-05-04-hipchat.md
=> Btwisted hipchat update

_posts/02_pro/03_integrations/2017-05-04-keen.md
=> Btwisted keen update

_posts/02_pro/03_integrations/2017-05-04-microsoft_flow.md
=> Btwisted microsoft flow update

_posts/02_pro/03_integrations/2017-05-04-slack.md
Updated screenshots and documented new workflows
=> Btwisted slack update

_posts/01_postman/03_collections/2017-05-04-using_markdown_for_descriptions.md
Updated screenshots and workflow
=> Btw markdown desc011218

_posts/02_pro/2018-01-12-upgrading_to_postman_pro_from_a_trial_team
New topic Upgrading to Pro from a trial team
=> Btw upgrading to pro011218

_posts/02_pro/2018-01-12-managing_your_team, _posts/02_pro/2018-01-12-managing_your_team.md
New topic to manage the team. The content comes from the former inviting and managing topic.
=> Btw managing team011218

_data/doc_map.json
Updating json file for new pro purchasing plan
=> Btw purchasing pro011218

_posts/01_postman/09_monitors/2017-05-04-pricing_monitors.md
=> Btw pricing monitor011218

_posts/02_pro/01_managing_pro/2018-01-12-managing_your_billing.md
Add some external links to bulleted list
=> Btw 011318 billing

_posts/02_pro/03_integrations/2017-05-04-victorops.md
Added updated screenshots and workflow. VictorOps was mistakenly not submitted on 1/13.
=> Btwisted victor ops update

_data/doc_map.json, workspaces/2018-01-22-intro_to_workspaces.md
removed url_prefix from child, Intro to Workspaces.
=> Btw workspaces pages011818

_posts/02_pro/04_api_search/2018-01-25-searching_apis.md
=> Btw api search 012418

_posts/02_pro/04_api_search/2018-01-25-searching_apis.md
approved PR to replace the flawed merge of previous branch
=> Btw api search final  012518

_posts/02_pro/01_managing_pro/2018-01-12-managing_your_billing.md
=> Btw 013018 update manage billing

_posts/01_postman/01_launching_postman/2017-05-04-postman_account.md
=> Btw 013018 postman acct

_posts/01_postman/01_launching_postman/2017-05-04-postman_account.md
@66eli77  Fixing a small typo on the Master branch this time 👍
=> Fixing small typo

_data/doc_map.json, _posts/01_postman/09_monitors/2018-02-01-monitors-history.md
=> Btw 010118 monitor history request new

_data/doc_map.json, _posts/01_postman/08_api_documentation/2017-05-04-intro_to_api_documentation.md, _posts/01_postman/09_monitors/2017-05-04-integrations_for_alerts.md, _posts/01_postman/10_mock_servers/2017-05-04-matching_algorithm.md, _posts/01_postman/10_mock_servers/2017-05-04-mock_with_api.md, _posts/01_postman/10_mock_servers/2017-05-04-mocking_with_examples.md, _posts/01_postman/10_mock_servers/2017-05-04-setting_up_mock.md, _posts/01_postman/2017-05-04-mock_servers.md, _posts/02_pro/01_managing_pro/2017-05-04-inviting_and_managing.md, _posts/02_pro/01_managing_pro/2018-01-12-managing_your_team.md, _posts/02_pro/02_pro_api/2017-05-04-continuous_integration.md, _posts/02_pro/02_pro_api/2017-05-04-intro_api.md, _posts/02_pro/2015-05-04-what_is_pro.md, _posts/04_postman_for_publishers/2017-05-04-public_api_docs.md
- update mocks are public by default, no api key required
- add mocks headers for example name and uid
- correct "Postman Pro API" to "Postman API"
@66eli77 please review
=> Mocks update

_posts/01_postman/09_monitors/2017-05-04-viewing_monitor_results.md
=> Btw 020518 viewing monitors  update

_posts/01_postman/02_sending_api_requests/2017-05-04-interceptor_extension.md
=> Btw priority 1 touchups

_posts/01_postman/12_workspaces/2018-01-22-using_workspaces.md
=> Btw vineet workspaces feedback

_posts/01_postman/01_launching_postman/2017-05-04-navigating_postman.md, _posts/01_postman/02_sending_api_requests/2017-05-04-capturing_http_requests.md, _posts/01_postman/02_sending_api_requests/2017-05-04-interceptor_extension.md, _posts/01_postman/03_collections/2017-05-04-managing_collections.md, _posts/01_postman/12_workspaces/2018-01-22-using_workspaces.md
=> Btw priority1 021918

_posts/01_postman/08_api_documentation/2017-05-04-adding_and_verifying_custom_domains.md, _posts/01_postman/08_api_documentation/2017-05-04-adding_team_name_and_logo.md, _posts/01_postman/08_api_documentation/2017-05-04-environments_and_environment_templates.md, _posts/01_postman/08_api_documentation/2017-05-04-how_to_document_using_markdown.md, _posts/01_postman/08_api_documentation/2017-05-04-intro_to_api_documentation.md, _posts/01_postman/08_api_documentation/2017-05-04-publishing_public_docs.md
=> Btw workspaces priority 2

_data/v6_map.json, v6/pro/workspaces_workaround_for_version_5.5_and_below.md
added pro workspaces workaround
=> Btw v6 pro workaround

_data/v6_map.json
deleted team library from version 6
=> Btw delete teamlibrary v6

_data/v6_map.json, v6/enterprise/apply_for_beta_access.md, v6/enterprise/audit_logs.md, v6/enterprise/sso/admin_sso.md
=> Btw enterprise update 030218

v6/pro/managing_pro/managing_your_team.md
revised workflow and screenshots for Managing your Team.
=> Btw postprod v6

v6/postman/workspaces/intro_to_workspaces.md
Minor edits to Intro to Workspaces per ashley.
=> Btw intro ws revisions

v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/collection_runs/integration_with_jenkins.md, v6/postman/collections/data_formats.md, v6/postman/collections/sharing_collections.md, v6/postman/workspaces/creating_workspaces.md, v6/postman/workspaces/managing_workspaces.md, v6/postman/workspaces/using_workspaces.md
Sharing collections: corrected misspell
Data formats: applied hyperlinks to text 
Environments and environments templates: replaced Team Library to team Workspace
Creating Workspaces: modify capitalizations of Workspace
Managing Workspaces: modify capitalizations of Workspace
Using Workspaces: modify capitalizations of Workspace
=> Btw correction multiple 031618

_data/v6_map.json, v6/enterprise/apply_for_beta_access.md
Removed the "Apply for beta access" topic from Enterprise--the topic itself and the json.map entry.
=> Btw remove ent beta

v6/postman/launching_postman/postman_account.md
Inserted additional steps to indicate how to navigate to the Team settings page in the "Postman account" topic. Per [CON-262](https://postmanlabs.atlassian.net/browse/CON-262)
=> Btw pmacct navigate to team page

v6/postman/collections/sharing_collections.md
Updated this topic to reflect the workspaces workflow to share collections.
=> Btw sharing collections update032118

v6/postman/api_documentation/intro_to_api_documentation.md
updated doc view limits for private and public docs
=> Btw doc limit update2

v6/postman/api_documentation/intro_to_api_documentation.md, v6/postman/collections/sharing_collections.md
added modifying team permissions section.
=> Btw modify permissions update032618

v6/postman/sending_api_requests/requests.md
Fixed broken links and ill formed formatting.
=> Btw requests fix 032818

_data/v6_map.json, v6/postman/team_library/conflicts.md
Added 'Conflicts' to the Workspace topic. Minor edits to content. Updated json.map. Per jira ticket: https://postmanlabs.atlassian.net/browse/CON-284
=> Btw add conflicts to workspaces

v6/postman/mock_servers/setting_up_mock.md
Added content for public/private mocks.
=> Btw mocks pri pub update

v6/postman/launching_postman/sending_the_first_request.md
Revised the content and added more images
=> Btw sending request revisios

_data/v6_map.json, v6/postman/launching_postman/creating_the_first_collection.md
Revised content; added new images; and updated v6 json.map.
=> Btw creating collection revision

_data/v6_map.json, v6/postman/collection_runs/intro_to_collection_runs.md, v6/postman/mock_servers/intro_to_mock_servers.md, v6/postman/mock_servers/setting_up_mock.md
Added new topic: Intro to mock servers, updated v6 json.map, revised Setting up a mock server.
=> Btw intro mock servers new

_data/v6_map.json, v6/postman/collections/creating_collections.md, v6/postman/collections/intro_to_collections.md
Created a new intro topic for collections; v6 json.map updated in another PR.
=> Btw intro creating collections

v6/postman/api_documentation/intro_to_api_documentation.md
add new content to Intro to Publishing page
@staysea please review 🍰
=> add section about linking to sections within documentation

_config.yml, v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/environments_and_globals/manage_environments.md, v6/postman/environments_and_globals/variables.md, v6/postman/mock_servers.md, v6/postman/mock_servers/mock_with_api.md, v6/postman/team_library/setting_up_team_library.md, v6/postman/team_library/sharing.md, v6/postman_for_publishers/run_button/environments_run_button.md
Reverts postmanlabs/postman-docs#1279
=> Revert "Remove references to "environment template""

_config.yml, _data/v6_map.json, v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/environments_and_globals/manage_environments.md, v6/postman/environments_and_globals/variables.md, v6/postman/mock_servers.md, v6/postman/mock_servers/mock_with_api.md, v6/postman/team_library/setting_up_team_library.md, v6/postman/team_library/sharing.md, v6/postman_for_publishers/run_button/environments_run_button.md
- update v5 search index in config
- update environment "template" terminology to "shared environments"
- fix v6 broken links, formatting, typos
=> Remove template 2

v6/pro/integrations/github.md
Divided the doc into two headings, how to generate access token on github and how to configure it on postman. Also, added another screenshot of the dashboard.
=> Refactored the GitHub integration doc

_data/v6_map.json, v6/postman/environments_and_globals/intro_to_environments_and_globals.md, v6/postman/environments_and_globals/manage_environments.md, v6/postman/environments_and_globals/manage_globals.md, v6/postman/environments_and_globals/variables.md
Added an intro topic, added topic to v6 JSON map, and reformatted other topics under this category.
=> Btw intro to environments global

v6/getting_started/updating.md, v6/postman/collections/sharing_collections.md, v6/postman/launching_postman/installation_and_updates.md, v6/postman/launching_postman/postman_account.md, v6/postman/workspaces/creating_workspaces.md, v6/postman/workspaces/using_workspaces.md, v6/pro/managing_pro/managing_your_team.md, v6/pro/managing_pro/team_settings.md
Update for docs 6.1, see jira tickets here:
[https://postmanlabs.atlassian.net/browse/CON-328](https://postmanlabs.atlassian.net/browse/CON-328)
[https://postmanlabs.atlassian.net/browse/CON-329](https://postmanlabs.atlassian.net/browse/CON-329)
[https://postmanlabs.atlassian.net/browse/CON-330](https://postmanlabs.atlassian.net/browse/CON-330)
[https://postmanlabs.atlassian.net/browse/PRODASH-963](https://postmanlabs.atlassian.net/browse/PRODASH-963)
=> Paul docs update 6.1 may 7

_data/v6_map.json, v6/postman/workspaces/activity_feed_and_restoring_collections.md, v6/postman/workspaces/conflicts.md, v6/postman/workspaces/creating_workspaces.md, v6/postman/workspaces/intro_to_workspaces.md, v6/postman/workspaces/managing_workspaces.md, v6/postman/workspaces/using_workspaces.md
- Add private workspaces
- Reconfigure workspaces section
- Add back activity feed page
=> Private workspaces

v6/enterprise/purchasing_enterprise.md, v6/postman/launching_postman/installation_and_updates.md, v6/pro/managing_pro/managing_your_billing.md, v6/pro/managing_pro/purchasing_pro.md, v6/pro/managing_pro/upgrading_to_postman_pro_from_a_trial_team.md
updates to troubleshooting update instructions 6.1, and refreshing screenshots/pricing for new model
=> Troubleshooting and partial pricing screenshots

v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/api_documentation/intro_to_api_documentation.md, v6/postman/api_documentation/publishing_public_docs.md, v6/postman/api_documentation/viewing_documentation.md, v6/postman/collections/managing_collections.md, v6/postman/launching_postman/navigating_postman.md, v6/postman/launching_postman/newbutton.md, v6/postman/mock_servers/mocking_with_examples.md, v6/postman/team_library/activity_feed_and_restoring_collections.md, v6/postman/workspaces/activity_feed_and_restoring_collections.md
- Reconfigure API documentation section
- Add API Network self-serve checkbox
=> API network self serve

v6/postman/monitors/faqs_monitors.md, v6/postman/monitors/intro_monitors.md, v6/postman/monitors/pricing_monitors.md
update monitoring with Enterprise free limit and new block size.
=> kasey monitor pricing update

v6/postman/monitors/intro_monitors.md
Updated the total monitor run time from two (2) minutes to five (5).
=> Update to intro_monitors.md

v6/pro/managing_pro/activating_trial.md
Reverts postmanlabs/postman-docs#1370
=> Revert "Delete activating_trial.md"

v6/postman/launching_postman/postman_account.md
=> Removed turn off sync bullet - 1377

v6/postman/launching_postman/postman_account.md
Fixed, please review and close
=> added workspaces to the list - gh-1376

v6/postman/launching_postman/syncing.md
=> Added History and Workspaces to list - 1378

v6/postman/launching_postman/settings.md
Please review and provide feedback
=> Fixed Editor Font Size issue - 1381

v6/postman/launching_postman/settings.md
Fixed the issue, Please review and provide feedback
=> Removed Incorrect Ref to client certificates - 1379

v6/postman/launching_postman/settings.md, v6/postman/launching_postman/syncing.md
Please review and let me know any feedback comments.
=> Removed Disabling Sync information - 1383

v6/postman/launching_postman/creating_the_first_collection.md
Please review and provide feedback
=> Fixed the Save button issue - 1374

v6/postman/launching_postman/creating_the_first_collection.md
=> collection sidebar added - 1375

v6/postman/environments_and_globals/manage_environments.md
Updated Editing an Active environment section with the new screen shot
=> Updated Edit Env screen having current val field

v6/postman/launching_postman/syncing.md
=> Updated Deleting Postman Account section - 1380

v6/postman/launching_postman/creating_the_first_collection.md
=> Updated the Save Request dialog - 1373

v6/postman/launching_postman/sending_the_first_request.md
=> Updated Save Request dialog - 1391

v6/postman/collection_runs/working_with_data_files.md
Hi, Preetham,
Please review the changes to the docs.
=> Updating docs for Importing Error #4588

v6/postman/launching_postman/installation_and_updates.md
=> Menu Bar section updated

v6/postman/environments_and_globals/variables.md, v6/postman/launching_postman/newbutton.md
In the first paragraph of Create New section, a new para is introduced...
Blocks are incorrectly mentioned as features....rewrote this part.... 
and updated two snapshots....
=> Made Changes in newbutton.md

v6/postman/mock_servers/intro_to_mock_servers.md, v6/postman/workspaces/intro_to_workspaces.md
Removed instances of word paid from Mock Servers and Team Workspaces
=>  Mock Servers, Team Workspaces talk about Pro and Enterprise users

v6/postman/mock_servers/mocking_with_examples.md
The matching query params feature is now documented. You can review and provide feedback. In the prod, it appears like this:
=> Matching q params mocks

_data/v6_map.json, v6/pro/integrations/webhooks.md
=> Webhooks Integrations added

v6/postman/collections/managing_collections.md
Please review and approve the doc for this feature...
=> Trash feature

_data/v6_map.json, v6/postman/find_replace.md
Hi, Prashant,
Please review and provide your feedback for this feature. If you're okay with the content, please approve the PR.
=> Find and Replace

_data/v6_map.json, v6/postman/customizing_postman.md, v6/postman/sending_api_requests/requests.md
Harry, please review the first draft. I have so many doubts still. Let's discuss..
=> Custom methods

v6/pro/integrations/gitlab.md
Preetham, please review this and provide your f/b comments
=> Gitlab - Custom Domain

v6/postman/monitors/setting_up_monitor.md
Please review and provide your f/b comments
=> Change monitor

_data/v6_map.json, v6/postman/collections/working_with_openAPI.md, v6/postman/collections/working_with_openAPIs.md
Abhijit, please review and provide f/b comments on this...
=> Swagger OAS 3.0 Docs

_data/v6_map.json, v6/postman/collections/commenting_on_collections.md
=> Commenting on Request & Collections

v6/postman/scripts/postman_sandbox.md, v6/postman/scripts/postman_sandbox_api_reference.md, v6/postman/scripts/test_examples.md
=> Ajv Docs Update

v6/postman/api_documentation/adding_and_verifying_custom_domains.md, v6/postman/api_documentation/adding_team_name_and_logo.md, v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/api_documentation/how_to_document_using_markdown.md, v6/postman/api_documentation/intro_to_api_documentation.md, v6/postman/api_documentation/publishing_public_docs.md, v6/postman/api_documentation/viewing_documentation.md
=> API Chapter Updates

v6/postman/sending_api_requests/working_with_tabs.md
Hey Vineet,
You can view the gif files now.
=> Tabs updated

v6/pro/managing_pro/billing_and_pricing.md
Discussed with Sanjeev - we'll include this only in 1:1 support conversations, not here.
=> Removing refund policy from a public-facing page

v6/postman/monitors/monitoring_apis_websites.md
=>  Markdown issue in monitors chap

_data/v6_map.json, v6/postman/migrating_to_v7.0.md, v6/postman/migrating_to_v7.md, v6/postman/roles_and_permissions.md
=>  Roles and permissions

v6/postman/roles_and_permissions.md
Fixed the image issue pointed by Abhijit
=> RBAC Image Bug

v6/postman/workspaces/activity_feed_and_restoring_collections.md, v6/postman/workspaces/creating_workspaces.md, v6/postman/workspaces/intro_to_workspaces.md, v6/postman/workspaces/managing_workspaces.md, v6/postman/workspaces/using_workspaces.md
=> Workspaces chap updates

v6/postman/collections/managing_collections.md, v6/postman/collections/sharing_collections.md, v6/postman/workspaces/creating_workspaces.md, v6/postman/workspaces/intro_to_workspaces.md, v6/postman/workspaces/managing_workspaces.md
=> RBAC User Guide Changes

v6/postman/sending_api_requests/requests.md
=> Content type in form data

v6/postman/environments_and_globals/sessions.md, v6/postman/environments_and_globals/variables.md
Hey, 
Can you please review and approve?
=> Session faq link and Note

_includes/_search.html
We pay for the Algolia search, so removing the logo.
=> Updated poweredBy to false to remove Algolia logo

v6/postman/launching_postman/newbutton.md
=> Link Issues - Jlin 

v6/postman/launching_postman/newbutton.md
Joyce, Can you review and approve this PR? Let me know if you need me to add anything else.
=> Templates Doc Update

v6/postman/api_documentation/publishing_public_docs.md
=> Ellipsis Singular

v6/postman/api_documentation/adding_and_verifying_custom_domains.md, v6/postman/monitors/viewing_monitor_results.md
Abhijit,
Can you please review and approve this?
=> CAA records fix

v6/postman/launching_postman/installation_and_updates.md, v6/postman/roles_and_permissions.md
Updated as per stacee's feedback.
=> Chrome App Deprecated

v6/postman/monitors/integrations_for_alerts.md
The API link was broken, and I also added a link to the Custom Webhooks page. Resolves issue #1568.
=> #1568 remove 'Coming soon' and updated links

v6/postman/collections/commenting_on_collections.md
=> Clarify commenting

v6/postman/collections/data_formats.md
— converted kramdown table formatting to markdown
— fixes #1543, and relates to part of #1438
=> fixed table layout

_data/v6_map.json, v6/postman/environments_and_globals/variables_complete_reference.md
Hi, Numaan,
Please review and provide f/b.
=> Variables Reference Doc

v6/api_testing_and_collection_runner/sandbox.md, v6/postman/scripts/postman_sandbox_api_reference.md
- Changed the numbered list to a bullet point list for consistency
- Added links to the available NodeJs modules
- Extracted the `pm.test()` info out of the `pm.cookies()` section
- Added the language to the code blocks
- Fixed the code in the first example
=> Spelling, Grammar and Formatting changes

v6/postman/working_with_APIs/introduction_to_apis.md
Fixed typos
Removed Sample use case link
=> Basic fixes

v6/pro/managing_pro/managing_your_team.md
As per gh-1537, I updated the docs. If you review I can merge the PR.
=> Gh 1537 - Updated Roles in Postman

v6/postman/design_and_develop_apis/sharing_apis.md, v6/postman/sending_api_requests/requests.md
In response to gh-Issue1575, the fix is available in this PR.
=> Params button to params tab change update

v6/postman/scripts/postman_sandbox.md
Mainly doing this to trigger webhook and hopefully pull this page anew. This should fix issue #1597 by regenerating this page content and redeploy it to Prod.
=> 1597- fixed spacing

v6/postman/launching_postman/newbutton.md
This fixes issue #1553 
— updated anchor links
— updated hrefs (many 404'd)
=> 1553 updated links on New Button page

v6/postman/launching_postman/settings.md
This fixes issue #1624 
— updated links
=> 1624 updated links on Postman Settings page

v6/postman/team_library/sharing.md
Fixed issue related to gh-1495
=> Link in Team Library chapter

v6/pro/integrations/intro_integrations.md
Replaced them with new screens.
=> Old Dashboard Screens

v6/pro/what_is_pro.md
Fixes issue #1642 
— fixed 404 link
— updated other links (redirecting)
— updated bullet points
=> 1642 updated links and copy

v6/postman/collections/data_formats.md
RAML 1.0 import isn't supported yet.
=> Updating RAML docs to say `coming soon`

v6/postman/monitors/intro_monitors.md
This fixes issue #1680 
— fixed broken link address in issue
— fixed redirecting links to use resolved URL
— update headings to use H1 > H2 > H3 hierarchy
=> Fixed 404 link + redirecting links; updated hierarchy

v6/postman/design_and_develop_apis/the_api_workflow.md
Adding a new section to API chapter
=> Generate collections from schema section

v6/postman/launching_postman/settings.md, v6/settings/settings.md
Added description for "max response size" option in the settings window.
=> [RUNTIME-937] Add settings docs for Max Response Size

README.md
- Changed h3 titles to h2
- Fixed a few linting errors, doc now passes linter
=> changed titles and fixed linting errors

v6/postman/workspaces/using_workspaces.md
Fixes issue #1739 
— fixed numerous linting errors
=> #1739 - fixed linting issues

v6/postman/workspaces/conflicts.md
fixed linter errors in issue number #1736
=> #1736 - fixed linting errors

v6/postman/collections/data_formats.md
Fixes Issue #1726 
— updated broken img and img link
— fixed linter errors
— fixed duplicate heading
— linter / prettyfier adjusted tables and unordered lists
=> 1726 fixed img, linter errors, and duplicate heading

v6/postman/scripts/postman_sandbox_api_reference.md
Added the new "cookieJar" methods to the postman sandbox references API list.
=> RUNTIME-942 Added new cookieJar methods

v6/postman/workspaces/intro_to_workspaces.md
changed headers from h3 to h2 and fixed linting issues
=> 1737 linting fixes

v6/postman/collection_runs/building_workflows.md, v6/postman/collection_runs/command_line_integration_with_newman.md, v6/postman/collection_runs/debugging_a_collection_run.md, v6/postman/collection_runs/integration_with_jenkins.md, v6/postman/collection_runs/integration_with_travis.md, v6/postman/collection_runs/intro_to_collection_runs.md, v6/postman/collection_runs/newman_with_docker.md, v6/postman/collection_runs/running_multiple_iterations.md, v6/postman/collection_runs/sharing_a_collection_run.md, v6/postman/collection_runs/starting_a_collection_run.md, v6/postman/collection_runs/using_environments_in_collection_runs.md, v6/postman/collection_runs/working_with_data_files.md
=> 1749 collection runs linting fixes

v6/postman/api_documentation/adding_and_verifying_custom_domains.md, v6/postman/api_documentation/adding_team_name_and_logo.md, v6/postman/api_documentation/environments_and_environment_templates.md, v6/postman/api_documentation/how_to_document_using_markdown.md, v6/postman/api_documentation/intro_to_api_documentation.md, v6/postman/api_documentation/publishing_public_docs.md, v6/postman/api_documentation/viewing_documentation.md
changed headers from h3 to h2 and fixed linting issues
=> 1749 api documentation linting fixes

v6/postman/collections/commenting_on_collections.md, v6/postman/collections/creating_collections.md, v6/postman/collections/data_formats.md, v6/postman/collections/examples.md, v6/postman/collections/intro_to_collections.md, v6/postman/collections/managing_collections.md, v6/postman/collections/sharing_collections.md, v6/postman/collections/using_markdown_for_descriptions.md, v6/postman/collections/version_control_for_collections.md, v6/postman/collections/working_with_openAPI.md
=> 1749 collections linting fixes

v6/postman/collections/commenting_on_collections.md, v6/postman/collections/creating_collections.md, v6/postman/collections/data_formats.md, v6/postman/collections/examples.md, v6/postman/collections/intro_to_collections.md, v6/postman/collections/managing_collections.md, v6/postman/collections/sharing_collections.md, v6/postman/collections/using_markdown_for_descriptions.md, v6/postman/collections/version_control_for_collections.md, v6/postman/collections/working_with_openAPI.md, v6/postman/design_and_develop_apis/introduction_to_apis.md, v6/postman/design_and_develop_apis/managing_apis.md, v6/postman/design_and_develop_apis/reporting_faqs.md, v6/postman/design_and_develop_apis/sharing_apis.md, v6/postman/design_and_develop_apis/the_api_workflow.md, v6/postman/design_and_develop_apis/versioning_an_api.md, v6/postman/design_and_develop_apis/view_and_analyze_api_reports.md
=> 1749 design and develop apis linting fixes

v6/postman/collections/commenting_on_collections.md, v6/postman/collections/creating_collections.md, v6/postman/collections/data_formats.md, v6/postman/collections/examples.md, v6/postman/collections/intro_to_collections.md, v6/postman/collections/managing_collections.md, v6/postman/collections/sharing_collections.md, v6/postman/collections/using_markdown_for_descriptions.md, v6/postman/collections/version_control_for_collections.md, v6/postman/collections/working_with_openAPI.md, v6/postman/design_and_develop_apis/introduction_to_apis.md, v6/postman/design_and_develop_apis/managing_apis.md, v6/postman/design_and_develop_apis/reporting_faqs.md, v6/postman/design_and_develop_apis/sharing_apis.md, v6/postman/design_and_develop_apis/the_api_workflow.md, v6/postman/design_and_develop_apis/versioning_an_api.md, v6/postman/design_and_develop_apis/view_and_analyze_api_reports.md, v6/postman/environments_and_globals/intro_to_environments_and_globals.md, v6/postman/environments_and_globals/manage_environments.md, v6/postman/environments_and_globals/manage_globals.md, v6/postman/environments_and_globals/sessions.md, v6/postman/environments_and_globals/variables.md, v6/postman/environments_and_globals/variables_complete_reference.md, v6/postman/environments_and_globals/variables_list.md
=> 1749 environments and globals linting fixes

v6/postman/collections/commenting_on_collections.md, v6/postman/collections/creating_collections.md, v6/postman/collections/data_formats.md, v6/postman/collections/examples.md, v6/postman/collections/intro_to_collections.md, v6/postman/collections/managing_collections.md, v6/postman/collections/sharing_collections.md, v6/postman/collections/using_markdown_for_descriptions.md, v6/postman/collections/version_control_for_collections.md, v6/postman/collections/working_with_openAPI.md, v6/postman/design_and_develop_apis/introduction_to_apis.md, v6/postman/design_and_develop_apis/managing_apis.md, v6/postman/design_and_develop_apis/reporting_faqs.md, v6/postman/design_and_develop_apis/sharing_apis.md, v6/postman/design_and_develop_apis/the_api_workflow.md, v6/postman/design_and_develop_apis/versioning_an_api.md, v6/postman/design_and_develop_apis/view_and_analyze_api_reports.md, v6/postman/environments_and_globals/intro_to_environments_and_globals.md, v6/postman/environments_and_globals/manage_environments.md, v6/postman/environments_and_globals/manage_globals.md, v6/postman/environments_and_globals/sessions.md, v6/postman/environments_and_globals/variables.md, v6/postman/environments_and_globals/variables_complete_reference.md, v6/postman/environments_and_globals/variables_list.md, v6/postman/postman_api/continuous_integration.md, v6/postman/postman_api/intro_api.md
=> 1749 postman api linting fixes

v6/postman/monitors/faqs_monitors.md, v6/postman/monitors/integrations_for_alerts.md, v6/postman/monitors/intro_monitors.md, v6/postman/monitors/monitoring_apis_websites.md, v6/postman/monitors/pricing_monitors.md, v6/postman/monitors/setting_up_monitor.md, v6/postman/monitors/troubleshooting_monitors.md, v6/postman/monitors/viewing_monitor_results.md
=> 1749 monitors linting fixes

v6/postman/monitors/faqs_monitors.md, v6/postman/monitors/integrations_for_alerts.md, v6/postman/monitors/intro_monitors.md, v6/postman/monitors/monitoring_apis_websites.md, v6/postman/monitors/pricing_monitors.md, v6/postman/monitors/setting_up_monitor.md, v6/postman/monitors/troubleshooting_monitors.md, v6/postman/monitors/viewing_monitor_results.md, v6/postman/scripts/branching_and_looping.md, v6/postman/scripts/intro_to_scripts.md, v6/postman/scripts/pre_request_scripts.md, v6/postman/scripts/test_scripts.md
=> 1749 scripts linting fixes

v6/postman/monitors/faqs_monitors.md, v6/postman/monitors/integrations_for_alerts.md, v6/postman/monitors/intro_monitors.md, v6/postman/monitors/monitoring_apis_websites.md, v6/postman/monitors/pricing_monitors.md, v6/postman/monitors/setting_up_monitor.md, v6/postman/monitors/troubleshooting_monitors.md, v6/postman/monitors/viewing_monitor_results.md, v6/postman/scripts/branching_and_looping.md, v6/postman/scripts/intro_to_scripts.md, v6/postman/scripts/pre_request_scripts.md, v6/postman/scripts/test_scripts.md, v6/postman/team_library/activity_feed_and_restoring_collections.md, v6/postman/team_library/conflicts.md, v6/postman/team_library/searching.md, v6/postman/team_library/setting_up_team_library.md, v6/postman/team_library/sharing.md
=> 1749 team library linting fixes

v6/postman/scripts/branching_and_looping.md, v6/postman/scripts/intro_to_scripts.md, v6/postman/scripts/pre_request_scripts.md, v6/postman/scripts/test_scripts.md, v6/postman/team_library/activity_feed_and_restoring_collections.md, v6/postman/team_library/conflicts.md, v6/postman/team_library/searching.md, v6/postman/team_library/setting_up_team_library.md, v6/postman/team_library/sharing.md, v6/postman/workspaces/activity_feed_and_restoring_collections.md, v6/postman/workspaces/creating_workspaces.md, v6/postman/workspaces/managing_workspaces.md, v6/postman/workspaces/sharing_collections_in_workspaces_for_version_5.md, v6/postman/workspaces/using_workspaces.md
=> 1749 workspaces linting fixes

v6/postman/collection_runs/running_multiple_iterations.md, v6/postman/scripts/postman_sandbox_api_reference.md
This PR adds pm.iterationData methods under "running multiple iterations" page, describing all the methods accessible by the iterationData object that can be used during collection runs.
=> [Runtime-1061] Collection runner: Added iterationData methods

v6/postman/collection_runs/running_multiple_iterations.md, v6/postman/collection_runs/starting_a_collection_run.md, v6/postman/collection_runs/using_environments_in_collection_runs.md, v6/postman/collection_runs/working_with_data_files.md
The obsolete screenshots and syntax for test script in postman app used in documentation have been replaced with the latest ones.
=>  Update outdated screenshots

v6/postman/scripts/branching_and_looping.md, v6/postman/scripts/postman_sandbox_api_reference.md, v6/postman/scripts/test_scripts.md
Issues fixed:
Devrel-22: Mentioned a way to loop on the current request.
Devrel-23: Updated outdated screenshot on Test Scripts page.
Devrel-24: Added pm.variables.set() to sandbox api reference.
Note: Needs screenshot upload before merge.
Fixes #1709
=> Minor documentation fixes

v6/postman/environments_and_globals/variables.md
=> [1782] updated slash

v6/postman/launching_postman/newbutton.md, v6/postman_for_publishers/api_network/add_api_network.md
@kaustavdm @tristandenyer please review 🦐
=> Feature/api network 1.0

v6/pro/api_search/searching_apis.md, v6/pro/integrations/apimatic.md, v6/pro/integrations/bigpanda.md, v6/pro/integrations/coralogix.md, v6/pro/integrations/datadog.md, v6/pro/integrations/dropbox.md, v6/pro/integrations/github.md, v6/pro/integrations/gitlab.md, v6/pro/integrations/hipchat.md, v6/pro/integrations/intro_integrations.md, v6/pro/integrations/keen.md, v6/pro/integrations/microsoft_flow.md, v6/pro/integrations/microsoft_teams.md, v6/pro/integrations/pagerduty.md, v6/pro/integrations/slack.md, v6/pro/integrations/victorops.md, v6/pro/integrations/webhooks.md, v6/pro/managing_pro/billing_and_pricing.md, v6/pro/managing_pro/buying.md, v6/pro/managing_pro/changing_your_plan.md, v6/pro/managing_pro/inviting_and_managing.md, v6/pro/managing_pro/managing_your_billing.md, v6/pro/managing_pro/managing_your_team.md, v6/pro/managing_pro/purchasing_pro.md, v6/pro/managing_pro/team_settings.md, v6/pro/managing_pro/upgrading_to_postman_pro_from_a_trial_team.md, v6/pro/pro_api/continuous_integration.md, v6/pro/pro_api/intro_api.md, v6/pro/what_is_pro.md
linting errors I could not solve: 
- intro_integrations.md: '?' in heading is not allowed
- inviting_and_managing.md & managing_your_team.md: how to add a new line in a table without <br>
- bigpanda.md: has the same title twice
=> [LC-13] fixed linting errors in v6 "pro" folder

v6/postman_for_publishers/api_network/api_submission_guidelines.md
=> Fix broken link in API Network submission guidelines

v6/postman/mock_servers/setting_up_mock.md
Add info on editing Mocks in the Setting up Mocks page.
[Rendered](https://github.com/postmanlabs/postman-docs/blob/feature/DEVREL-16-mock-edit/v6/postman/mock_servers/setting_up_mock.md#editing-mock-servers)
=> [DEVREL-16] Document edit options for Mocks

CODE_OF_CONDUCT.md
=> Fix typo in CODE_OF_CONDUCT.md

v6/postman/scripts/postman_sandbox_api_reference.md
Added the pm.request method descriptions.
Fixes #1799
=> GH-1799 Added description for methods provided by pm.request object.

v6/enterprise/audit_logs.md
if this works then our develop branch pipeline is correctly configured
=> removing test commas

.github/workflows/ci.yml
=> changed github actions branch

v6/postman/scripts/postman_sandbox_api_reference.md
Added descriptions for local, environment and global variable methods.
=> GH-1566 Added descriptions for variables

CONTRIBUTING.md, README.md
fix of #1825 
fixed link on README.md and on CONTRIBUTING.md
=> fixed link to code of conduct

CONTRIBUTING.md, README.md, v5/postman/team_library/sharing.md, v6/postman/scripts/postman_sandbox_api_reference.md
fixes broken Code of Conduct links in README.md and CONTRIBUTING.md
=> fixed links #1826

v6/postman/sending_api_requests/requests.md
This pull request adds documentation around the request configuration tab.
It follows the newly adopted git flow. Raised in place of #1816.
=> Added request configuration documentation and screenshot.

v6/postman/mock_servers/setting_up_mock.md
Updates to the "Setting up a mock server" page with the following points:
- Rewrote introduction section
- Rewrote in-app mock creation section
- Reorder headings
- Update screenshots
- Add a `gif` for the simplest mock creation CNX flow in-app
- Add a section for mock creation flow from the web dashboard
[**Rendered**](https://github.com/postmanlabs/postman-docs/blob/feature/DEVREL-20-mock-creation-flow/v6/postman/mock_servers/setting_up_mock.md)
=> [DEVREL-20] Update content for mock creation flow

v6/postman/mock_servers/intro_to_mock_servers.md
Just a little fix, thank you for your brilliant documentation!
=> [intro_to_mock_servers.md] fix typo

v6/postman/launching_postman/navigating_postman.md, v6/postman/sending_api_requests/certificates.md, v6/postman/sending_api_requests/debugging_and_logs.md
This pull request adds information around the new postman console, along with the screenshots and updates the relevant places in the docs.
=> Documentation around the new Postman console.

v6/postman/sending_api_requests/visualizer.md
- Adds debugging info for visualizers.
- Fixes #1810 by removing too much information.
=> Fix minor visualizer issue and add debugging info

v6/postman/sending_api_requests/proxy.md
This pull request updates the documentation and screenshots around the proxy settings.
=> Updated documentation and screenshots for proxy settings.

v6/postman/sending_api_requests/authorization.md
This PR adds the documentation and screenshots around Akmai EdgeGrid authorization method. 
Screenshots upload pending.
=> Documentation and screenshot around EdgeGrid

v6/postman/launching_postman/syncing.md
Fixes #1812 (link url here https://learning.getpostman.com/docs/postman/launching_postman/syncing/#sign-out)
Hope everything looks ok 🙂
=> Update team sign out link

v6/postman/launching_postman/installation_and_updates.md
=> Added section for troubleshooting updates

src/components/seo.jsx, src/pages/404.jsx, src/pages/concepts.jsx, src/pages/getting-started.jsx, src/pages/index.jsx, src/pages/landing.jsx, src/pages/reference.jsx, src/templates/doc.jsx
=> adding canonical URL to all pages

src/components/Header/Header.jsx, src/pages/docs/postman-pro/integrations/apimatic.md, src/pages/docs/postman-pro/integrations/bigpanda.md, src/pages/docs/postman-pro/integrations/datadog.md, src/pages/docs/postman-pro/integrations/dropbox.md, src/pages/docs/postman-pro/integrations/github.md, src/pages/docs/postman-pro/integrations/gitlab.md, src/pages/docs/postman-pro/integrations/hipchat.md, src/pages/docs/postman-pro/integrations/intro-integrations.md, src/pages/docs/postman-pro/integrations/keen.md, src/pages/docs/postman-pro/integrations/microsoft-flow.md, src/pages/docs/postman-pro/integrations/microsoft-teams.md, src/pages/docs/postman-pro/integrations/pagerduty.md, src/pages/docs/postman-pro/integrations/slack.md, src/pages/docs/postman-pro/integrations/victorops.md, src/pages/docs/postman-pro/managing-pro/managing-your-billing.md, src/pages/docs/postman-pro/managing-pro/managing-your-team.md, src/pages/docs/postman-pro/managing-pro/migrating-to-v7.md, src/pages/docs/postman-pro/managing-pro/purchasing-pro.md, src/pages/docs/postman-pro/managing-pro/roles-and-permissions.md, src/pages/docs/postman-pro/managing-pro/team-settings.md, src/pages/docs/postman-pro/managing-pro/upgrading-to-postman-pro-from-a-trial-team.md, src/pages/docs/postman-pro/what-is-pro.md
completed contextual links in postman pro folder
=> Contextual links pro

legacy-documentation/v5/postman/api_documentation/adding_team_name_and_logo.md, legacy-documentation/v5/postman/api_documentation/environments_and_environment_templates.md, src/pages/docs/postman-for-publishers/public-api-docs.md, src/pages/docs/postman-for-publishers/run-button/creating-run-button.md, src/pages/docs/postman-for-publishers/run-button/environments-run-button.md, src/pages/docs/postman-for-publishers/run-button/run-button-API.md, src/pages/docs/postman-for-publishers/run-button/security.md, src/pages/docs/postman-for-publishers/run-button/using-run-button.md
completed contextual links for postman for publishers folder
=> Contextual links publishers

src/pages/docs/postman-enterprise/audit-logs.md, src/pages/docs/postman-enterprise/intro-to-enterprise.md, src/pages/docs/postman-enterprise/purchasing-enterprise.md, src/pages/docs/postman-enterprise/sso/admin-sso.md, src/pages/docs/postman-enterprise/sso/intro-sso.md, src/pages/docs/postman-enterprise/sso/microsoft-adfs.md, src/pages/docs/postman-enterprise/sso/saml-duo.md, src/pages/docs/postman-enterprise/sso/saml-gsuite.md, src/pages/docs/postman-enterprise/sso/saml-in-azure-ad.md, src/pages/docs/postman-enterprise/sso/saml-okta.md, src/pages/docs/postman-enterprise/sso/saml-onelogin.md, src/pages/docs/postman-enterprise/sso/saml-ping.md, src/pages/docs/postman-enterprise/sso/user-sso.md, src/pages/docs/postman-enterprise/using-static-IPs-to-monitor.md
completed contextual links in enterprise folder
=> Contextual links enterprise

src/components/ContextualLinks/ContextualLinks.scss, src/components/MarketingPages/Hero.scss, src/components/layout.scss, src/components/seo.jsx, src/templates/doc.jsx, src/templates/doc.scss, src/utils/typography.js
=> included font-styling

src/components/ContextualLinks/ContextualLinks.scss, src/components/LeftNav/LeftNav.scss, src/components/layout.jsx, src/components/layout.scss, src/templates/doc.jsx, src/templates/doc.scss
added responsive breakpoints in docs and orange full bar in left nav bar
=> added breakpoints and left nav orange bar from side to side

src/components/Header/Header.jsx, src/components/Header/Header.scss, src/components/Header/__snapshots__/Header.spec.jsx.snap, src/components/MarketingPages/Buttons.scss, src/components/MarketingPages/Cards.jsx, src/pages/getting-started.jsx, src/pages/index.jsx, src/pages/index.scss, src/pages/qa.jsx
- renamed v5_btn to btn
- fixed css on landing page
=> Landing page

src/components/Footer/Footer.jsx
decreased footer title size from h3 to h5
=> changed footer titles to h5

src/components/Header/Header.scss, src/components/LeftNav/LeftNav.scss, src/templates/doc.jsx, src/templates/doc.scss
- updated shadow on left navbar
- updated left padding to remove left white border
=> left navbar styling

src/components/Footer/Footer.jsx
added clearfix to footer and adjusted cols. Same as Website footer now.
=> added clearfix to footer

gatsby-config.js, package-lock.json, package.json, src/components/LeftNav/LeftNav.scss, src/components/seo.jsx
- added padding in left navbar 
- added Google Tag Manager
=> left nav styling, added GTM

src/components/Header/Header.jsx, src/components/Search/_search.scss, src/components/Search/searchPreview.jsx
also fixed a linting error in Header.
=> adding search highlighting

package-lock.json, package.json, src/templates/doc.scss
- changed background color of inline code 
- added padding to inline code
=> changed code background color

src/components/seo.jsx
adden og: metatags
added twitter metatags
omitted description
=> added opengraph and more twitter meta tags

.github/workflows/ci.yml, mdlint.sh
remove branch specific linting to test if this is the cause of inhibiting forked repos PRs from running Github Actions
=> removed branch specific linting

src/templates/doc.scss
add 40px of padding-bottom to .doc-page
=> add 40px of padding-bottom to .doc-page

src/pages/docs/postman/environments-and-globals/sessions.md
made sessions.md page_id lowercase & removed h2, active class now shows on left nav
=> 1832 made sessions.md page_id lowercase & removed h2, active class now shows

src/components/MarketingPages/Buttons.scss, src/components/Shared/EditDoc.jsx, src/templates/doc.jsx, src/templates/doc.scss
Component in src>components>Shared>EditDoc.jsx
=> basic functionality for edit this doc link

.github/workflows/ci.yml
=> fix: 🐛 check for image url github action

src/pages/docs/postman/environments-and-globals/variables-complete-reference.md, src/pages/docs/postman/environments-and-globals/variables.md, src/pages/docs/postman/scripts/postman-sandbox-api-reference.md, src/pages/docs/postman/scripts/test-examples.md
This PR adds documentation around pm.collectionVariables, addressing #1856.
=> Documentation for pm.collectionVariables

src/pages/docs/postman/collection-runs/newman-with-docker.md
fixes 1652
— updated command lines according to updated Docker page
=> 1652-updated command lines and links

src/pages/docs/postman-pro/managing-pro/roles-and-permissions.md, src/pages/docs/postman/collections/requesting-access-to-collections.md
Fixing https://github.com/postmanlabs/postman-docs/issues/1573 and https://github.com/postmanlabs/postman-docs/issues/1813
=> Request for Access changes and fixing Roles and Permissions

.github/stale.yml
-stalebot is not running so I changed the settings to the same settings we had in testing
=> changed stalebot settigs to test settings

src/pages/docs/postman/collections/managing-collections.md
=> Removing references to reordering collections

src/components/Shared/EditDoc.jsx
added ID to EditDoc button and cleaned up js
=> Editbutton ID

src/pages/docs/postman/launching-postman/sending-the-first-request.md, src/pages/docs/postman/sending-api-requests/requests.md
Requests page redraft and updated links in sending first request page since they seemed to have gotten messed up.
@claireriley hopefully not such a huge one this time 🙈
=> Requests redraft

src/pages/docs/postman/launching-postman/creating-the-first-collection.md, src/pages/docs/postman/launching-postman/installation-and-updates.md, src/pages/docs/postman/launching-postman/keyboard-shortcuts.md, src/pages/docs/postman/launching-postman/navigating-postman.md, src/pages/docs/postman/launching-postman/newbutton.md, src/pages/docs/postman/launching-postman/postman-account.md, src/pages/docs/postman/launching-postman/sending-the-first-request.md, src/pages/docs/postman/launching-postman/settings.md, src/pages/docs/postman/launching-postman/syncing.md, src/pages/docs/postman/sending-api-requests/requests.md
@nicktran as discussed, changed title to "sending your first request" and updated text on links to this page
=> Update sending first request title

redirects.json
Fixes #2046 
@Ryan-McBride this is another case of new redirect not working when someone comes from the old underscore url, for the moment I've just added underscore versions of all redirects..
=> Add underscore version of all redirects

src/pages/docs/postman/mock-servers/matching-algorithm.md, src/pages/docs/postman/mock-servers/setting-up-mock.md, src/pages/docs/postman/sending-api-requests/visualizer.md
Fixes #2031 
Fixes #2032 
Fixes #2052
=> Misc issue fixes

.github/workflows/deploy.yml, .github/workflows/prod-deploy.yml, email.js, logFile.sh, package-lock.json, package.json
Adding a H2 diff checker, which scans the PR for diffs between branches and creates an attachment that is emailed to a stakeholder. 
Testing with my email for now.
=> Adding H2 diff checker

src/pages/docs/postman/sending-api-requests/interceptor-extension.md
[Draft] Contains updates regarding installation, connectivity, and troubleshooting the interceptor <> native app integration
=> Updated interceptor documentation for Postman Native

src/pages/docs/postman/variables-and-environments/variables-list.md
{{$randomCounty}} no longer seems to work
=> remove non-functioning variable

src/pages/docs/postman/scripts/test-examples.md
=> Fixed typo in video link text

CONTRIBUTING.md
@tristandenyer @ch264 adding clarifications to develop branch usage we talked about, probably need a more comprehensive redraft tailored to staff vs community but hoping this gets the point across for the minute
=> Add detail on develop branch

src/pages/docs/postman/launching-postman/installation-and-updates.md, src/pages/docs/postman/launching-postman/introduction.md, src/pages/docs/postman/launching-postman/navigating-postman.md, src/pages/docs/postman/launching-postman/sending-the-first-request.md, src/pages/docs/postman/sending-api-requests/requests.md, src/pages/docs/postman/sending-api-requests/responses.md
=> Add links to api intro video series

redirects.json, src/pages/docs/postman/scripts/test-scripts.md
=> Test scripts redraft

src/pages/docs/postman/monitors/intro-monitors.md
This is my first monitoring-centric page draft ready for review (@ArjunSingh-PM since the UI is being updated shortly, it made the most sense for me to start here). 
This addition walks the user through the monitor dashboard and monitoring usage dashboard (not quite sure where to use monitor versus monitoring, let me know if anything sounds awkward) — two gaps that will be addressed once this is merged. I also rewrote the vast majority and reworked it to fit our style guide. 
Let me know what y'all think and happy weekend!
=> Intro to monitoring

src/pages/docs/postman-pro/managing-pro/billing.md
=> Fix broken link

src/pages/docs/postman/monitors/intro-monitors.md, src/pages/docs/postman/monitors/setting-up-monitor.md, src/pages/docs/postman/scripts/intro-to-scripts.md
removed Microsoft Case study PDF from 
src/pages/docs/postman/monitors/intro-monitors.md
src/pages/docs/postman/monitors/setting-up-monitor.md
src/pages/docs/postman/scripts/intro-to-scripts.md
=> removing Microsoft Case Studies PDF

src/pages/docs/postman/sending-api-requests/cookies.md
=> Fix misspelling

README.md
**What Changed?**
Added more information about postman to the second paragraph of _README.md_ file. 
**Why the change?**
This is so that people can have a better idea about what postman is and why they must use it. This reduces the confusion among the developers who are new to this concept of API testing and can have a quick _brief overview of the features_ that are provided to them by Postman
=> Extended the documentation for the second paragraph of README.md

src/pages/docs/postman/design-and-develop-apis/validating-relations-against-schema.md
This is a first go at the schema sync documentation, I'm not quite sure about the organisation of the page and I'm open to any suggestions!
I've tried to keep in mind the comments from previous PR but if I missed something apologies in advance.
@sankalp0o I haven't included the documentation for request validation since I'll do it on another page with another PR.
=> documentation for API relation validation

redirects.json, src/pages/docs/postman/launching-postman/installation-and-updates.md, src/pages/docs/postman/scripts/postman-sandbox.md, src/pages/docs/postman/sending-api-requests/authorization.md, src/pages/docs/postman/sending-api-requests/capturing-http-requests.md, src/pages/docs/postman/sending-api-requests/cookies.md, src/pages/docs/postman/sending-api-requests/interceptor.md, src/pages/docs/postman/sending-api-requests/proxy.md, src/pages/docs/postman/sending-api-requests/responses.md
Interceptor redraft—let me know what you think, re-styled and reworded a bit. Had trouble using active voice for some of the more prescriptive sections.
@abhijitkane could you particularly check the section "Troubleshooting tips"? That was one that I had to make a few assumptions on as it was a bit unclear. I did my best to maintain the original meaning of all sentences/sections here, just moved some words around.
=> Interceptor

src/pages/docs/postman/variables-and-environments/variables-list.md
=> Add old dynamic variables

src/pages/docs/postman/design-and-develop-apis/validating-elements-against-schema.md, src/pages/docs/postman/design-and-develop-apis/validating-relations-against-schema.md
**Please don't merge this until the schema validation update is in prod**
=> Revert "Revert "documentation for API relation validation""

.gitignore
@ch264 hopefully this does the trick 😬 give me a shout if I can try anything else
=> Revert gitignore changes

src/components/ContextualLinks/ContextualLinks.scss, src/templates/doc.jsx, src/templates/doc.scss
moved 'edit this doc' button to right hand side. Solves ticket #2118.
=> moved edit this doc button to right column

src/components/ContextualLinks/ContextualLinks.scss, src/components/LeftNav/LeftNav.scss, src/templates/doc.jsx, src/templates/doc.scss
solves ticket #2120 
- moved contextual links under the page content in tablet view
- added padding to bottom of contextual links in tablet and mobile view
- made contextual links full width in tablet view
- made left navbar and contextual links full width in mobile view
=> adjusted layout in tablet and mobile view

email.txt, logFile.sh, log_file.txt, src/pages/docs/postman-for-publishers/run-in-postman/creating-run-button.md, src/pages/docs/postman-pro/integrations/github.md, src/pages/docs/postman/collection-runs/command-line-integration-with-newman.md, src/pages/docs/postman/postman-api/continuous-integration.md, src/pages/docs/postman/scripts/test-examples.md
moving the comments to the next line fixes the layout problem.
=> moved comments on lower line

src/pages/docs/postman/collection-runs/command-line-integration-with-newman.md, src/templates/doc.scss
In order to fix the layout issues, the content within <pre> text is now wrapped.
=> added css to wrap <pre> tags content

src/pages/docs/postman/launching-postman/sending-the-first-request.md
@claireriley just a light redraft of the text on this page (def no rush, just been meaning to do it since it's getting more hits from the new intro page).
Fixes #2072
=> First request redraft

src/pages/docs/postman/monitors/intro-monitors.md
=> Fix typo intro to monitoring

package-lock.json, package.json
=> updating vulnerabilities except for gatsby@2.19.12 which breaks the app

src/pages/docs/integrations/github.md
@SueSmith Let me know if that's clear enough
=> Added plan details for github integrations

src/pages/docs/integrations/apimatic.md, src/pages/docs/integrations/bigpanda.md, src/pages/docs/integrations/coralogix.md, src/pages/docs/integrations/datadog.md, src/pages/docs/integrations/dropbox.md, src/pages/docs/integrations/github.md, src/pages/docs/integrations/gitlab.md, src/pages/docs/integrations/hipchat.md, src/pages/docs/integrations/intro-integrations.md, src/pages/docs/integrations/keen.md, src/pages/docs/integrations/microsoft-flow.md, src/pages/docs/integrations/microsoft-teams.md, src/pages/docs/integrations/pagerduty.md, src/pages/docs/integrations/slack.md, src/pages/docs/integrations/victorops.md, src/pages/docs/integrations/webhooks.md
=> Clarify pricing on integrations

src/pages/docs/postman/sending-api-requests/authorization.md
Fixes #2071 
Had originally added this to live preview draft docs but not sure what eta for that is in prod so just fixing this now..
=> Add api key auth detail

src/pages/docs/postman/sending-api-requests/validating-requests-against-schema.md
This is a first go at the request validation documentation. Any input highly appreciated :D
=> Documentation for request validation

src/pages/docs/integrations/apimatic.md, src/pages/docs/integrations/bigpanda.md, src/pages/docs/integrations/coralogix.md, src/pages/docs/integrations/datadog.md, src/pages/docs/integrations/dropbox.md, src/pages/docs/integrations/github.md, src/pages/docs/integrations/gitlab.md, src/pages/docs/integrations/hipchat.md, src/pages/docs/integrations/intro-integrations.md, src/pages/docs/integrations/keen.md, src/pages/docs/integrations/microsoft-flow.md, src/pages/docs/integrations/microsoft-teams.md, src/pages/docs/integrations/pagerduty.md, src/pages/docs/integrations/slack.md, src/pages/docs/integrations/victorops.md, src/pages/docs/integrations/webhooks.md
Adds note on integrations availability
=> Integrations pricing clarification

src/pages/docs/postman/sending-api-requests/interceptor.md
Updated the native interceptor guide by adding error codes that users may encounter during the installation of interceptor and manual resolution steps to resolve them.
=> Update error codes and their manual resolution steps for native interceptor guide

src/pages/docs/postman/scripts/postman-sandbox-api-reference.md
@arlemi could you give this a wee once over please 😬
=> Update and remove invalid sdk links

src/pages/docs/postman/collaboration/requesting-access-to-collections.md
This is pretty much the same as requesting access to collections but have still duplicated the content to get relevant screenshots for both cases.
=> Documentation for request access to APIs

src/pages/docs/postman/monitors/setting-up-monitor.md
@ArjunSingh-PM this is my first go at a full page revamp and filling all of those gaps. You'll notice in a couple places I used [X] or similar notation for information blanks that I'm hoping you can fill in. I think I covered almost all of the gaps and use cases we discussed, but let me know what I'm missing.
Let me know your thoughts on the overall format and approach as well—for instance, I kept screenshots to a minimum as I thought it'd look repetitive or disjointed if I attempted to break them up.
=> Update setting up a monitor

src/pages/docs/postman-for-publishers/public-api-docs.md, src/pages/docs/postman/api-documentation/authoring-your-documentation.md, src/pages/docs/postman/api-documentation/documenting-your-api.md, src/pages/docs/postman/api-documentation/viewing-documentation.md
Updates to API documentation docs for inline edit.
=> Inline edit updates

src/pages/docs/postman/api-documentation/documenting-your-api.md, src/pages/docs/postman/sending-api-requests/validating-requests-against-schema.md
=> Fixed broken link in validating requests against schema

src/pages/docs/postman/sending-api-requests/interceptor.md
Added steps to how to update interceptor extension.
=> Add interceptor update steps to interceptor native guide

src/pages/docs/postman/collections/version-control-for-collections.md
@ankit-m Have rewritten the page and added pull request detail - give me a shout if anything looks off or missing!
=> Pull request updates

src/pages/docs/postman/scripts/postman-sandbox-api-reference.md
Addresses some of the points raised in this issue - https://github.com/postmanlabs/postman-docs/issues/1725
=> Fixed typos in the dynamic variable table

src/components/MarketingPages/Buttons.scss
=> updated styles for secondary button 

src/pages/docs/postman/collaboration/roles-and-permissions.md, src/pages/docs/postman/design-and-develop-apis/view-and-analyze-api-reports.md
@claireriley pricing edit as mentioned in slack thread..
=> Pricing edit

.github/workflows/deploy.yml
Changing target bucket and adding --private flag to deploy script
=> migrating the deploy bucket for beta

src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md
Updated the create new API flow documentation from the Build view on the app. 
This is meant to go live on the 9th of March.
=> Updated create api workflow

src/pages/docs/postman-for-publishers/public-api-docs.md, src/pages/docs/postman/api-documentation/authoring-your-documentation.md, src/pages/docs/postman/api-documentation/custom-doc-domains.md, src/pages/docs/postman/api-documentation/publishing-your-docs.md, src/pages/docs/postman/collections/examples.md, src/pages/docs/postman/collections/using-markdown-for-descriptions.md, src/pages/docs/postman/scripts/branching-and-looping.md
Case study link updates as per [jira ticket](https://postmanlabs.atlassian.net/browse/LC-162).
=> update case study links

src/pages/docs/postman/sending-api-requests/requests.md
Split url encoding and invalid chars into two separate prs - this one is for updates that are in prod already, invalid chars one can wait until release..
=> URL processing

src/pages/index.jsx, src/pages/index.scss
fixes #2172 
@ch264 I wrote the media queries in `.scss` file entirely and removed the inline `style` attribute from the JSX tags. Would this be an acceptable approach?
=> fix video width in mobile view

src/pages/docs/administration/sso/microsoft-adfs.md, src/pages/docs/administration/sso/saml-in-azure-ad.md
@ArjunSingh-PM made a few copy edits so please check in case I've misinterpreted anything..
=> SSO updates

src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md
@arlemi could you have a wee check over this please?
=> New api spec create flow

src/pages/docs/postman/launching-postman/syncing.md, src/pages/docs/postman/workspaces/conflicts.md
@ankit-m update for new sync conflict resolution ui if you don't mind checking it over 🙂
=> Sync conflict ui update

src/pages/docs/postman/sending-api-requests/requests.md
Managed to miss a heading out.. also removing a bit that was repetitive - casualties of working on the same page on two different branches 🙃
=> Add heading

src/pages/docs/integrations/apimatic.md, src/pages/docs/integrations/github.md, src/pages/docs/integrations/gitlab.md
Fixes #1583 (finally going through some of these issues, better late than never 😬)
Fixes #1705 
@cyrielle-hada I've essentially just added your steps as a troubleshooting section here - whether this is all still up to date I'm not sure so if you could give it a read over that would be great!
=> Troubleshooting github sync

src/pages/docs/postman/workspaces/conflicts.md
@claireriley just added a bit of detail here
=> Sync conflict detail

src/pages/docs/postman/workspaces/changelog-and-restoring-collections.md
Fixes #2007 
@cyrielle-hada Hoping this does the job!
=> Recover folder detail

src/pages/docs/postman/sending-api-requests/requests.md
@claireriley just added a tiny bit of detail here
=> Adds whitespace / invalid char detail

src/pages/docs/administration/billing.md
=> Add set instructions for next billing cycle

README.md
Added instructions to build with Docker and Docker Compose to the README.
=> Add Docker build instructions to README

src/pages/docs/postman/collections/sharing-collections.md
Fixes #2040
@asi-postman just added a note, hoping it looks ok!
=> Delete vs remove info

src/pages/docs/administration/billing.md, src/pages/docs/administration/sso/intro-sso.md, src/pages/docs/postman/sending-api-requests/visualizer.md
Fixes #2297 
Thanks for the headsup @ch264 hoping this does the job
=> Link fixes

package-lock.json, package.json
Went from 2000 vulnerabilities to 12 low vulnerabilities
=> fixing vulnerabilities

package-lock.json, src/pages/docs/postman/collaboration/collaboration-intro.md, src/pages/docs/postman/workspaces/changelog-and-restoring-collections.md, src/pages/docs/postman/workspaces/intro-to-workspaces.md, src/pages/docs/postman/workspaces/using-workspaces.md
pulled from original pr because package lock change had sneaked in there
=> Workspace presence feature

src/pages/docs/postman/api-documentation/publishing-your-docs.md
Fixes #2280 
Hoping this does the job @cyrielle-hada 🙂
=> Doc discoverability note

src/pages/docs/postman/collection-runs/working-with-data-files.md
Fixes #2187 (I hope)
General redraft and update with assets / images kindly provided by @DannyDainton
=> Working with data files update

legacy-documentation/v5/getting_started/errors.md, src/pages/docs/integrations/github.md, src/pages/docs/postman-for-publishers/run-in-postman/creating-run-button.md, src/pages/docs/postman/collaboration/requesting-access-to-collections.md, src/pages/docs/postman/collections/commenting-on-collections.md, src/pages/docs/postman/collections/sharing-collections.md, src/pages/docs/postman/design-and-develop-apis/managing-apis.md, src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md, src/pages/docs/postman/design-and-develop-apis/validating-elements-against-schema.md, src/pages/docs/postman/mock-servers/setting-up-mock.md, src/pages/docs/postman/sending-api-requests/certificates.md, src/pages/docs/postman/sending-api-requests/validating-requests-against-schema.md, src/pages/docs/postman/workspaces/changelog-and-restoring-collections.md, src/pages/docs/postman/workspaces/creating-workspaces.md
I did not add the images of v5 legacy docs.
=> added images to aws for most recent version of docs - not for v5

src/pages/docs/postman/sending-api-requests/making-soap-requests.md
@loopDelicious had a go at redrafting the soap doc, can hold off until your blog post is up and add it in the right sidebar, added new pics too in case any of them are handy..
=> Redraft soap steps

src/pages/docs/postman/scripts/postman-sandbox-api-reference.md
Fixes #2281 
@loopDelicious hoping we'll develop some conventions around how we structure this content but for the minute I've just dumped these in the doc!
=> Visualizer sandbox update

src/pages/docs/postman/collection-runs/command-line-integration-with-newman.md
Slightly edited version of #2207
=> Newman options

legacy-documentation/v5/postman_for_publishers/run_button/run_button_API.md, src/pages/docs/postman-for-publishers/run-in-postman/run-button-API.md
@claireriley , this page has been optimized for:
* Scannability
* Conversational tone
* Info hierarchy
* Simple , non-Postman-specific language
=> Changes to rip api page

src/pages/docs/integrations/apimatic.md
Fixes #2332 
@claireriley gave this a very light redraft as well as adding the key info (just linked to apimatic docs)
=> Add key step

src/pages/docs/postman/scripts/pre-request-scripts.md
@claireriley just a light redraft since this is coming up pretty high in page views.. not entirely sure if I've picked good example usage since I hardly use pre-request scripts so all input appreciated!
=> Pre-request scripts redraft

src/pages/docs/postman/launching-postman/postman-account.md
Fixes #2286 
cc @cyrielle-hada @claireriley this page was woefully out of date so just gave it a general update
=> Account update

src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md
=> Correct typo in The API Wokflow docs

DOCS_STYLE_GUIDE.md, package-lock.json
To try out Postman community collaboration, made digstible more digestible. Thanks for pointing me to this style guide!
=> Fix 1 typo

src/pages/docs/postman/sending-api-requests/interceptor.md
Add manual installation steps for interceptor bridge installation for Mac, Linux, Windows.
=> Add manual installation steps for interceptor bridge installation 

src/pages/docs/postman/sending-api-requests/authorization.md
@claireriley new option in oauth 2.0 grant type..
=> PKCE update

src/pages/docs/postman/collections/data-formats.md
=> Remove RAML note

src/pages/docs/postman/sending-api-requests/capturing-http-requests.md
=> updated image urls

src/pages/docs/postman/sending-api-requests/authorization.md
@claireriley this is for tomorrow's release if you could have a wee pass through it for me 😬
=> Authorize in browser update

package-lock.json, src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md
I took the opportunity to update all the images on that page as I was making the updates. 
I'm also thinking this page is starting to get heavier, we could think of splitting it into different ones in future iterations.
=> Doc updates for API Dev 1.3

redirects.json, src/pages/docs/postman-for-publishers/run-in-postman/creating-run-button.md, src/pages/docs/postman/collection-runs/building-workflows.md, src/pages/docs/postman/collection-runs/integration-with-travis.md, src/pages/docs/postman/collections/creating-collections.md, src/pages/docs/postman/collections/data-formats.md, src/pages/docs/postman/collections/importing-and-exporting-data.md, src/pages/docs/postman/collections/sharing-collections.md, src/pages/docs/postman/launching-postman/installation-and-updates.md, src/pages/docs/postman/launching-postman/settings.md
Docs for upcoming 1.0 Importers release. 
Includes:
* Updated/refreshed content
* New page name
* Redirects
* Updated links
=> Update docs for new importers release

src/pages/docs/postman/design-and-develop-apis/managing-apis.md, src/pages/docs/postman/design-and-develop-apis/the-api-workflow.md, src/pages/docs/postman/design-and-develop-apis/validating-elements-against-schema.md, src/pages/docs/postman/design-and-develop-apis/versioning-an-api.md, src/pages/docs/postman/design-and-develop-apis/view-and-analyze-api-reports.md, src/pages/docs/postman/launching-postman/newbutton.md
Just changed the title as it appears in the page and nav to keep the url intact for the moment.
=> API builder page title change

.github/workflows/deploy.yml, .github/workflows/prod-deploy.yml
_Branched from `develop`_, this includes the MUNCHKIN_ID secret in the deploys.
_*No visuals_
=> [secret] MUNCHKIN_ID for workflows

src/components/CookieAlert.jsx, src/components/Footer/__snapshots__/Footer.spec.jsx.snap, src/components/LeftNav/LeftNav.jsx, src/components/Search/searchPreview.jsx, src/components/Shared/EditDoc.jsx, src/components/seo.jsx, src/pages/404.jsx, src/pages/index.jsx, src/templates/doc.jsx
_Branched from `develop`_, this merges `master` into `develop`, updates a snapshot, & does lint fixes.
w/ this branch `develop_merge-master`:
* It's concerning that commits that are in `master` (PROD), are not in `develop`, ATM; commits that harken back as far as Oct 30, 2019; _though only 9 files changed_
* confirmed `jest` runs successfully
* confirmed `npm run test:lint` runs clean
* crawling a locally running LC has no 404s
=> Develop merge master

src/pages/docs/postman/sending-api-requests/requests.md, src/pages/docs/postman/sending-api-requests/troubleshooting-api-requests.md
@claireriley have kept this to a minimum (I know the troubleshooting doc needs work beyond this but just aiming to get it updated for the error visibility improvement release..) 😬
=> Error visibility detail

src/pages/docs/postman-for-publishers/run-in-postman/introduction-run-button.md
Hi @SueSmith , this is quick PR. Just removed the sentence discussed on Slack. Thanks! 😊
=> Removed description format note

src/components/Footer/Footer.jsx, src/components/Footer/Footer.scss
Added our Twitch social icon to the footer.  Removed underline on hover from social icons, which caused a 1 pixel jump on some devices
=> Add in Twitch icon to footer

src/pages/docs/integrations/github.md, src/pages/docs/postman/mock-servers/setting-up-mock.md, src/pages/docs/postman/sending-api-requests/debugging-and-logs.md, src/pages/docs/postman/sending-api-requests/generate-code-snippets.md, src/pages/docs/postman/sending-api-requests/interceptor.md, src/pages/docs/postman/sending-api-requests/requests.md, src/pages/docs/postman/variables-and-environments/managing-environments.md
Just added some recent blog posts that followed feature release to docs sidebar (need to build this into the release docs flow..)
cc @kinlane @loopDelicious
=> Add recent blog posts

src/pages/docs/administration/billing.md, src/pages/docs/postman-for-publishers/api-network/add-api-network.md, src/pages/docs/postman/api-documentation/publishing-your-docs.md, src/pages/docs/postman/launching-postman/syncing.md, src/pages/docs/postman/sending-api-requests/interceptor.md
pulling the new request for Add note on prorated plan changes
=> Add note on prorated plan changes

src/pages/docs/postman/collections/examples.md, src/pages/docs/postman/design-and-develop-apis/validating-elements-against-schema.md
Name change from Ingur to Imgur.
Fixes #2410
Image in validating-elements-against-schema changed.
Fixes #2357
=> New branch- Ingur to Imgur

src/pages/docs/postman/api-documentation/publishing-your-docs.md
- Update live preview for documentation
- Add client-side scanner 
Pending
- Upload screenshot to S3
- Publish blog post for Related Blog Posts in sidebar - in review
=> add client scanner

src/pages/docs/postman/api-documentation/documenting-your-api.md
Hi @SueSmith , I switched the image in "Documenting your API" to a prod image. Thanks! 😊
Fixes #2448
=> Replaced beta image w/ prod image

src/templates/doc.scss
remove z-index to fix left-nav
=> fixed left-nav bug 

src/pages/docs/postman/mock-servers/setting-up-mock.md
Described the response in case of outages and added a link to status page
=> Add troubleshooting tip for outages on mock servers

src/components/LeftNav/LeftNav.scss
=> feature: add hover to left navbar link

src/components/Footer/Footer.data.json
=> (fix) : update jobs to careers

src/pages/docs/postman/sending-api-requests/certificates.md, src/pages/docs/postman/sending-api-requests/responses.md
Added basic content for network info - our responses material is very minimal just now, will try and get that built out one of these days..
@appurva21 if you have time could you give this a wee read over for me 🙏 
**22nd Jun app release**
=> Network info

src/pages/docs/postman/variables-and-environments/variables.md
@appurva21 Another one for you 😬 
_Made a note to do a more general update for the readonly collection details view in the collaboration docs section at some point too._
**22nd Jun app release**
=> Collection var viewer access

src/pages/docs/postman/launching-postman/newbutton.md
@claireriley sorry for the avalanche of review requests, if they don't all get reviewed nbd will just publish on mon and we can refine later.. 😭 this one is for the new button which is having the dropdown list removed, the new button doc is getting binned in the restructure (and gets hardly any views) so have kept this to the absolute bare minimum, screengrabs of it are all over the place so will need to be updated in the longer term anyway 🙃
=> Dropdown removal

src/pages/docs/postman/collaboration/collaboration-intro.md, src/pages/docs/postman/launching-postman/postman-account.md
@prashantagarwal Hopefully this covers it! Please give me a shout with any issues.
=> Team discovery flow

src/pages/docs/postman/sending-api-requests/authorization.md
**For 22nd June release**
Includes:
* OAuth 1.0 body hash, callback / verifier, signature methods / secret vs key fields
* OAuth 2.0 custom prefix
* AWS headers / url selection
* Digest auth SHA addition
@vikiCoder if you get a chance to check this over it would be much appreciated 🙂
=> Auth updates app 7.27

src/pages/docs/postman-for-publishers/api-network/add-api-network.md, src/pages/docs/postman/collaboration/adding-private-network.md, src/pages/docs/postman/design-and-develop-apis/managing-apis.md, src/pages/docs/postman/variables-and-environments/managing-environments.md, src/pages/docs/postman/variables-and-environments/variables.md
- Add overview page
- Add version support
=> Private API Network

redirects.json
{
"from": "/docs/postman/environments-and-globals/variables/",
"to": "/docs/postman/variables-and-environments/variables/"
},
=> added redirect 

src/pages/docs/postman/collaboration/adding-private-network.md
=> add sharing to private network from app

src/pages/docs/postman/collections/version-control-for-collections.md
Modified the Learning Center for Version Control!
=> Version control- PR Approval Flow

src/components/CookieAlert.jsx, src/components/Footer/Footer.jsx, src/components/Header/Header.jsx, src/components/LeftNav/LeftNav.jsx, src/components/MarketingPages/Cards.jsx, src/components/MarketingPages/Slider.jsx, src/components/Search/searchPreview.jsx, src/pages/404.jsx, src/pages/concepts.jsx, src/pages/index.jsx, src/pages/reference.jsx, src/utils/algolia.js
Hey, I fixed a couple of linter issues and console errors
=> fix linter issues for develop

src/pages/docs/collaborating-in-postman/requesting-access-to-collections.md
I have added an alt tag in the image tag. 
Issue :
no html <img> tags good first issue
#2323 opened on Apr 15 by ch264
changes made in src/pages/docs/collaborating-in-postman/requesting-access-to-collections.md.
=> Added alt tag to 1 img tag

src/pages/docs/writing-scripts/script-references/variables-list.md
Added $isoTimestamp to dynamic variable list. [GH-1060](https://github.com/postmanlabs/postman-collection/pull/1060) on postman-collection.
=> Add $isoTimestamp to variable list

src/pages/docs/collaborating-in-postman/requesting-access-to-collections.md
Added ALT Tags in the image tags in which they were missing and some Markdown syntax for images had alt information the same as an image link. Therefore I removed the link from alt tags and places some meaningful text.
=> Added Alt tag in requesting-access-to-collections.md

src/pages/docs/getting-started/introduction.md, src/pages/docs/getting-started/navigating-postman.md, src/pages/docs/sending-requests/responses.md, src/pages/docs/sending-requests/troubleshooting-api-requests.md
**7.28 release**
Mainly image updates with a little text adjustment @coditva if there's anything else you think should be highlighted please give me a shout!
=> Console and resizable panes

src/pages/docs/sending-requests/requests.md
=> URL processing default

src/pages/docs/writing-scripts/script-references/variables-list.md
Reverts postmanlabs/postman-docs#2519
Will be in app 7.29
=> Revert "Add $isoTimestamp to variable list"

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/faqs-monitors.md, src/pages/docs/designing-and-developing-your-api/monitoring-your-api/using-static-IPs-to-monitor.md
@ArjunSingh-PM this should address MONITOR-1443 and MONITOR-1451. I also did a quick rewrite of the "Running Postman monitors using static IPs" page to bring it more in line with our docs style guide.
=> Static IP clarification + edits

src/pages/docs/getting-started/importing-templates.md, src/pages/docs/getting-started/introduction.md, src/pages/docs/getting-started/sending-the-first-request.md, src/pages/docs/sending-requests/generate-code-snippets.md, src/pages/docs/sending-requests/supported-api-frameworks/graphql.md, src/pages/docs/sending-requests/visualizer.md, src/pages/docs/writing-scripts/intro-to-scripts.md
* updated app overview pic
* updated first request pic from @DannyDainton 
* autocomplete gif via @arlemi 
* vids as per WEBSITES-763 and WEBSITES-621
* link to public rest api collection from @kinlane 
* updated postman echo link
=> Misc pics and videos

src/pages/docs/getting-started/installation-and-updates.md, src/pages/docs/getting-started/introduction.md
@claireriley just a note pointing at the Artemis blog posts and forum post..
=> Artemis callout

src/pages/docs/designing-and-developing-your-api/the-api-workflow.md, src/pages/docs/designing-and-developing-your-api/validating-elements-against-schema.md
=> Schema validation 

src/pages/docs/running-collections/using-newman-cli/command-line-integration-with-newman.md
New gif courtesy of @DannyDainton 🏆
=> Newman gif

src/pages/docs/publishing-your-api/run-in-postman/creating-run-button.md, src/pages/docs/publishing-your-api/run-in-postman/introduction-run-button.md, src/pages/docs/publishing-your-api/run-in-postman/run-button-API.md
- Updated the Run in Postman section.
- Added modal screenshot of View in web or app
=> Rip in web

src/pages/docs/writing-scripts/script-references/test-examples.md
@vdespa finally got the script examples revamp in here - it still has some bits that will live in other places once we have them added (non test script related info), let me know any issues!
=> Script examples revamp

src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md
Starting with the intro page, will add the rest to the same PR..
=> Mock redrafts

src/pages/docs/sending-requests/supported-api-frameworks/graphql.md
Added GraphQL video to additional resources links in sidebar
=> GraphQL links added in sidebar

src/pages/docs/getting-started/introduction.md
Just an updated pic for the intro page to reflect comment mode ui change..
=> App img update for comment ui

src/pages/docs/getting-started/importing-and-exporting-data.md
Reverts postmanlabs/postman-docs#2605
=> Revert "Revert "Docs for importing several API specs at once""

src/pages/docs/getting-started/importing-and-exporting-data.md
Reverts postmanlabs/postman-docs#2607
lol
=> Revert "Revert "Revert "Docs for importing several API specs at once"""

src/pages/docs/designing-and-developing-your-api/view-and-analyze-api-reports.md
New branch updated with the reporting feature documentation.
=> Reporting docs

src/pages/docs/integrations/available-integrations/apimatic.md
=> FIX #2610 [Link Fix]

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/viewing-monitor-results.md
Added section for viewing individual monitoring activity logs.
=> Add activity log

gatsby-config.js, src/components/Header/Header.jsx, src/components/Header/__snapshots__/Header.spec.jsx.snap
added GA tracker to LC sign in button and changed Dashboard to Launch + GA
=> sing in + launch postman in navbar

src/pages/docs/writing-scripts/script-references/postman-sandbox-api-reference.md, src/pages/docs/writing-scripts/script-references/variables-list.md
@vdespa finally got this one drafted 😅 feedback appreciated (like the previous one am leaving the external libs bit in until we have a new page for it)
=> Sandbox redraft

src/pages/docs/getting-started/importing-and-exporting-data.md
Reverts postmanlabs/postman-docs#2609
For real this time.
=> Revert "Revert "Revert "Revert "Docs for importing several API specs at once""""

src/pages/docs/designing-and-developing-your-api/mocking-data/setting-up-mock.md, src/pages/docs/designing-and-developing-your-api/the-api-workflow.md
=> Mock delay + schema autocomplete

src/pages/docs/sending-requests/certificates.md
This PR is to fix documentation on FAQs Let’s Encrypt SSL certificates #2444
=> documentation on FAQs Let’s Encrypt SSL certificates

src/pages/docs/publishing-your-api/publishing-your-docs.md
This PR is to update Clarify docs edits and explore listings
=> Clarify docs edits and explore listings #2348

src/pages/docs/sending-requests/capturing-request-data/interceptor.md
Updating to add the new UI flow for adding a custom encryption key to Interceptor.
=> Add encryption key UI section

src/pages/docs/collaborating-in-postman/adding-private-network.md
You will be able to organize APIs shared in your Private API Network into folders.
=> Folders in Private API Network

src/pages/docs/getting-started/importing-and-exporting-data.md
Added section for release coming up early next week.
@umeshp7 I used the screenshot with the failed import as a placeholder—do you mind sending me a fully successful screenshot?
Also blurred out "beta" mentions 😅 can update that once in prod
=> Add github bulk import

src/pages/docs/sending-requests/variables.md
New set as var from request builder flow that was added last week.. 😅
=> Set as var flow

CONTRIBUTING.md
=> Fixed a Typo in CONTRIBUTING.md

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/troubleshooting-monitors.md
Removed the incorrect bullet point and screenshot.
https://github.com/postmanlabs/postman-docs/issues/2183
=> Fix for  #2183

src/pages/docs/integrations/available-integrations/datadog.md
Quick update for IS-522 + the new region option.
=> Add eu update

src/pages/docs/getting-started/importing-and-exporting-data.md
Gif for importing multiple schemas at once was not up to date as we've removed the ability to choose the workspace you want to import in.
=> Updated gif for import

src/pages/docs/getting-started/installation-and-updates.md
Add a link to downloads page to download the desktop agent (if user has closed the initial modal prompt)
Related to #2651 - Clarify How to Install Desktop Agent After Closing Web Modal (BETA)
=> add blog link and agent download link

src/pages/docs/designing-and-developing-your-api/monitoring-your-api/intro-monitors.md
Fixes #2572 
Reviewers:
@ch264 
@claireriley
=> replace Monitoring APIs with Monitoring your APIs
